### PR TITLE
Bug 389

### PR DESCRIPTION
**Pull request by abhikulshrestha22**
#389 Fix 
Buttons in top left panel gets horizontally centered. 
Screen Shot 2020-01-17 at 11 46 36 PM

### CODE REVIEW

**Comment by abhikulshrestha22** [comment]
@lipis should I marked the issue closed as well?

**Comment by lipis** [comment]
It's merged... so there is nothing more to this branch... you can delete it if you want to.

**Comment by abhikulshrestha22** [comment]
No, I mean the issue #389 still shows up as open issue. Should we mark it as closed.

**Comment by lipis** [comment]
Closed it :) Thanks!

**Pull request merged**
