### PR TITLE
[Not For Merge]: Rollup of #2993

### LINKED ISSUE #1176: Support for writing / rendering math equations
It would be nice to support math equations embedded in text. Imagine the cool diagrams you can draw with labels using this support to illustrate geometry and physics problems.

One way to implement this would be to integrate [LaTeX math mode](https://artofproblemsolving.com/wiki/index.php/LaTeX:Math#Math_Mode) in text. For example, `$d = \sqrt{x^2 + y^2}$` would show up as .

Potential challenges:
1. Can this be done in a lightweight manner?
2. How difficult would it be to support artistic rendering in this mode?

### PR DESCRIPTION
**Pull request by DanielJGeiger**
Take 2 rolling up #2993:
- Lazy-loads MathJax and only after math is detected.
- Renders math only if math formulas are present.
- Uses standard Latex input as well as simplified AsciiMath input.
- Supports math formulas in bound text.
- Contains preliminary screen-reader support.

Other points:
- This PR provides an `@excalidraw/extensions` package (not to be confused with "plugins").
- `@excalidraw/excalidraw` receives features of independent interest:
  - A subtype system for custom extensions of `ExcalidrawElement` (eg, permitting inline `code`, UML diagrams, etc).
  - Custom actions and shortcuts independent of `ExcalidrawElement` subtypes.
- The MathJax extension in `@excalidraw/extensions` demonstrates use of the `ExcalidrawElement` subtype system.
- Since MathJax resides in `@excalidraw/extensions`, MathJax support is entirely decoupled from `@excalidraw/excalidraw`.

Tested in virtual and in-person classrooms.

See the description of #3915 for an overview of custom actions/shortcuts and the `ExcalidrawElement` subtype system.

See #2993 for the list of various issues fixed.

### CODE REVIEW

**Comment by ad1992** [comment]
HI @DanielJGeiger, sorry for not being responsive on your PR. 
Before we start the review I was thinking about a plugin like integration where users can install the extra add-ons / plugins for more functionalities.

* This would also mean that it will be completely decoupled from the codebase and will go into some repo lets say `@excalidraw/plugins` which is a big plus point
* It will not add it by default keeping Excalidraw as is and interested users can install the extension to try out
* It will be easier and faster to add extensions 

This will mean we will need to come up with a workflow / UI and API for plugins as well which would take some time but I think this this would be worth it and will make the process of adding plugins very smooth and easier once merged in the repo `@excalidraw/plugins`.

Let me know your thoughts. cc @dwelle.

**Comment by DanielJGeiger** [comment]
Hi @ad1992, thanks for your reply.  I think `@excalidraw/plugins` is a great idea.

I would propose making a version of https://excalidraw.com with `@excalidraw/plugins` included, something like https://full.excalidraw.com.  Then academics like myself could have our students use https://full.excalidraw.com without pointing them to preview versions of PRs.  @mcaruel @baptiste what do you think?

**Comment by baptiste** [comment]
Very much in favour of having a permanent URL like you suggest, to access optional plugin functionalities. Maybe the list of plugin(s) in use could be user-selected, if some happen to be incompatible with others or just not needed.

You've done a fantastic job Daniel, with this Mathjax integration, and I imagine a lot of STEM instructors will jump at this opportunity to combine online sketches and maths for their virtual classes. The only thing that's prevented me from sharing it with academic colleagues for the past year is a lack of a permanent-looking URL (giving confidence that it's worth investing time in the tool).

Thanks so much for your continued efforts on this.

**Comment by DanielJGeiger** [comment]
@ad1992 @dwelle What do you think of the following?  Let's have an initial release of the `@excalidraw/plugins` API support `ExcalidrawElement` subtype plugins, with MathJax as an example.  This PR would land in both packages: `src/subtypes/math/*` would go in `@excalidraw/plugins`, and the rest in `@excalidraw/excalidraw` as part of the API and UI.

This would also benefit people who wanted to create plugins for Kroki/Mermaid etc.  Then future releases would expand the `@excalidraw/plugins` API.

**Comment by DanielJGeiger** [comment]
@dwelle @ad1992 I'm trying marking all my PRs as drafts except for the one I'd for you to review next.  Hopefully this makes it easier for you to review my work amid everything you have going on as the lead @excalidraw devs.

**Comment by mcaruel** [comment]
@DanielJGeiger : You're doing such a great job. This LaTeX feature is really cool !

**Comment by DanielJGeiger** [comment]
@jcezarms I'm glad to hear this works so reliably for you.  On a technical note, #2993/#5311 provide MathJax support as an "extension" rather than a "plugin".  Per discussions with @dwelle, extensions are reviewed by the Excalidraw team, whereas plugins are community-made without review from Excalidraw.

I can not say for certain, but I believe the answer to your question would be, #2993 mainly just needs review by someone from @excalidraw.  (I doubt it would take much work to put extensions on subdomains like "math.excalidraw.com".  Also, I provided a way to select which extensions get loaded.)

@mcaruel @baptiste

**Comment by DanielJGeiger** [comment]
@jcezarms @mcaruel @baptiste This PR is starting to become cluttered itself, with Vercel deployments of force-pushes.  Maybe further discussions should go in #1176 or #5265.

**Comment by DanielJGeiger** [comment]
This is not the PR you are looking for: closing in favor of #2993.

**Pull request closed without merging**
