### PR TITLE
feat: shortcut for clearCanvas confirmDialog

### LINKED ISSUE #5818: Reset Scene Shortcut
Before the redesign, we always had the button for deleting the whole scene accessible with one 1 click. 

Now that we currently need 2 clicks in order to reach the Reset Scene button, it may be interesting to add a shortcut to do so.
I personally attempted to do it but it's not implemented

I would prefer `Shift+Del`.
I've got a commit ready, will open a PR soon.

### PR DESCRIPTION
**Pull request by proke03**
resolve #5818

### CODE REVIEW

**Comment by proke03** [comment]
@dwelle
Could you please approve the workflow?

**Comment by ad1992** [comment]
> @dwelle Could you please approve the workflow?

should work now

**Comment by proke03** [comment]
thank you!

**Comment by proke03** [comment]
@ad1992
Could you please approve the workflow?
Fixed issues with lint and test.

**Comment by dwelle** [comment]
Hi @proke03, thanks for the PR.

We should still prompt for confirmation regardless of how the clear canvas is invoked. This will require a bit of refactor that I did in https://github.com/excalidraw/excalidraw/pull/6152, so we'll need to merge that first.

**Comment by proke03** [comment]
Thank you, @dwelle !
After the PR you mentioned was merged, I implemented it again.
Could you review this PR?

**Review by dwelle — APPROVED** [review]

**Pull request merged**
