### PR TITLE
feat: simple impl of multi font support, for chinese font

### PR DESCRIPTION
**Pull request by alswl**
This is a feature of multi font support, and especially for Chinese font.

There are three solution for CJK hand writing style font:

1. add a new font(eg. HandWritingCN) after Hand-Drawn, Normal, Code.
    - https://github.com/excalidraw/excalidraw/pull/2429 (This is full solution)
    - https://github.com/excalidraw/excalidraw/pull/3409 (This is full solution)
    - https://github.com/excalidraw/excalidraw/issues/5259
    - https://github.com/excalidraw/excalidraw/issues/1290
2. Using multi font for font-family, Virgil is first font, and if Virgil missing, the second(eg. HanziPen SC) will be enabled
3. Patching Virgil font file, add CJK(more then thousands unicode) 
    - https://github.com/excalidraw/excalidraw/issues/5370 imp

In my solution, I choose 2.

By using system including fonts(macOS HanziPen SC, Windows Kai), I do not add any external fonts.

Demo:

image

### CODE REVIEW

**Comment by alswl** [comment]
ping @ad1992

**Comment by jcyh0120** [comment]
I tried this pull request and it works. Could you merge this PR?

**Comment by ad1992** [comment]
@alswl since you are adding "HanziPen SC" as a fallback for Virgil so will you be disabling virgil in order to use it? 
Also since its a system font, I think adding as a fallback under "normal" would be better option.

**Comment by alswl** [comment]
@ad1992 
> so will you be disabling virgil in order to use it?

No, I think the Virgil is a better style for English font, and "HanziPen SC fallback" solution will keeps others diagram looks the same in the solution.

> I think adding as a fallback under "normal"

As you see, the 'HanziPen SC" is a hand writing style, not a regular font style. I think this font is an alternative for Chinese font, not the alternative for "Normal".

**Comment by jcyh0120** [comment]
Is it possible to add a handwriting chinese web font? HanziPen SC looks great but only works on system font. I cannot use it in ipad.

**Comment by jcyh0120** [comment]
> > Is it possible to add a handwriting chinese web font? HanziPen SC looks great but only works on system font. I cannot use it in ipad.
> 
> The cost of embedding font files is high. There are too many CJK fonts, which may require 5M-20M to store and transfer.

I see. I've tried installing the same font on my iphone and ipad but no luck. Seems that mobile browser doesn't apply the system Hanzipen SC font on portable devices. But it works on my macbook.

**Comment by alswl** [comment]
This is a instance http://excalidraw.alswl.com/ .
Static // Support Chinese font // No Collaboration

**Comment by alswl** [comment]
@ad1992 Friendly ping.

**Comment by PhantomMaa** [comment]
approve the pr

**Comment by linguax-gc** [comment]
> This is a instance http://excalidraw.alswl.com/ . Static // Support Chinese font // No Collaboration

Tried using this, but I don't get the handwritten font. Do I need to do something special? I'm on Windows, if that matters.

**Comment by alswl** [comment]
@linguax-gc Maybe the Windows  Chinese handwriting is missing? I'm using `Kai` as name of 楷体。
According to https://xuui.net/ui-design/english-name-of-chinese-characters-table.html , I should fix to `KaiTi`.

**Comment by linguax-gc** [comment]
@alswl I have KaiTi on my system, so maybe it's because of the name you used for the font, yes. I just tried on mobile (Android) and it doesn't work either. So, unfortunately, your solution is not viable immediately on all platforms, which I think it's a problem. I don't believe Android has a handwritten font included in the system fonts. Not sure about iOS, but going by what @jcyh0120 said above it doesn't either.

In any case, HanziPen SC looks suitable for the Excalidraw aesthetic, but I'm not so sure about KaiTi. I use it for documents, but I don't believe it fits with the sketchy visuals of Excalidraw.

I believe, for the public website, another solution might be needed. Maybe having an option to manually activate the Virgil with Xiaolai as fallback font (#5370 ) and have it downloaded and activated if the user wishes to? Or maybe automatically loading it when the language of the site is changed to Chinese?

I understand the size of the file (14 mb) might be a problem for some connections, but using normal squary fonts as it is now is certainly not working visually.

As I said on the other issue I ended up compiling an offline version of Excalidraw on Docker and replacing the original Virgil font with the one with fallback to XiaoLai, so I can finally work with handwritten font on Chinese, but having the feature on the public website is the most desirable outcome, obviously.

Hope @dwelle doesn't mind my mentioning them to ask about the devs' thoughts on this issue.🙏

**Comment by alswl** [comment]
@linguax-gc can you try this one in your Windows? This is a version using `KaiTi` instead of `Kai`.
https://e2da098c.excalidraw-alswl-com.pages.dev/

**Comment by linguax-gc** [comment]
@alswl 

> @linguax-gc can you try this one in your Windows? This is a version using `KaiTi` instead of `Kai`. https://e2da098c.excalidraw-alswl-com.pages.dev/

@alswl I just tried, and it is still not showing KaiTi for me. :(

**Comment by alswl** [comment]
@linguax-gc so sad. It works for me in a Windows 10 laptop.

(though the KaiTi did not looks pretty).

image

**Comment by linguax-gc** [comment]
@alswl Checked again and still nothing. I'm on Windows 11. I looked at my installed fonts and the 楷体 font is called like that in Word, for example, but the ttf name is SIMKAI.TTF, and there's another one called STKAITI.TTF. Both provide the standard Kai calligraphy script.

I still think it doesn't really suit the aesthetics of Excalidraw. Wouldn't it be possible to add Xiaolai (https://github.com/lxgw/kose-font) as the font family, but instruct the user to install it on their system instead of embedding it? (Although embedding is, apparently, the only solution for mobile devices.)

**Comment by alswl** [comment]
> the ttf name is SIMKAI.TTF, and there's another one called STKAITI.TTF

Thanks, I think the new Windows version using the new hand-writing fonts.

> instruct the user to install it on their system instead of embedding

This requirement is beyond the scope of this pull request and I think you can draft a new pull request.

**Comment by Mrazator** [comment]
Closing in favor of https://github.com/excalidraw/excalidraw/pull/8530.

**Pull request closed without merging**
