### PR TITLE
fix exporting lines as svg

### PR DESCRIPTION
**Pull request by dwelle**
fixes https://github.com/excalidraw/excalidraw/issues/835

### CODE REVIEW

**Comment by Fausto95** [comment]
Looks like the svg export button is no longer working

**Comment by dwelle** [comment]
@Fausto95  Works for me. Can you create an issue with steps to repro?

**Comment by dwelle** [comment]
Ok, I got it.

**Comment by dwelle** [comment]
Bloody hell, such an easy fix and I make such a glaring error. So much for thinking I don't need a review on this one :).

**Pull request merged**
