### PR TITLE
fix: spacebar grabbing

### PR DESCRIPTION
**Pull request by Jeffsingh**
Before holding spacebar would show the grab icon but it would not allow the user to grab by holding space bar and drag. 
This fixes that issue by allowing the user to move the selected items while holding the space bar. This was originally mentioned in [6007](https://github.com/excalidraw/excalidraw/issues/6007)

### CODE REVIEW

**Comment by dwelle** [comment]
I still don't understand what the original issue was about, or this PR is trying to fix.

If it's to make holding spacebar pan the canvas without dragging the mouse (i.e. clicking down on canvas and moving your mouse while you still hold the left mouse button), then we don't want to do that because that would go against the standard behavior. (Note that this PR is not doing that.)

**Comment by Jeffsingh** [comment]
@dwelle The original issue as I understood it was that when a user would try to grab something by holding down the spacebar and then drag that item by moving the mouse with the spacebar down, the grab icon would show but nothing would move. So by capturing the last mouse positions when the key spacebar is pushed down...we act as if it is a pointer down event and allow the items selected to be dragged. This does work and does fix the issue. Before, the grabbing icon would show and nothing would move. I attempted to fix this as @TinQk identified this in [issue #6007](https://github.com/excalidraw/excalidraw/issues/6007)

**Comment by mickremedi** [comment]
Hmmm I'd have to agree with the solution that @dwelle made earlier in #6015. The issue seemed to focus on moving the canvas more than moving individual items. So just switching the mouse icon makes it more clear!

**Comment by mickremedi** [comment]
Although I do like the idea of the hotkey click-and-drag elements functionality. It could speed up the flow of someone drawing shapes and wanting to move them quickly while not leaving whichever shape tool they're currently at. It could be worth bringing up as a new binding?

**Comment by Jeffsingh** [comment]
@mickremedi how would the hotkey binding work?

**Comment by mickremedi** [comment]
@Jeffsingh Say you're currently creating a bunch of circles for a diagram, but while you're drawing, you realize you need to move one of the drawings out of the way. Currently, you would have to press a key to switch to selection mode, move the drawing, and press a key to switch back to whatever tool you're using. A possible approach is that you would hold a modifier key (e.g. CMD/CTRL) and you temporarily switch back to selection mode, where you do the quick move, and when you let go of the key, you go back to whatever tool you were using before.

**Pull request closed without merging**
