### PR TITLE
tweak png copy button label

### PR DESCRIPTION
**Pull request by dwelle**

### CODE REVIEW

**Comment by lipis** [comment]
Run `yarn` locally to get the latest changes.. and I don't get why they are warnings instead of errors..?!

**Comment by j-f1** [comment]
They’re warnings because the `prettier/prettier` ESLint rule is only a warning, not an error.

**Comment by dwelle** [comment]
The fact it's a warning is correct. My bad on `yarn`. I did that over at `excalidraw-blog` and forgot to do it here.

**Comment by lipis** [comment]
The lint tasks should fail though.. that's not good that it's a warning in this case.

**Comment by dwelle** [comment]
It should fail on warnings, too. I'll take a look.

**Pull request merged**
