### PR TITLE
fix: docker build of Excalidraw app

### LINKED ISSUE #7403: [ Bug ] Docker image on Dockerhub not updated for 4 months
The docker image on Dockerhub hasn't been updated for 4 months.

Given that the latest release is ~3 weeks old, there may be an issue with the github action.

### PR DESCRIPTION
**Pull request by agebhar1**
Fixes #7403.

### CODE REVIEW

**Comment by ad1992** [comment]
@agebhar1 can you confirm if the updated docker build in this PR works for you ?

**Comment by agebhar1** [comment]
As far as I can remember yes @ad1992, but let me check again today.

**Comment by agebhar1** [comment]
There was a small issue left but now the container is build @ad1992. Also updated to latest version of Nginx.

**Comment by agebhar1** [comment]
Any chance to get this PR merged @ad1992?

**Review by aolyang — COMMENTED** [review]
this fix works fine and no bad side effect.

image

image

**Comment by AlphaCraft9658** [comment]
This should be merged.

**Comment by ad1992** [comment]
since its been long time, @agebhar1 @AlphaCraft9658  can one of you test the build and confirm if this PR is good to go?

**Comment by AlphaCraft9658** [comment]
> since its been long time, @agebhar1 @AlphaCraft9658  can one of you test the build and confirm if this PR is good to go?

How should I test it? Clone and build, or with GitHub Cl?

**Comment by ad1992** [comment]
> > since its been long time, @agebhar1 @AlphaCraft9658  can one of you test the build and confirm if this PR is good to go?
> 
> How should I test it? Clone and build, or with GitHub Cl?

Yes, Running the docker build command locally and testing it out.

**Comment by AlphaCraft9658** [comment]
> > > since its been long time, @agebhar1 @AlphaCraft9658  can one of you test the build and confirm if this PR is good to go?
> > 
> > How should I test it? Clone and build, or with GitHub Cl?
> 
> Yes, Running the docker build command locally and testing it out.

I'll do that on my homelab in a second.

**Comment by AlphaCraft9658** [comment]
> > > since its been long time, @agebhar1 @AlphaCraft9658  can one of you test the build and confirm if this PR is good to go?
> > 
> > How should I test it? Clone and build, or with GitHub Cl?
> 
> Yes, Running the docker build command locally and testing it out.

I'll do that on my homelab in a second.

**Comment by aolyang** [comment]
I have done test for locally, see https://github.com/excalidraw/excalidraw/pull/7430#pullrequestreview-1938234215

and https://excalidraw.aolyang.me/

I have used for a time, just try it

image

**Comment by AlphaCraft9658** [comment]
> I have done test for locally, see https://github.com/excalidraw/excalidraw/pull/7430#pullrequestreview-1938234215
> 
> and https://excalidraw.aolyang.me/
> 
> I have used for a time, just try it
> 
> image
> 
> 

It doesn't work for me and it says that cross-env is not found.

**Comment by AlphaCraft9658** [comment]
> since its been long time, @agebhar1 @AlphaCraft9658  can one of you test the build and confirm if this PR is good to go?

I tested it. The build succeeds.

**Review by ad1992 — APPROVED** [review]
Thanks @aolyang @AlphaCraft9658 @agebhar1 , merging 🚀

**Comment by AlphaCraft9658** [comment]
Tests are failing.

**Comment by AlphaCraft9658** [comment]
> Tests are failing.

@ad1992 ?

**Comment by AlphaCraft9658** [comment]
Any ETA on when the next release with this fix will be pushed? It should automatically build and push to docker hub, if everything works now, including the publish workflow.

**Comment by ad1992** [comment]
> Any ETA on when the next release with this fix will be pushed? It should automatically build and push to docker hub, if everything works now, including the publish workflow.

I will wait for some time to push to release so at max by tomorrow it should be deployed.

**Comment by ad1992** [comment]
The docker build is published 🚀

**Comment by jauderho** [comment]
I was eager to test this out and can confirm that the Docker image does build. But then I noticed that the build image `node:20` is not an Alpine base image.

node:20-alpine should probably be used as the build image instead

**Comment by agebhar1** [comment]
The builder images was not changed with this PR, it's still `node:18`.

**Comment by jauderho** [comment]
My point still stands that the build image ideally should be the same Linux OS as the final image. This just means that the issue has been around longer than the most recent changes.

**Comment by agebhar1** [comment]
It's almost an good idea to use the same image IMHO. The build result are only static files which are served by Nginx. Maybe I did not see the issue to serve these files from a different Linux OS.

**Pull request merged**
