### PR TITLE
wip: sloppy svg path

### PR DESCRIPTION
**Pull request by dai-shi**
While implementing #1931 , I wanted a way to draw shape with sloppiness and connected edges.
@vjeux seems to want something similar. So, I gave it a try.

I have been thinking about focusing on implementing only one shape "svgPath" and all other shapes can be converted to it, hopefully.

image

TODOs:
- [x] fix round edge connection now being sharp
- [ ] fix round/sharp lines resizing
- [ ] fix lines with points less than 4
- [ ] fix bound box of ellipses (for lines too)
- [x] random seed
- [ ] support filling
- [ ] support arrow head

### CODE REVIEW

**Comment by lipis** [comment]
On the ellipse.. you can always see the 3 points where the segments are.. should be smoother.

**Comment by dai-shi** [comment]
Yeah, still not optimal. Needs to solve curve + curve smooth connection.

image

**Comment by vjeux** [comment]
I think the issue is that there are too many control points and it feels really wobbly. Can you try with less, maybe 2?

**Comment by vjeux** [comment]
Btw, this is crazy how it takes so few lines of code to build that!

**Comment by lipis** [comment]
Let's mark it out of scope and leave that on hold for now.

**Pull request closed without merging**
