### PR TITLE
fix for #1106 - Weird behavior when resize + shift a 2-point line

### PR DESCRIPTION
**Pull request by jquintozamora**

### CODE REVIEW

**Comment by jquintozamora** [comment]
I've got an issue with Sentry task ... Do I have to add something else ?

**Comment by lipis** [comment]
No.. ignore the Sentry task.. it's all good.

**Comment by dwelle** [comment]
Hello @jquintozamora → AFAIK this only fixes the weird flicker/behavior, but doesn't revert to the previous behavior of rotating by discrete steps. Lemme find a commit to show you.

**Comment by dwelle** [comment]
This actually seems fixed in https://github.com/excalidraw/excalidraw/pull/1099

**Comment by dai-shi** [comment]
@dwelle No, it's not. The bug in #1106 seems to happen if you drag the other end of the arrow.

**Comment by dwelle** [comment]
@dai-shi didn't catch that. Mhm, but since the other handle is working correctly, you must have changed something (related). I'd maybe wait for your PR to land before further attempting to fix this.

**Comment by jquintozamora** [comment]
> @dai-shi didn't catch that. Mhm, but since the other handle is working correctly, you must have changed something (related). I'd maybe wait for your PR to land before further attempting to fix this.

I see the desired behaviour covers also scale from ne and sw. I could work on that as well meanwhile @dai-shi is finishing his PR and solve conflicts later.

**Comment by jquintozamora** [comment]
@lipis @dwelle please have a look, now looks like the issue is solved with the desired behavior. 
Thanks for the feedback!

**Comment by lipis** [comment]
Yes, feels very nice! But let's wait for @dwelle he is more aware of the issue :)

**Comment by dwelle** [comment]
LGTM. Thanks @jquintozamora! :rocket:

**Pull request merged**
