### PR TITLE
docs: add multiple selection docs

### PR DESCRIPTION
**Pull request by OrenMe**
added docs for the multiple selection option following my question in #1851 
I know it was asked not to add translations directly to the files, but I'm a bit lacking of how this can be done then for new features, so please let me know if I should remove them.
Also, the naming might be a bit unclear - I called it multiple selection, but it can also be named multiple discrete selection - gut it felt a bit too tedious and long.

I also saw that for other menu items that have multiple click actions, lie drawing a line, it was described as click, click, click - is this a convention? cause for multiple selection you also press shift and then click around, but again - it feels a bit too long to describe like this.

Open for your suggestions.

### CODE REVIEW

**Comment by dwelle** [comment]
> I know it was asked not to add translations directly to the files, but I'm a bit lacking of how this can be done then for new features, so please let me know if I should remove them.

Just add the `en.json` and remove the rest.

As for the label, maybe "Add element to selection"? Under "Select multiple elements" I imagine something like shift+drag, but maybe it's just me.

**Comment by OrenMe** [comment]
thanks @dwelle, removed unnecessary i18n changes.
I'm not sure I understood the other comment.

**Comment by dwelle** [comment]
I meant that I'd use `Add element to selection` for the label, but I don't have a strong opinion. /cc @lipis

**Comment by OrenMe** [comment]
@dwelle I like yours better :-) changed

**Comment by dwelle** [comment]
Cool, thanks for the PR!

**Pull request merged**
