### PR TITLE
feat: Support LaTeX and AsciiMath via MathJax on stem.excalidraw.com

### LINKED ISSUE #1176: Support for writing / rendering math equations
It would be nice to support math equations embedded in text. Imagine the cool diagrams you can draw with labels using this support to illustrate geometry and physics problems.

One way to implement this would be to integrate [LaTeX math mode](https://artofproblemsolving.com/wiki/index.php/LaTeX:Math#Math_Mode) in text. For example, `$d = \sqrt{x^2 + y^2}$` would show up as .

Potential challenges:
1. Can this be done in a lightweight manner?
2. How difficult would it be to support artistic rendering in this mode?

### LINKED ISSUE #3569: is there any feature for writing a formula
if i need to write a math formula, what can i do?

### LINKED ISSUE #3636: Subscript and Superscript Text
Raised by Fong Chun Chan for Obsidian Excalidraw with the following text:

Chemical formulas contain subscripts and right now there is no way to add a subscript.
An option to specify a subset of the text to be a subscript or superscript

https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/64

### LINKED ISSUE #5265: Add LaTeX support
I'm trying to use excalidraw to express mathematical models more easily.

It's very useful, but lacks in supporting math symbols.

### LINKED ISSUE #5424: Support plugins in Excalidraw
Let's discuss the development of `@excalidraw/plugins` here.  (I'm opening an issue since even force-pushes can generate some clutter for @excalidraw to wade through.)

Could we start by landing `ExcalidrawElement` subtype functionality into `@excalidraw/excalidraw`?  That's already done in #5349 and has no impact on the defaults.

Then we can figure out a plugins API (or whatever exactly would best allow optional inclusion of MathJax, UML, etc on https://excalidraw.com).

Once we nail down an initial plugins API, `@excalidraw/plugins` could ship with MathJax as an initial plugin demonstrating the API.

cc @dwelle @ad1992 @baptiste

### LINKED ISSUE #5765: [Feature Request] Add PageUp & PageDown scroll
Trying to use excalidraw as a whiteboard is amazing, but also something close to the slide experience can be achieved by enabling PgUp/PgDn keys to be used for a 100% viewable screen size scroll. This is related to #253 in a barebones way.

For those still looking for an alternative in the meantime, theres https://github.com/excalideck/excalideck (I particularly don't like the layout too much, but as it's also open source, there's always the possibility of customizing. It's also a bit outdated as of now)

### LINKED ISSUE #5789: Text gets misaligned when (and after) editing a sticky note
https://user-images.githubusercontent.com/14358394/197757783-01e59b3c-deef-4901-a493-4166a5fd844a.mp4

### LINKED ISSUE #5798: How to add custom share type?
Hello folks, 
Is there any guide on how to add custom shape type with its custom attributes? 

I need to allow users to draw rectangular shapes with multiple attributes, and the content will be rendered by my code.

Any guides or examples please.

### LINKED ISSUE #5865: Improve subscript and superscript characters in text
The text `2²₂` currently renders like this:
image
The superscript character is hard to read, and the subscript character doesn't match the font that everything else is in.

### PR DESCRIPTION
**Pull request by DanielJGeiger**
### **Overview of PR**
This PR is ready for review.  All features are effectively stable: MathJax support, `ExcalidrawElement` subtypes, custom actions/shortcuts, and the `@excalidraw/extensions` package.  More info about these may be found in the description of the rollup #5311 (identical to #2993 other than sometimes lagging behind).  Further commits to #2993 at this point are primarily maintenance: tracking `excalidraw:master`, ensuring test coverage, fixing occasional bugs.

### **MathJax support**
**Overview**
This PR renders math notation using the MathJax library.  By default, standard Latex input is used (simplified AsciiMath input is also supported).  Math rendering is activated by selecting the "Math" button in the shape chooser and typing math between delimiters.  AsciiMath input is included for situations where Latex's steep learning curve might be undesirable (such as first-year gen-ed math classes).

**Implementation**
This PR is implemented as an extension in the `@excalidraw/extensions` package and employs the `ExcalidrawElement` subtyping system of #3915.  The extension uses MathJax's SVG output instead of MathML because some major browsers (eg Chromium) misrender the latter.  Rendering the `ExcalidrawMathElement` contents to the canvas employs MathJax's provided layout.  Of course, math rendering generalizes WYSIWYG.  (The `ExcalidrawMathElement`'s width and height are set based upon the MathJax output.)

**Inputting math content**
The delimiters are the usual '\\(' and '\\)' for Latex, and backward tick marks ('\`') for AsciiMath.  Simplified input (ie AsciiMath) may be selected in the "Math" button's context menu.  The canvas context menu provides an option to reset the input mode of selected math elements to the choice from the "Math" button's context menu.

**Math-only mode**
By default, only text inside of math delimiters is rendered as math.  To render the entire `ExcalidrawMathElement` as math, select "Math only" from the "Math mode" property in the sidebar.  For simplified AsciiMath input, newlines are used in math-only mode.  For standard Latex input, newlines are ignored in math-only mode since Latex supports environments like `align` and `gather`.

**Miscellaneous details**
- Fixes #1176, fixes #3569, fixes #5265, fixes #3636, fixes #5865, fixes #5798, fixes #5424, fixes #5789, and fixes #5765.
- Tested in virtual and face-to-face classrooms.
- Uses extensive caching for optimization.
- Exports SVGs displayable in standalone viewers.
- Includes #5659 and #5511.

### CODE REVIEW

**Comment by lipis** [comment]
Could you provide a few example that we could use to test the rendering?

**Comment by dwelle** [comment]
Without giving my vote, I think if we were gonna accept this it must be implemented in a way that doesn't have a noticeable effect on the defaults. This means:

1. Don't attempt to render math if no math formula is present. I haven't dug into the code, but right now it seems you're rendering it all the time which affects rendering after confirming the text editor (there's a noticeable flicker).
2. Same for loading the Mathjax library: it should be lazy-loaded, either after math is detected, or at least after initial load.
3. I'm not sure about AsciiMath. I don't write Math these days, so I'm not sure what the difference is from Latex (which is what I used in college), but if impacts what you can express in it, or if the hurdle of learning its syntax (when you already know Latex math) is too big, I'd rather use Latex. After all, we wouldn't target just students (and I'd also not underestimate their ability). I asked for opinions in the related issue. Lastly, the AsciiMath `` ` ` `` delimiters will clash with `code` if we ever add support for inline code (but even if not, it's a known Markdown delimiter so it'll mess up with people's muscle memory). I like Latex delimiters: `$` and `$$`.

**Comment by baptiste** [comment]
I would favour LaTeX over AsciiMath; typing maths on a computer is always going to be a bit of a learning curve for someone who's never done it (how likely is it they will start in Excalidraw?) and LaTeX is a more transferable skill. 
Additionally, as mentioned any LaTeX users would find it quite unpleasant to have to constantly look up all the quirks that make Ascii notation arguably "more intuitive".
Maybe a simple switch somewhere in the UI could make everyone happy? (to avoid cluttering the interface, how about double-clicking the "A" (text) button to view/set this option?)

**Comment by DanielJGeiger** [comment]
@lipis Here are some examples:
```
Typing $$\frac{x+1}{2}$$ in Latex.

Typing `(x+1)/2` in AsciiMath.
```
and
```
Writing $$\{x_{11}, x_{12}, x_{13}\}$$ in Latex.
Writing `{x_11, x_12, x_13}` in AsciiMath.
```
Would you like some more?

@dwelle @baptiste I have made the changes you requested.  Could you check them out?

**Comment by baptiste** [comment]
It's awesome, thanks a lot for working on this.

I noted a few glitches,

- The size box seems a little off
Screen Shot 2021-02-14 at 5 26 15 PM
- trying to change the colour while in the view tex source mode makes the equation disappear; it seems to reappear sometime later when performing other actions on the canvas
- switching between asciim/tex modes seems to confuse a bit the bounding box – equations get rendered, but with the bounding box of the source code

Screen Shot 2021-02-14 at 5 35 06 PM
Screen Shot 2021-02-14 at 5 35 00 PM

**Comment by DanielJGeiger** [comment]
@baptiste I pushed a fix for the third item you mentioned.  I could not reproduce the first two items either in Firefox or in Chromium.  What browser were you using?

**Comment by baptiste** [comment]
> @baptiste I pushed a fix for the third item you mentioned. I could not reproduce the first two items either in Firefox or in Chromium. What browser were you using?

@DanielJGeiger I'm using Firefox 85.0.2

**Comment by DanielJGeiger** [comment]
@lipis @dwelle @baptiste This may be ready for merging.

@excalidraw Could someone look this over? Would you want any tests for this?

**Comment by baptiste** [comment]
> @lipis @dwelle @baptiste This may be ready for merging.

I'm just a tourist here, but FWIW I think it's a very useful addition to Excalidraw, and I hope it gets merged (I'll probably pitch Excalidraw to my Physics class next trimester, if they can write maths and doodle about the course collaboratively).

For some reason the bounding box still seems off for me (Firefox 86.0 (64-bit) on a Mac)?

Screen Shot 2021-03-09 at 5 36 20 PM

**Comment by pschyrem** [comment]
I'm not sure whether this belongs here ...

- is Ascii-math-mode supposed to work (eg. with the given example above)? It doesn't work for me (Win 10: FF 86.0, Edge Version 89.0.774.48, iOS Safari 14.0.3)
- exporting as *.png scaled by 2x or 3x results in unsharp formulas.

Awesome feature extension btw! Really looking forward for it.

**Comment by DanielJGeiger** [comment]
@baptiste Do you still get bounding box issues with commit d1ec8a5 or later?

> For some reason the bounding box still seems off for me (Firefox 86.0 (64-bit) on a Mac)?
> 
> Screen Shot 2021-03-09 at 5 36 20 PM

**Comment by DanielJGeiger** [comment]
> * is Ascii-math-mode supposed to work (eg. with the given example above)? It doesn't work for me (Win 10: FF 86.0, Edge Version 89.0.774.48, iOS Safari 14.0.3)
> 
> * exporting as *.png scaled by 2x or 3x results in unsharp formulas.

@pschyrem I pushed a fix for your second comment.  For your first comment, does the following from the changelog entry address your question?

_The delimiters are double dollar signs ('$$') for Latex and grave accents ('`') for AsciiMath. Press "Control Shift 8" to toggle between Latex and AsciiMath. This toggles the input mode for each selected text element which could be in math mode. With only one text element selected, this also sets the default input mode for new text elements. Press "Shift 8" to check which input mode the selected text element uses, or the default input mode if no text element is selected._

**Comment by baptiste** [comment]
> @baptiste Do you still get bounding box issues with commit [d1ec8a5](https://github.com/excalidraw/excalidraw/commit/d1ec8a55223b801f899c00fe4787c66a0c1f734a) or later?
> 
> > For some reason the bounding box still seems off for me (Firefox 86.0 (64-bit) on a Mac)?
> > Screen Shot 2021-03-09 at 5 36 20 PM

I believe so (using the latest Preview from the vercel bot). I wonder if I can share the link to that:
https://excalidraw-5i62ipzv5-excalidraw.vercel.app/#json=5259979061723136,DvUOIm3OUkY8rWNpEjEg6w

**Comment by pschyrem** [comment]
> @pschyrem I pushed a fix for your second comment. For your first comment, does the following from the changelog entry address your question?

Ah, I missed that part - unfortunaly it's not working for me (Edge & FF). Neither do I get informed (Shift + 8) - how's that supposed to happen? - nor can I switch the modes (ctrl+shift+8).

I'll see, if I get this ReactDebugger in FF working...

**Comment by DanielJGeiger** [comment]
@baptiste Are you using a high-density screen? Does commit 1306658 fix the bounding box issues you are seeing?

**Comment by DanielJGeiger** [comment]
@pschyrem Are you using the "normal" font? The browser should display an alert box when you press "Shift 8".

**Comment by pschyrem** [comment]
> 
> 
> @pschyrem Are you using the "normal" font? The browser should display an alert box when you press "Shift 8".

Yep. LaTex is rendering fine. Nothing is happening, when I hit Shift 8, though.

**Comment by baptiste** [comment]
> @baptiste Are you using a high-density screen? Does commit [1306658](https://github.com/excalidraw/excalidraw/commit/1306658e0d249ea1d05a0e2c3c54f40aa9bceeb7) fix the bounding box issues you are seeing?

Possibly (in the sense that Macs tend to have high density). This last version seems to have done the trick – the bounding box looks good now :) 

Awesome job, thanks so much.

Minor detail, maybe LaTeX should require two pairs of `$$` (both opening and closing), to be consistent with TeX conventions. Currently I only need to start the expression with `$$`.

It might be nice to load the `ams` extension by default in TeX mode, as I think most users would expect/want it to be available (for things like `\begin{aligned}` etc.)

**Comment by baptiste** [comment]
Oh, and another minor nitpicking – if I rotate an equation, and double-click to edit, the text source is somehow shifted (but reverts to the right position after edit)

Screen Shot 2021-03-14 at 4 59 50 PM
Screen Shot 2021-03-14 at 4 59 44 PM

**Comment by dwelle** [comment]
Hey @DanielJGeiger — we've been pretty busy so we haven't been keeping an eye on this PR. This will require a thorough review and we can't guarantee we'll merge this. Initially it seemed like this PR's logic could be encapsulated and separated, but I haven't realized how much involved this would turn out.

The main factors contributing to the decision of whether to merge this or not are 1) how it affects users (that means both the users of excalidraw.com and consumers of the npm package — in terms of UX, UI, performance, size...) 2) how it affects the codebase (complexity, design changes...).

I've taken just a quick glance, but I'm not super happy with the following:

- There's been an increase to the general bundle size — unclear what contributes to it and which chunks are affected, but all files considered (source JS files), this PR adds ~1.6MB in total if I'm reading it correctly (2.6MB vs 1MB folder size of `build/static/js`). This is not just a big deal in terms of how many more bytes excalidraw.com users will need pull in, but it will also affect the npm consumers when integrating Excalidraw into other apps.

	This is why I advised to lazy-load as much as possible. But seeing how coupled the PR is to the whole codebase, this will be hard.

- Speaking of which, some of the changes are pretty major, such as changing the rendering from sync to async. This is huge and we'd need to thoroughly investigate the impact this will have (both the impact it has now, and going forward).

Haven't had time to review in more detail.

Ideally, this PR would be a plugin, if we already had a plugin system. Barring that, we'd need to figure out how we can isolate the logic and make it not have such an impact as it does now.

---

That was just for the technical part. We'd also need to discuss the UI/UX, but I'd leave that discussion for later.

**Comment by DanielJGeiger** [comment]
@dwelle Thank you for your comments.  You raise some good points.

- On the bundle size, my hunch is this can be readily addressed by lazy-loading MathJax from a CDN instead of lazy-loading it from within Excalidraw.

- On the coupling issue, I could create something like an `ExcalidrawMathElement` to inherit from `ExcalidrawTextElement`.

- Let me revisit whether the async rendering is really still necessary, since I got rid of using `<foreignObject>` SVG tags.

- I could help with isolating the logic on this PR.

**Comment by dwelle** [comment]
> On the bundle size, my hunch is this can be readily addressed by lazy-loading MathJax from a CDN instead of lazy-loading it from within Excalidraw.

Simple lazy-loading should do. We generally don't want to import resources from 3rd-party servers — the Excalidraw component should be self-composed. Though I'd be interested where is the additional ~1.3MB coming from (since the lib's ES5 minified code is only [~260KB](https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.1.2/es5/input/tex-full.min.js)) when we bundle the mathjax locally (but again, maybe my measurement wasn't correct).

Anyway, before you start the refactor in earnest, you should get an idea whether the 1) decoupling 2) lazy-loading, and 3) sync-rendering is at all feasible, or what it'd require from our side to change to make it feasible. This PR could potentially serve as a proto-plugin or a proto-scaffolding for the future plugin system.

Btw, even if the decision is not to merge, it would be beneficial if the code was decoupled as much as possible to allow for easy maintenance of a fork if you went that route.

**Comment by DanielJGeiger** [comment]
@excalidraw I have updated this pull request in response to the technical points @dwelle raised.

* Sync rendering: Done.

* Lazy-loading: Done.  As for the extra payload weight, I think [output/svg/fonts/tex.js](https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/output/svg/fonts/tex.js) contributes the most.

* Decoupling: Since 412fb59, the MathJax additions are decoupled from the rest of Excalidraw.  (The few loose ends could be resolved by adjusting the math-mode UX).  I created kind of a plugin system just for `ExcalidrawTextElement` and derived types.  This approach allows easily adding other specializations of `ExcalidrawTextElement`; e.g. @dwelle mentioned supporting `code`.  Note the text metrics when rendered and when editing might differ now.

@lipis @dwelle @excalidraw Might I create a separate pull request with the changes for subtyping `ExcalidrawTextElement`?  Then we could simply iron out the particulars of math-mode here.  This pull request currently touches many files.  But most changes are small and would go in the pull request for subtyping `ExcalidrawTextElement`.

**Comment by dwelle** [comment]
Hello!

I haven't been keeping close tabs on this PR in terms of code changes, and haven't yet had the time to review it. But I've at least checked the preview.

Just so that we keep the two most important considerations in mind, they are:

1. Impact on user experience, especially in terms of performance, and especially when the user isn't using any math in the drawing.
2. Impact on the codebase (complexity).

Since I only checked the preview, I can only comment on (1), and I've noticed a significant performance degradation when rendering moderate amount of text elements.

There seems to be a problem when importing elements from file/clipboard, as the text is invisible and nothing that I do which forces rerender/recalculation seems to work so I cannot supply a repro, but it's fairly easy. Create 350+ text elements (not containing math), and refresh the browser.

What I'm seeing on Chromium browsers is this:

(note also the two render passes: unclear if it's present in production and we're just not seeing it because it's fast)

excal_math_perf

In Safari, it takes comparable amount of time, but it blocks the thread completely until everything is rendered. In Firefox, it's similar to Chromium behavior, but the perf is 5-10x worse.

Now, I'm not sure whether this is still in-progress and you are aware of this and have concrete plans to fix this, or this is just a fact of the MathJax library, but this is a major regression. At worst, I'd at least want to contain this to text elements that have math so that rendering regular text retains production level of perf profile.

**Comment by DanielJGeiger** [comment]
@dwelle Could you check the preview again?  Commits 937e8bb and 8c3efc3 should solve the invisible text and performance degradation issues, respectively.

**Comment by DanielJGeiger** [comment]
@dwelle @excalidraw The plugin-like subtyping system for `ExcalidrawTextElement` is ready for review.  The MathJax-specific aspects are nearly ready for review, though still wip.  That is why I asked about creating a separate pull request with the `ExcalidrawTextElement` subtyping.

**Comment by lipis** [comment]
I authorized the deployment, should be testable now.

**Comment by y9san9** [comment]
I am using excalidraw with obsidian.md and for me this PR is game changer, so really waiting for this

**Comment by baptiste** [comment]
This is really great! One thing that I find could be improved is the handling of errors; currently when I type an incorrect LaTeX equation, especially a long one, I find it very hard to know what's going on because once I leave the TeX source the object seemingly just disappears from screen. Displaying a placeholder to indicate that there was an error in processing the TeX would be quite helpful, I think?

**Comment by mcaruel** [comment]
Hi everyone, This PR is a game changer, indeed. Having equation in a tool like this would massively attract scientists such as myself. The collaborative aspect would also contribute.  Quickly doing drawings with nice formula inside is quite time consuming. Usually people resolve to using PPT or Keynote and separate programs like LaTeXiT to render the equations and embed them as pictures. I tested the version of the code available here and for me it is very good already. People won't care too much about the handwritten font. What is great is that you can directly have the equation with the right font size and the right colors, matching those already there in the drawing. You already did a good job. I do hope this PR will be fully integrated.

**Comment by DanielJGeiger** [comment]
Hello @mcaruel @y9san9 @pschyrem @baptiste, the main thing blocking inclusion of this pull request is for @excalidraw to review and merge the plugin system in #3915 (which is of broader interest than MathJax support).  Once @excalidraw accepts #3915, this MathJax plugin pull request (which by necessity includes #3915) will only change three files outside `src/textlike`.

**Comment by mcaruel** [comment]
Thanks @DanielJGeiger for the update. There's no hurry. The development version works well !

**Comment by baptiste** [comment]
Thanks so much @DanielJGeiger – this is really brilliant work, and much appreciated! It'll be a game-changer in STEM courses taught remotely.

I'm just a tourist here, but I see a few reasons to push this beyond the current status of pull request: i) visibility; ii) reward (encouragement) for the hard work; iii) longevity: what happens to a PR when the proposer has moved on, or is no longer in a capacity to merge upstream changes? 

I wonder if there could be a "library" of experimental "beta" Excalidraw features such as this one, where PR's such as this one would be made more visibly available and tentatively supported (testing and gauging the community's reaction, in a way).

**Comment by DanielJGeiger** [comment]
@baptiste Thank you for the feedback.  I have marked this PR "ready for review".  There are ways I could optimize things, and some enhancements I could add.  However, for all practical purposes this PR really is as ready for review as the underlying #3915 included in this PR.

@baptiste I added the "ams" LaTeX package you requested previously.  @mcaruel In the same commit, I added optional support for the "mhchem" and "physics" LaTeX packages.  How much might scientists like you want to have those packages activated?  I did not turn those on by default because of @dwelle's comments about payload size.

@baptiste You raise good points about merging upstream changes.  Once @excalidraw merges the plugin system of #3915, this MathJax PR will be trivial to maintain (if @excalidraw wants to hold it awhile in your proposed "beta library" before merging).  Compared to #3915, this PR only touches 10 files: `package.json` and `yarn.lock` (to include MathJax), `CHANGELOG.md`, and 7 files inside `src/textlike`.

**Comment by mcaruel** [comment]
@DanielJGeiger Good Job ! The question about the package is difficult to solve as there are so many use case. For sure mhchem and physics will please most users. I think it's better to wait for user requests to decide wether or not additional package should be included. After all I don't think academics like me would use excalidraw to write very complex equations. I'm already very happy with what is there (I work in Physics). Users with very specific need can always resolve to embed a picture of the equation that would be generated by more specialised programs(using LaTeXit on Mac for instance).

**Comment by baptiste** [comment]
It seems linebreaks break the rendering; it makes it a bit tricky to type (or edit) long formulas, and especially those involving `aligned` environments where one's usually typing different lines with linebreaks. Is this a hard technical constraint, or could it be worked around?

**Comment by hengsok** [comment]
@DanielJGeiger when can we have this feature in the release?

**Comment by DanielJGeiger** [comment]
> @DanielJGeiger when can we have this feature in the release? It looks really awesome!

@hengsok Before this MathJax plugin can land, the plugin system #3915 needs to get merged first.  The review of #3915 by @ad1992 and @dwelle from @excalidraw remains underway.

**Comment by ChasingZenith** [comment]
Hello, when I open the svg with Inkscape. I find that even when I open the same file, formulas does not show up sometimes and sometimes actually work. Is there a way to make the behavior consistent? And all give a very large selection block in Inkscape.

The formula doesn't show up this time
image
I reopened the same svg and the formula shows up and the svg is displayed correctly.
image
The formula give a very big selection box.
image

**Comment by DanielJGeiger** [comment]
@ChasingZenith Commit ac4f685 should fix the large selection blocks in Inkscape.

Making Inkscape render formulas may be a separate matter.  MathJax specifies the formulas' dimensions in `ex` units.  I can get formulas to render in Inkscape by manually setting the dimensions to use units other than `ex` or `em`.

But MathJax really does need to use `ex` units: per [W3](https://www.w3.org/Style/Examples/007/units.en.html), the value of one `ex` equals the height of a font's lowercase letters.  Even in metrically equivalent fonts (eg Arial/Arimo/Liberation Sans) this value can vary from one font to another.

I think the best solution would be to configure Inkscape to handle `ex` units.  But as a workaround, you could convert the values of `width`, `height`, and `vertical-align`: multiply each by the value of one `ex` and drop the `ex` units.  The following code shows a way to find the value of one `ex` when the font size is `20px`:

```
const context = document.createElement("canvas").getContext("2d");
context.font = "20px Helvetica";
const exSize = context.measureText("x").actualBoundingBoxAscent;
```

Just be sure your browser and Inkscape are choosing the same font for "Helvetica".

**Comment by nileblack** [comment]
> **excalidraw-package-example**
mixed text not work.
image

**Comment by DanielJGeiger** [comment]
@nileblack It looks like you were using the examples I posted in an early [comment](https://github.com/excalidraw/excalidraw/pull/2993#issuecomment-778717459).  Since then, I updated LaTeX to use the more standard delimiters `\(` and `\)`.  I have updated the examples accordingly now.

Recently, I also tweaked the selection of LaTeX vs AsciiMath.  Now the `Math` toggle button provides these in a context menu.  I made the change based upon my experience using this PR in my classrooms.

> > **excalidraw-package-example**
> > mixed text not work.
> > image

**Comment by nileblack** [comment]
> @nileblack It looks like you were using the examples I posted in an early [comment](https://github.com/excalidraw/excalidraw/pull/2993#issuecomment-778717459). Since then, I updated LaTeX to use the more standard delimiters `\(` and `\)`. I have updated the examples accordingly now.
> 
> Recently, I also tweaked the selection of LaTeX vs AsciiMath. Now the `Math` toggle button provides these in a context menu. I made the change based upon my experience using this PR in my classrooms.

is it means "standard input" and "simplefiled input"? 
context menu is not "KEEP SIMPLE". excalidraw is a simple enough draw tools.

Maybe you can move the choice to left option panel? just my opinion.

**Comment by jcezarms** [comment]
@DanielJGeiger I may be wrongly reviewing this PR's diff, but is `speech-rule-engine@4.0.7` required for this scope? If included for screen reader accessibility, it could be put in a separate PR, post-MathJax inclusion, due exclusively to [its bundle size](https://bundlephobia.com/package/speech-rule-engine@4.0.7) being bigger than [MathJax's](https://bundlephobia.com/package/mathjax-full@3.2.2) for the versions chosen here. This could alleviate the perceived bundle size increase @dwelle has mentioned before.

**Comment by jcezarms** [comment]
@dwelle as far as I can see, the many requirements noted here against merging this have been accomplished. If I've read the thread correctly, this PR hasn't been thoroughly reviewed yet. Is it possible to carry onto that now?

**Comment by DanielJGeiger** [comment]
> @DanielJGeiger, I heart this feature! +1 But I found a bug: when I type `\vec a_\text{f}`, all works fine, but when I type some nonlatin inside `\text`, I have an error. For example: `\vec a_\text{абс}` doesn't work for me. There are nothing in devtools console, so I have no additional information about this bug.

@sindzicat Thanks for the report.  I located which code call leads to MathJax throwing an error.  I suspect needing to change subtly how the MathJax components lazy-load in `loadMathJax()`.

**Comment by DanielJGeiger** [comment]
@sindzicat I believe I fixed the bug you pointed out.

**Comment by sindzicat** [comment]
@DanielJGeiger, yes, it now work! 👍 Many thanks!
Unfortunatelly, there is a small thing: there are relatively big spaces between symbols:
image
```$\vec a_\text{rod}$```
```$\vec a_\text{абс}$```
Is it possible to remove these spaces between symbols, please?

**Comment by DanielJGeiger** [comment]
@sindzicat I believe the spacing issue you reported will resolve after another subtle adjustment to `loadMathJax()`.

**Comment by sindzicat** [comment]
@DanielJGeiger, sorry, but symbols spacing are still large. I compared how equation `$$\vec F_text{абс}$$` is rendered on Excalidraw and Mathjax sites ( [https://mathjax.org#demo](https://www.mathjax.org/#demo) ).

image

image

**Comment by DanielJGeiger** [comment]
Closing in favor of #6037 with preview access at https://math.preview.excalidraw.com/.

**Comment by diego898** [comment]
> @DanielJGeiger, yes, it now work! 👍 Many thanks!
> Unfortunatelly, there is a small thing: there are relatively big spaces between symbols:
> image
> `$\vec a_\text{rod}$`
> `$\vec a_\text{абс}$`
> Is it possible to remove these spaces between symbols, please?

Sorry @DanielJGeiger  - is it possible to use `$` instead of `\|` like in the above example? Or will excalidraw only support `\(` for latex?

**Pull request closed without merging**
