### PR TITLE
fix resizing lines with abs coords bigger than element w/h

### LINKED ISSUE #1275: Resizing curved lines from W/N doesn't fix E/S
We would probably need to fix this before continuing #1218.
This behavior existed before we added rotation support.

exdraw19

### PR DESCRIPTION
**Pull request by dai-shi**
Trying to fix #1275 as one of tasks in #1298.

- [x] from n/w (x2,y2 exceeds x+w/y+h) without rotation
- [x] from s/e (x1,y1 precedes x/y) without rotation
- [x] with rotation
- [x] fix positions with flipping without rotation
- [x] fix positions with flipping with rotation
- [x] refactor code

### CODE REVIEW

**Comment by dai-shi** [comment]
This works.

exdraw26

**Comment by dai-shi** [comment]
But, this is weird.

exdraw27

**Comment by dai-shi** [comment]
This is bad. So, the issue was not about the direction from n/w, but the shape.

exdraw28

**Comment by dai-shi** [comment]
Overall, this is worse than before...

**Comment by dai-shi** [comment]
Without rotation, it works.

exdraw29

**Comment by dai-shi** [comment]
@jquintozamora You might be interested in some of work in this PR. I found a bug and a new requirement in `adjustXYWithRotation`. Currently, it doesn't work as expected though. Also, `resizeXYWidthHightWithRotation` had another bug (we need to use `x2-x1` instead of `width`.)

**Comment by dai-shi** [comment]
Finally fixed!!!

exdraw34

**Comment by dwelle** [comment]
Good job.

One thing I noticed: negative resizing tends to reposition x1/y1 when going to negative & back to positive:

excal_arrow_neg_resize_repositioning

**Comment by dai-shi** [comment]
Thanks. Good catch.
I'll try to find at least mitigate that issue. (#1475 wasn't enough... 😓 )

**Comment by dai-shi** [comment]
I fixed the flip positioning with no rotation involved. (I know you say this is suboptimal which would be tackled in #1506.)

Now, this makes positioning worse with rotation. I think I need to normalize negative width _before_ calculating rotation,

exdraw35

**Comment by dai-shi** [comment]
I finally made something I'm happy with.

@dwelle If you are OK with this behavior, I will continue refactoring the code.

exdraw36

**Comment by dwelle** [comment]
I'm sorry for the delay. Your 2 previous comments you made didn't notify me at all, which is weird.

Works great!

**Comment by dai-shi** [comment]
Cool. I will be refactoring some code for more readability before merging.

**Comment by dai-shi** [comment]
@dwelle This is ready for final review and merge.

**Comment by dwelle** [comment]
LGTM. Thanks for the work you're continuing to do on this front!

**Pull request merged**
