### PR TITLE
Wysiwyg text 2.0

### PR DESCRIPTION
**Pull request by nanot1m**
For issues investigation #200

### CODE REVIEW

**Comment by dwelle** [comment]
Works well (https://codesandbox.io/s/github/nanot1m/excalibur/tree/text-wysiwyg). :+1: 

Is it going to be hard to make the text editable by double-click (currently double click on an existing text element creates a new text), or leave that for another PR?

**Comment by Fausto95** [comment]
@nanot1m while you're here, do you think it's worth editing the text on double click?

**Comment by nanot1m** [comment]
I can make it in this PR :)

**Comment by nanot1m** [comment]
It should work
image

**Comment by Fausto95** [comment]
Also I think that we should listen to <kbd>Shift+Enter</kbd> to go support multiline
What do you think @nanot1m

**Comment by vjeux** [comment]
Okay, I can't reproduce the issue anymore. This is awesome!

**Comment by vjeux** [comment]
I'm not committed to centering the text vertically by reading the vertical ascent. If that's causing issue, feel free to let go of it!

**Comment by nanot1m** [comment]
@Fausto95, I was trying to implement it. But there was some problems:
1. multiline text is always rendered as single line by `context.fillText` if maxWidth is not specified as a 4th argument.
2. it is a little bit complicated to position textarea at right place

**Pull request merged**
