### PR TITLE
refactor: Converting span to kbd tag

### PR DESCRIPTION
**Pull request by Rafi993**
## What type of PR is this?

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## What does it do?

1. kbd tag is used to keyboard shortcuts
2. converting span to kbd tag to be more semtantic

## Related issue

NA

## QA Instructions, Screenshots, Recordings

1. checkout the branch
2. view keyboard shortcut modal it should use kbd tag instead of span nothing else should have changed
 
### UI accessibility concerns?
* With the way keybard shortcut is now rendered it uses single tag for rendering a combination. For example **ctrl + c** gets rendered inside a single tag it would be better if **ctrl** and **c** gets rendered as a separate tag
* This is more of a preference than an actual accessibility concerns

## Tests?

- [ ] yes
- [ ] no, reason?   
- [x] I need help with writing tests   
There were no existing snapshot covering this I was not sure if I should add one

### CODE REVIEW

**Comment by dwelle** [comment]
I'm fine with `<kbd>`, but right now it changes our styling, so we'd have to reset:

image

After:

image

You can add a `font-family: inherit;` to the `.ShorcutsDialog-key` class.

**Comment by dwelle** [comment]
As for:

> With the way keybard shortcut is now rendered it uses single tag for rendering a combination. For example ctrl + c gets rendered inside a single tag it would be better if ctrl and c gets rendered as a separate tag

IMO it would make it look like alternative shortcuts instead:

image

**Comment by lipis** [comment]
If we changing it here.. we should change in the context menu too..

**Comment by Rafi993** [comment]
font

I have added ```font-family: inherit``` this is how it looks now.

**Comment by Rafi993** [comment]
> If we changing it here.. we should change in the context menu too..

I have converted div in context menu to kbd key too now

context_menu

**Review by lipis — APPROVED** [review]

**Comment by Rafi993** [comment]
Thank you @lipis

**Pull request merged**
