### PR TITLE
ci: Update the coverage report for i18n PRs

### PR DESCRIPTION
**Pull request by lipis**
## Languages check

Our translations for every languages should be at least **85%** to appear on Excalidraw. Join our project in [Crowdin](https://crowdin.com/project/excalidraw) and help us translate it in your language. **Can't find your own?** Open an [issue](https://github.com/excalidraw/excalidraw/issues/new) and we'll add it to the list.

| | Flag | Locale | % |
| --: | :--: | -- | --: |
| **1** | 🇫🇮 | [**Suomi**](https://crowdin.com/translate/excalidraw/10/en-fi) | **100** |
| **2** | 🇫🇷 | [**Français**](https://crowdin.com/translate/excalidraw/10/en-fr) | **100** |
| **3** | 🇮🇹 | [**Italiano**](https://crowdin.com/translate/excalidraw/10/en-it) | **100** |
| **4** | 🇳🇴 | [**Norsk bokmål**](https://crowdin.com/translate/excalidraw/10/en-nb) | **100** |
| **5** | 🇷🇴 | [**Română**](https://crowdin.com/translate/excalidraw/10/en-ro) | **100** |
| **6** | 🇸🇰 | [**Slovenčina**](https://crowdin.com/translate/excalidraw/10/en-sk) | **100** |
| **7** | 🇸🇪 | [**Svenska**](https://crowdin.com/translate/excalidraw/10/en-sv) | **100** |
| **8** | 🇩🇪 | [**Deutsch**](https://crowdin.com/translate/excalidraw/10/en-de) | **99** |
| **9** | 🇮🇩 | [**Bahasa Indonesia**](https://crowdin.com/translate/excalidraw/10/en-id) | **99** |
| **10** | 🇹🇼 | [**繁體中文**](https://crowdin.com/translate/excalidraw/10/en-zhtw) | **99** |
| **11** | 🇺🇦 | [**Українська**](https://crowdin.com/translate/excalidraw/10/en-uk) | **98** |
| **12** | 🇲🇲 | [**Burmese**](https://crowdin.com/translate/excalidraw/10/en-my) | **96** |
| **13** | 🇬🇷 | [**Ελληνικά**](https://crowdin.com/translate/excalidraw/10/en-el) | **95** |
| **14** | 🇨🇳 | [**简体中文**](https://crowdin.com/translate/excalidraw/10/en-zhcn) | **95** |
| **15** | 🇸🇦 | [**العربية**](https://crowdin.com/translate/excalidraw/10/en-ar) | **89** |
| **16** | 🇮🇷 | [**فارسی**](https://crowdin.com/translate/excalidraw/10/en-fa) | **89** |
| **17** | 🇯🇵 | [**日本語**](https://crowdin.com/translate/excalidraw/10/en-ja) | **89** |
| 18 | 🇵🇹 | [Português](https://crowdin.com/translate/excalidraw/10/en-pt) | 83 |
| 19 | 🇮🇳 | [हिन्दी](https://crowdin.com/translate/excalidraw/10/en-hi) | 82 |
| 20 | 🇪🇸 | [Catalan](https://crowdin.com/translate/excalidraw/10/en-ca) | 81 |
| 21 | 🇪🇸 | [Español](https://crowdin.com/translate/excalidraw/10/en-es) | 81 |
| 22 | 🇷🇺 | [Русский](https://crowdin.com/translate/excalidraw/10/en-ru) | 81 |
| 23 | 🇹🇷 | [Türkçe](https://crowdin.com/translate/excalidraw/10/en-tr) | 81 |
| 24 | 🇳🇱 | [Nederlands](https://crowdin.com/translate/excalidraw/10/en-nl) | 80 |
| 25 | 🇳🇴 | [Norsk nynorsk](https://crowdin.com/translate/excalidraw/10/en-nnno) | 80 |
| 26 | 🇵🇱 | [Polski](https://crowdin.com/translate/excalidraw/10/en-pl) | 79 |
| 27 | 🇮🇱 | [עברית](https://crowdin.com/translate/excalidraw/10/en-he) | 69 |
| 28 | 🇰🇷 | [한국어](https://crowdin.com/translate/excalidraw/10/en-ko) | 68 |
| 29 | 🇧🇬 | [Български](https://crowdin.com/translate/excalidraw/10/en-bg) | 61 |
| 30 | 🇭🇺 | [Magyar](https://crowdin.com/translate/excalidraw/10/en-hu) | 44 |

\* Languages in **bold** are going to appear on production.

### CODE REVIEW

**Comment by kbariotis** [comment]
## Languages check\nOur translations for every languages should be at least **85%** to appear on Excalidraw. Help us translate them in [Crowdin](https://crowdin.com/project/excalidraw).\n### Languages over the threshold\n|Locale|%|\n|----|----|\n|ar-SA|89| |bg-BG|61| |ca-ES|81| |de-DE|99| |el-GR|93| |en|100| |es-ES|81| |fa-IR|89| |fi-FI|100| |fr-FR|100| |he-IL|69| |hi-IN|82| |hu-HU|44| |id-ID|99| |it-IT|100| |ja-JP|89| |ko-KR|68| |my-MM|96| |nb-NO|100| |nl-NL|80| |nn-NO|80| |pl-PL|79| |pt-PT|83| |ro-RO|100| |ru-RU|77| |sk-SK|100| |sv-SE|100| |tr-TR|81| |uk-UA|98| |zh-CN|95| |zh-TW|99|

**Comment by kbariotis** [comment]
## Languages check\nOur translations for every languages should be at least **85%** to appear on Excalidraw. Help us translate them in [Crowdin](https://crowdin.com/project/excalidraw).\n### Languages over the threshold\n|Locale|%|\n|----|----|\n|ar-SA|89|
|bg-BG|61|
|ca-ES|81|
|de-DE|99|
|el-GR|93|
|en|100|
|es-ES|81|
|fa-IR|89|
|fi-FI|100|
|fr-FR|100|
|he-IL|69|
|hi-IN|82|
|hu-HU|44|
|id-ID|99|
|it-IT|100|
|ja-JP|89|
|ko-KR|68|
|my-MM|96|
|nb-NO|100|
|nl-NL|80|
|nn-NO|80|
|pl-PL|79|
|pt-PT|83|
|ro-RO|100|
|ru-RU|77|
|sk-SK|100|
|sv-SE|100|
|tr-TR|81|
|uk-UA|98|
|zh-CN|95|
|zh-TW|99|

**Comment by kbariotis** [comment]
## Languages check\nOur translations for every languages should be at least **85%** to appear on Excalidraw. Help us translate them in [Crowdin](https://crowdin.com/project/excalidraw).\n### Languages over the threshold\n|Locale|%|\n|----|----|\n|ar-SA|89|
|bg-BG|61|
|ca-ES|81|
|de-DE|99|
|el-GR|93|
|en|100|
|es-ES|81|
|fa-IR|89|
|fi-FI|100|
|fr-FR|100|
|he-IL|69|
|hi-IN|82|
|hu-HU|44|
|id-ID|99|
|it-IT|100|
|ja-JP|89|
|ko-KR|68|
|my-MM|96|
|nb-NO|100|
|nl-NL|80|
|nn-NO|80|
|pl-PL|79|
|pt-PT|83|
|ro-RO|100|
|ru-RU|77|
|sk-SK|100|
|sv-SE|100|
|tr-TR|81|
|uk-UA|98|
|zh-CN|95|
|zh-TW|99|

**Comment by kbariotis** [comment]
## Languages check\r\nOur translations for every languages should be at least **85%** to appear on Excalidraw. Help us translate them in [Crowdin](https://crowdin.com/project/excalidraw).\r\n### Languages over the threshold\r\n|Locale|%|\r\n|----|----|\r\n|ar-SA|89|
|bg-BG|61|
|ca-ES|81|
|de-DE|99|
|el-GR|93|
|en|100|
|es-ES|81|
|fa-IR|89|
|fi-FI|100|
|fr-FR|100|
|he-IL|69|
|hi-IN|82|
|hu-HU|44|
|id-ID|99|
|it-IT|100|
|ja-JP|89|
|ko-KR|68|
|my-MM|96|
|nb-NO|100|
|nl-NL|80|
|nn-NO|80|
|pl-PL|79|
|pt-PT|83|
|ro-RO|100|
|ru-RU|77|
|sk-SK|100|
|sv-SE|100|
|tr-TR|81|
|uk-UA|98|
|zh-CN|95|
|zh-TW|99|

**Comment by kbariotis** [comment]
## Languages check
Our translations for every languages should be at least **85%** to appear on Excalidraw. Help us translate them in [Crowdin](https://crowdin.com/project/excalidraw).
### Languages over the threshold
|Locale|%|
|----|----|
|ar-SA|89|
|de-DE|99|
|el-GR|93|
|en|100|
|fa-IR|89|
|fi-FI|100|
|fr-FR|100|
|id-ID|99|
|it-IT|100|
|ja-JP|89|
|my-MM|96|
|nb-NO|100|
|ro-RO|100|
|sk-SK|100|
|sv-SE|100|
|uk-UA|98|
|zh-CN|95|
|zh-TW|99|
### Languages below the threshold
|Locale|%|
|----|----|
|bg-BG|61|
|ca-ES|81|
|es-ES|81|
|he-IL|69|
|hi-IN|82|
|hu-HU|44|
|ko-KR|68|
|nl-NL|80|
|nn-NO|80|
|pl-PL|79|
|pt-PT|83|
|ru-RU|77|
|tr-TR|81|

**Comment by dwelle** [comment]
> Our translations for every languages should be at least 85% to appear on Excalidraw. Join our project in Crowdin and help us translate it in your language. Can't find your own? Open an issue and we'll add it to the list.

↓

> Each language must be at least 85% translated in order to appear on Excalidraw. Join us on Crowdin and help us translate your own language. Can't find yours yet? Open an issue and we'll add it to the list.

**Pull request merged**
