### PR TITLE
Fix status when do `selectAll` while editing lines

### PR DESCRIPTION
**Pull request by lusingander**
When execute `selectAll` while editing lines, objects are selected without changing display.

200628_before

I think that it need to be undone the status of the editing line.

200628_after

### CODE REVIEW

**Comment by dwelle** [comment]
This is pretty much identical to https://github.com/excalidraw/excalidraw/issues/1742 and your fix is more of a hack, going half-way.

**Comment by lusingander** [comment]
I see, so it would be better to close this PR. Thanks for checking and explaining.

**Comment by dwelle** [comment]
That said, you can simply prevent the action from happening at all.

And later when support is added to move multiple points at once, this action will instead select all points.

**Comment by dwelle** [comment]
thx!

**Comment by lusingander** [comment]
thank you for confirming!

**Pull request merged**
