### PR TITLE
Add a gap between shapes and lock

### PR DESCRIPTION
**Pull request by vjeux**
The lock is a different type as the rest of the shapes, so we should visually separate it.

### CODE REVIEW

**Comment by dwelle** [comment]
I think this is still visually too close, and looks like a shape tool.

### this PR:

image

### Proposals:

A:

image


B: (but with this, there's no active state bg so it's less obvious it's active. We could change color or something)

image

**Comment by vjeux** [comment]
I like (B)

**Comment by dwelle** [comment]
Rebased to master and redesigned. Feel free to tweak as you like.

image

**Comment by vjeux** [comment]
Thanks, lgtm!

**Pull request merged**
