### PR TITLE
feat: add translatable strings

### PR DESCRIPTION
**Pull request by inwardmovement**
```
delete
shift
enter
space
up
down
wheel
```

and make use of existing `left` and `right` translatable strings

### CODE REVIEW

**Comment by dwelle** [comment]
Not sure about `Shift` and `Enter`. Though some languages do have a word for `Enter` (do they for `Shift`?), I haven't seen it translated on the keyboard itself (of course I have limited experience). It may end up so that translators come up with some names which are then displayed in the shortcut dialog and no one will know what to press.

**Comment by inwardmovement** [comment]
Yes in french we have a word for all those.
Shift > Maj
Enter > Entrée

I have those words on my (Logitech) keyboard keys, they seem pretty common to me in translated environments. "Shift" and "Enter" leave a "half-translated" feeling but maybe it's not very important for Excalidraw, I don't know, it's for you to evaluate.

Of course translators should make sure people know what to press.

**Comment by lipis** [comment]
yes, I also agree that it doesn't feel right to translate those..they are pretty common.

**Comment by lipis** [comment]
main-qimg-151799d2c2d34a77a24a8885416bf470

**Comment by vjeux** [comment]
French keyboards are usually translated :)

image

At least for French translation, it makes sense for it to be translated.

**Comment by dwelle** [comment]
@vjeux your screen actually shows that Shift/Enter/Space is not translated, which was the main issue we had with @lipis.

**Comment by lipis** [comment]
I changed my Gmail to French.. it seems like they are not doing it either..

Screenshot 2021-02-17 at 10 25 44 AM

**Comment by lipis** [comment]
I think we will close this.. as it will bring more confusion.. thanks

**Pull request closed without merging**
