### PR TITLE
Add file handling

### PR DESCRIPTION
**Pull request by tomayac**
On supporting operating systems (I think right now this is just Chrome OS), this PR adds the capability to open `.excalidraw` and `.json` files with Excalidraw.

https://github.com/WICG/file-handling/blob/master/explainer.md#example

### CODE REVIEW

**Comment by dwelle** [comment]
Is hijacking `.json` a good idea?

**Comment by tomayac** [comment]
> Is hijacking `.json` a good idea?

https://github.com/excalidraw/excalidraw/pull/1736#issuecomment-640503764 makes this less aggressively trigger only on `.excalidraw`.

**Comment by dwelle** [comment]
Cool. Can't test as I don't have ChromeOS. Hopefully more systems will support this.

**Comment by tomayac** [comment]
> Can you share gif or something to see that in action?!

Ironically it's seems to be broken (in the browser itself) at the moment. It should hopefully work again in the next Chrome release.

**Pull request merged**
