### PR TITLE
Introduce Shapelock

### PR DESCRIPTION
**Pull request by jillesme**
Adding a lock icon to lock the current shape selection (from https://github.com/excalidraw/excalidraw/pull/384).

Demo:

### CODE REVIEW

**Comment by lipis** [comment]
I think we should just lock without having the extra button..

**Comment by dwelle** [comment]
> I think we should just lock without having the extra button..

You mean making locking the default behavior?

Ad positioning, I understood it should be outside the list (and much smaller/less prominent --- i.e. no bg, border etc.)

> I was thinking of putting one checkbox at the right of the shape list with a little lock icon next to it. --- [source](https://github.com/excalidraw/excalidraw/pull/384#issuecomment-575277623)

**Comment by dwelle** [comment]
Also, I believe that once the lock is locked, it should persist until manually unlocked.

**Comment by lipis** [comment]
Yes have that the default behaviour if you ask me..without extra ui

**Comment by dwelle** [comment]
> Yes have that the default behaviour if you ask me..without extra ui

Figma does it like we do, and @vjeux implemented it like this by design, too. Also, it was decided in #384 to make it configurable as this PR does. Let's not change specs in the middle of decisions.

WTBS, let's create an issue to discuss possible alternatives. I have one in mind, but would probably require more work.

**Comment by jillesme** [comment]
> @dwelle Also, I believe that once the lock is locked, it should persist until manually unlocked.
I played around with both options and decided that you're right. Automatic unlock is removed https://github.com/excalidraw/excalidraw/pull/480/commits/b632047e40b6b65d21bc52432a1fae2c8bfa6140

**Comment by dwelle** [comment]
@jillesme also, while the tool is kept, the canvas acts as if selection tool is active (the element has resize handles).

**Comment by jillesme** [comment]
@dwelle I know, isn't that expected behaviour? Shouldn't the last drawn element always be selected

**Comment by dwelle** [comment]
> @dwelle I know, isn't that expected behaviour? Shouldn't the last drawn element always be selected

No, only if `selection` tool is active. Try selecting an element and switching to rectangle tool. It gets deselected.

**Comment by dwelle** [comment]
Also, the cursor shouldn't be reset, either.

**Comment by jillesme** [comment]
@dwelle I updated the cursor and selection.

**Comment by lipis** [comment]
Can we try it without the extra lock button?

**Comment by jillesme** [comment]
@lipis so how are we going to reset @vjeux's default behavior without the extra lock button?

**Comment by lipis** [comment]
@vjeux WDYT?

I think it's a nice behaviour.. click on rectangle.. draw a few.. click on circle.. draw a few.. etc!

**Comment by vjeux** [comment]
Yeah, I was thinking that the lock would stay locked until you manually unlock it

**Comment by vjeux** [comment]
The current PR is almost what i had in mind. Just don’t reset the lock when you change shape

**Comment by jillesme** [comment]
> @vjeux The current PR is almost what i had in mind. Just don’t reset the lock when you change shape

That's already done!

**Comment by vjeux** [comment]
Thanks!

**Comment by lipis** [comment]
Now let's have it locked all the time and remove the button! It's perfectly nice behaviour..

**Comment by gmertk** [comment]
Hey folks,
I didn't see this PR, and came back to the website just like a normal user. Saw this lock button. It wasn't clear to me at all what this lock button is supposed to do. I had to look at the commit history to find out what this is doing 😄  
Are we going to keep this button? If so, maybe we should think about ways to make it more intuitive.

**Comment by lipis** [comment]
My vote is to keep the behaviour as default when the lock is pressed and remove the button. It is confusing for new users for sure.

**Pull request merged**
