### PR TITLE
fix: set the width correctly using measureText in editor

### PR DESCRIPTION
**Pull request by ad1992**
Try adding a a letter in https://excalidraw.com/#json=8aAL_CLsjuwOKV4zLrCN0,p5reRLoF7GtLfj3etsol9g, it will add a new line in prod.

- [x] Chrome
- [x] Firefox

### CODE REVIEW

**Comment by ad1992** [comment]
I am also trying to fix https://github.com/excalidraw/excalidraw/issues/6093 as well with this fix, but `measureText` behaves differently in chrome and firefox hence the width is more in firefox due to which new line gets added.
Using `metrics.actualBoundingBoxLeft + metrics.actualBoundingBoxRight` gives accurate width in ff but in chrome `metrics.width` works hence the inconsistency

**Comment by dwelle** [comment]
> Try adding a a letter in [excalidraw.com/#json=8aAL_CLsjuwOKV4zLrCN0,p5reRLoF7GtLfj3etsol9g](https://excalidraw.com/#json=8aAL_CLsjuwOKV4zLrCN0,p5reRLoF7GtLfj3etsol9g), it will add a new line in prod.

While in this PR it doesn't add the newline, it increases the width by ~1px 👀

excal-pr-textwrap-1px-expand-issue

**Comment by ad1992** [comment]
> > Try adding a a letter in [excalidraw.com/#json=8aAL_CLsjuwOKV4zLrCN0,p5reRLoF7GtLfj3etsol9g](https://excalidraw.com/#json=8aAL_CLsjuwOKV4zLrCN0,p5reRLoF7GtLfj3etsol9g), it will add a new line in prod.
> 
> While in this PR it doesn't add the newline, it increases the width by ~1px 👀
> 
> excal-pr-textwrap-1px-expand-issue [ excal-pr-textwrap-1px-expand-issue ](https://user-images.githubusercontent.com/5153846/214828006-29a35d8d-c9d2-46df-94cd-21dcdd71e3b7.gif) [ ](https://user-images.githubusercontent.com/5153846/214828006-29a35d8d-c9d2-46df-94cd-21dcdd71e3b7.gif)

@dwelle for me its working fine, which browser and OS you are trying on ?

**Comment by dwelle** [comment]
> @dwelle for me its working fine, which browser and OS you are trying on ?

you're right. Tested, and it only reproduces on Win 10 Chrome, not MacOS Chrome. But on Safari it still adds newline, so not just FF that has the `measureText` inconsistency it seems.

**Comment by ad1992** [comment]
Yeah the `canvas.measureText` behaves differently, to test created a [demo](https://128lvh.csb.app/)

eg - Try with text `asdadasdd`

firefox
Screenshot 2023-01-26 at 8 53 10 PM

Chrome
Screenshot 2023-01-26 at 8 51 51 PM

**Comment by dwelle** [comment]
here's the number I get for text `wasdim`.

First number is `metrics.width`, second `metrics.actualBoundingBoxLeft + metrics.actualBoundingBoxRight`.

# Windows

- chrome

  ```
  64.79994201660156
  67.13995361328125
  ```
- firefox

  ```
  64.81666564941406
  63.749999777476
  ```

# MacOS

- chrome

  ```
  64.79994201660156
  63.73995453119278
  ```

- safari
  
  ```
  64.80000305175781
  64.80000305175781
  ```

- ff

  ```
  64.76667022705078
  65.699999777476
  ```

So neither of the metrics are constant across browsers/OS. `metrics.width` is close, but not fully.

**Comment by ad1992** [comment]
On further research, I found that we can take an adjustment factor of `0.2` and as the variation in browsers/OS doesn't go beyond `0.2` so safe to take and it works well. I will push it so you can try it out as well and we can merge this PR then.

However, one major issue right now is we are mixing up canvas and dom dimensions in `measureText` since I am taking width from canvas measureText but for final calculation I am considering dom height and forcing canvas width on dom elements which at times doesn't work out well coz of slight variation between the canvas and actual dom dimensions (which is expected due to HTML elements) so I will do a MVP for calculating height from canvas as well so we can completely move away from using DOM to calculate dimensions.
The canvas height looks same as DOM 

https://user-images.githubusercontent.com/11256141/215042955-9b564e51-8b1b-4a2b-87e8-882075064584.mov

And may be this adjustment factor of `0.2` might not be needed if we stop using DOM to calculate dimensions as well coz the main reason for the inconsistency is forcing canvas dims on the DOM element.

hence in this PR, I will also remove the canvas dimensions from `measureText` for now so that at least those inconsistencies don't happen due to mismatch of dimensions.

**Comment by ad1992** [comment]
> On further research, I found that we can take an adjustment factor of `0.2` and as the variation in browsers/OS doesn't go beyond `0.2` so safe to take and it works well. I will push it so you can try it out as well and we can merge this PR then.
> 
> However, one major issue right now is we are mixing up canvas and dom dimensions in `measureText` since I am taking width from canvas measureText but for final calculation I am considering dom height and forcing canvas width on dom elements which at times doesn't work out well coz of slight variation between the canvas and actual dom dimensions (which is expected due to HTML elements) so I will do a MVP for calculating height from canvas as well so we can completely move away from using DOM to calculate dimensions. The canvas height looks same as DOM
> 
>  Screen.Recording.2023-01-27.at.2.00.37.PM.mov 
> And may be this adjustment factor of `0.2` might not be needed if we stop using DOM to calculate dimensions as well coz the main reason for the inconsistency is forcing canvas dims on the DOM element.
> 
> hence in this PR, I will also remove the canvas dimensions from `measureText` for now so that at least those inconsistencies don't happen due to mismatch of dimensions.

ok so I have removed the `canvas.measureText` from `measureText` so it will consider DOM dimensions only and I will do a MVP for moving to canvas dims completely  as mentioned above so we use it everywhere when it comes to canvas and will be more faster as well.

This should fix https://github.com/excalidraw/excalidraw/issues/6093 and https://github.com/excalidraw/excalidraw/issues/6137

@dwelle can you test once if its fine now for you?
I have tested the prev issues as well mentioned in https://github.com/excalidraw/excalidraw/pull/6030 and https://github.com/excalidraw/excalidraw/pull/5996, I don't have a reproducible example for https://github.com/excalidraw/excalidraw/issues/5789 so that's the only which I am not able to test.

**Comment by dwelle** [comment]
Works the same across all browsers and OS! 👍

> On further research, I found that we can take an adjustment factor of `0.2` and as the variation in browsers/OS doesn't go beyond `0.2` so safe to take and it works well. I will push it so you can try it out as well and we can merge this PR then.

How does this fix work. I checked the code, but you're just adding `0.2` Isn't this just going to make the text break earlier for some cases and not others?

---


So temporarily we move to DOM-only, with the goal to switch to canvas-only? Long-term canvas-only indeed seems the way to go if we want to support node.js where we'd at most be able to get canvas (measureText).

But we're still mixing canvas/DOM – `measureText` is using DOM, but `getLineWidth` is using canvas, right?

**Comment by ad1992** [comment]
> Works the same across all browsers and OS! 👍
> 
> > On further research, I found that we can take an adjustment factor of `0.2` and as the variation in browsers/OS doesn't go beyond `0.2` so safe to take and it works well. I will push it so you can try it out as well and we can merge this PR then.
> 
> How does this fix work. I checked the code, but you're just adding `0.2` Isn't this just going to make the text break earlier for some cases and not others?

So earlier the issue was that firefox was differing by ~0.1-0.15px so adding `0.2` looks safe. As per text break, that shouldn't happen since minimum width to fit a char is ~3px when considering small font `16px`

image

You can run the same [CSB](https://128lvh.csb.app/) and check what it looks like in windows as well to be sure.
> 
> So temporarily we move to DOM-only, with the goal to switch to canvas-only? Long-term canvas-only indeed seems the way to go if we want to support node.js where we'd at most be able to get canvas (measureText).
> 
> But we're still mixing canvas/DOM – `measureText` is using DOM, but `getLineWidth` is using canvas, right?

Yep for wrap text we have been using canvas measureText from beginning else it would be super expensive so there might still be some inconsistencies but less that what its now.

**Comment by dwelle** [comment]
Shouldn't we rather substract the `0.2` so that we are erring on the side of "break later rather than earlier"? And shouldn't that constant be relative to font size?

I can still reproduce breaking early, though not through typing but resizing the container:

https://excalidraw-d9p5r7h9h-excalidraw.vercel.app/#json=hbprXSijRDZ4m3U5BaJ8m,_aQpuJwEwjM_nX9ne19-Sg

**Comment by ad1992** [comment]
> Shouldn't we rather subtract the 0.2 so that we are erring on the side of "break later rather than earlier"? And shouldn't that constant be relative to font size?

No that would actually have more inconsistency coz the diff between DOM width and canvas width increases more and additionally, it will not fix the bug of newline getting added. Also right now I am increasing the with by `0.2px` so that its closer to DOM width and similar across browsers, and also so that text doesn't break early whereas subtracting `0.2px` will lead to breaking the text early since I am assigning the width to the editor in `textWysiwyg.tsx` to fix the newline bug when adding a char

Screenshot 2023-01-27 at 10 02 15 PM

As per being relative to font size, that's not needed since if font size increases, the diff still remains similar, you can try with larger font sizes in the CSB and check the diff between browsers.

**Comment by ad1992** [comment]
> I can still reproduce breaking early, though not through typing but resizing the container:

https://excalidraw-d9p5r7h9h-excalidraw.vercel.app/#json=hbprXSijRDZ4m3U5BaJ8m,_aQpuJwEwjM_nX9ne19-Sg

I have pushed a fix for this and it works fine for me, can you try ?

**Comment by dwelle** [comment]
Works! Can't repro the issue.

**Comment by ad1992** [comment]
@dwelle this is ready to merge

**Review by dwelle — APPROVED** [review]

**Pull request merged**
