### PR TITLE
Add a doc with all the current shortcuts

### PR DESCRIPTION
**Pull request by lipis**
Let's keep track of this document that could be later used as a base for #408 or possible documentation page somewhere like excalidraw.com/docs/shortcuts

Preview: https://github.com/excalidraw/excalidraw/blob/shortcutdocs/docs/shortcuts.md

### CODE REVIEW

**Comment by lipis** [comment]
Feel free to commit directly to this branch with what I'm missing

**Comment by vjeux** [comment]
Could you add a screenshot by any chance? Thanks!

**Comment by vjeux** [comment]
Oh nvm, it’s a markdown file!

**Comment by dwelle** [comment]
Not a fan of doc files at this point (as I've stated elsewhere) -- it's another source of truth that will have to be kept up-to-date, and as such it should definitely not be used by #408 (which I still think should be entirely automated). In fact I think docs like these should be auto-generated, too.

**Comment by lipis** [comment]
At which point will be good enough?! Usually the shortcuts are not changing that often and we already missing a few.. it's a nice checklist to have with all the actions and their shortcut.

**Comment by dwelle** [comment]
Dunno, there's gonna be a larger rewrite of shortcuts when I (or someone) gets to it and figures out what are the industry standard hotkeys for certain tools.

I don't care either way, I'm just pointing out it's gonna be another thing that we'll need to keep up to date, which right now might not be worth the trouble (after all, how many people will look for hotkeys in a GH repo in a markdown file?).

**Comment by lipis** [comment]
It's more like an internal doc.. Not so hard to keep it updated and it has a nice overview of what's there and what's missing. 

When the shortcut overlay will be created within the app we can use all the existing shortcuts from this list and add/remove accordingly. Until we (if ever) automate that, we need to keep it up to date :) It's part of the job..

**Comment by nrgapple** [comment]
I can understand how this could be annoying to maintain, but this file was very helpful for me. I for one didn't know there was a shortcut for zoom.

**Comment by dwelle** [comment]
Yea, alright. I guess I'm too dismissive of these things :). Let's move this forward. :+1:

**Comment by lipis** [comment]
@dwelle can you update this list here with your latest changes?

**Comment by dwelle** [comment]
Shouldn't we put Mac hotkeys into `code`, too?

**Comment by lipis** [comment]
yes.. why not!

**Comment by j-f1** [comment]
I didn’t because they’re rendered with the normal UI font in the menus, and the code font kinda squishes the modifier keys.

**Comment by dwelle** [comment]
Let's merge this and keep up to date as we go along?

**Pull request merged**
