### PR TITLE
refactor: :construction: refactor wrap text (and working on renderEle…

### PR DESCRIPTION
**Pull request by ignacio-cuadra**
The goal of this PR is refactor the wrapText method and others related features (like container resize and fill text).

- [x] refactor the wrapText method to imitate the behavior of text area
  - [x] refactor wrap text
  - [x] update tests
- [x] refactor fill text with same proposal
  - [x] refactor horizontal offset
- [x] optimize

### CODE REVIEW

**Comment by ignacio-cuadra** [comment]
Regarding the wrapText method I prioritized code readability over efficiency, I broke this method in three parts:

1. *wrapText function*: split text in "hard lines returns" and then use breakLine function on each **trimmed** line that does not fit in container.
2. *breakLine function*: its like wrapText but with **words***, use breakWord function on each *trimed* word that does not fit in container
3. *breakWord function*: break words 😂

**Word***: its not a regular word, rather I want to refer to word with trailing spaces
'My cat is pooping' -> ['my ', 'cat ', 'is ', 'pooping'] (whit spaces) like textarea when a word is selected with Ctrl+Shift+Right Arrow

In this issue #4997  i explain why i try  to copy the textarea behaibor

**Comment by ad1992** [comment]
@ignacio-cuadra how about targetting one thing at a time ? so Only `text-wrap` refactor in this PR so its easy to review and test as well.

**Comment by ignacio-cuadra** [comment]
@ad1992 the new wrapText dont remove the trailing spaces, the spaces are controlled at draw the text. Because of this, it is necessary to rewrite code on renderElements file. But yes, textWysiwyg can be refactored in another PR.

**Comment by ad1992** [comment]
> @ad1992 the new wrapText dont remove the trailing spaces, the spaces are controlled at draw the text. Because of this, it is necessary to rewrite code on renderElements file. But yes, textWysiwyg can be refactored in another PR.

Sounds good 👍🏻 
Since both of us will be touching the same files and I have couple of PRs in progress so we might have conflicts once PRs are merged, In any such case I will help resolve them :)

**Comment by ignacio-cuadra** [comment]
@ad1992 could you guide me a little?

on test "Test wrapText" defines a font "20px Cascadia, width: Segoe UI Emoji", this font its working on testing? i am confused by the test outputs

**Comment by ignacio-cuadra** [comment]
I updated the tests.

considering that each character is equal to 10 pixels, and the container has a padding  of 5px on each side, the previous tests were wrong. Also, I added the spaces because the new functionality doesn't remove them.

(but im not sure about textWysiwyg tests)

**Comment by dwelle** [comment]
> Edit: is it possible to use faker.js or something like that? I didn't dare to install it without asking. 🫣

sure, go ahead!

**Comment by ad1992** [comment]
> I updated the tests.
considering that each character is equal to 10 pixels, and the container has a padding of 5px on each side, the previous tests were wrong. Also, I added the spaces because the new functionality doesn't remove them.
(but im not sure about textWysiwyg tests)

@ignacio-cuadra don't worry about the specs, once the PR is ready I will take a look at the tests.

**Comment by ad1992** [comment]
> I updated the tests.
considering that each character is equal to 10 pixels, and the container has a padding of 5px on each side, the previous tests were wrong. Also, I added the spaces because the new functionality doesn't remove them.
(but im not sure about textWysiwyg tests)

@ignacio-cuadra don't worry about the specs, once the PR is ready I will take a look at the tests.

**Comment by ignacio-cuadra** [comment]
@ad1992 and/or @dwelle
Would you please check the functionality? (no the code for now, I'm still working to optimize it)

**Comment by ignacio-cuadra** [comment]
ok, i'm done for now. 

About performance, the code is 2~ times slower than the previous code, but it does not affect the user experience. I could try to improve the performance but it would affect the readability of the code.

@dwelle i found this: [Intl Segmenter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter). that fix the emoji problem but it's not supported by Firefox (and I couldn't find a polyfill)

**Comment by ad1992** [comment]
@ignacio-cuadra thanks for the PR!
Doing quick testing on the PR and here are some issues I came across

Try editing text / resize you will see some displacement of text

https://user-images.githubusercontent.com/11256141/216585306-cff8ec48-d38d-4fd8-ab73-57d2aa2eba2e.mp4



```
{"type":"excalidraw/clipboard","elements":[{"id":"lXYpOynzXh0DcLgrQFQsn","type":"rectangle","x":356.5,"y":347.13671875,"width":143,"height":135,"angle":0,"strokeColor":"#000000","backgroundColor":"transparent","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":[],"roundness":null,"seed":47641214,"version":939,"versionNonce":1541651874,"isDeleted":false,"boundElements":[{"type":"text","id":"OnjPDQ12ZftCY08oEUeFd"}],"updated":1675421195571,"link":null,"locked":false},{"id":"OnjPDQ12ZftCY08oEUeFd","type":"text","x":361.5,"y":377.13671875,"width":133,"height":75,"angle":0,"strokeColor":"#000000","backgroundColor":"transparent","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":[],"roundness":null,"seed":1580386274,"version":960,"versionNonce":326755710,"isDeleted":false,"boundElements":null,"updated":1675421195572,"link":null,"locked":false,"text":"       hello \nworld.        ","fontSize":20,"fontFamily":1,"textAlign":"right","verticalAlign":"middle","baseline":68,"containerId":"lXYpOynzXh0DcLgrQFQsn","originalText":"       hello world.        "}],"files":{}}
```

The horizontal alignments/ resize don't work well with the below container

```
{"type":"excalidraw/clipboard","elements":[{"type":"rectangle","version":231,"versionNonce":1206824876,"isDeleted":false,"id":"LxFWgJcMPMJOV2fQeXHTq","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"angle":0,"x":364.23046875,"y":215.677734375,"strokeColor":"#000000","backgroundColor":"transparent","width":183,"height":91,"seed":2018276578,"groupIds":[],"roundness":{"type":3},"boundElements":[{"type":"text","id":"INf4OcweQC6-CoYviQBGp"}],"updated":1675421413935,"link":null,"locked":false},{"type":"text","version":415,"versionNonce":995856916,"isDeleted":false,"id":"INf4OcweQC6-CoYviQBGp","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"angle":0,"x":374.23046875,"y":256.677734375,"strokeColor":"#000000","backgroundColor":"transparent","width":173,"height":50,"seed":1485521470,"groupIds":[],"roundness":null,"boundElements":null,"updated":1675421419113,"link":null,"locked":false,"fontSize":20,"fontFamily":1,"text":"     hello world.      ","baseline":43,"textAlign":"right","verticalAlign":"bottom","containerId":"LxFWgJcMPMJOV2fQeXHTq","originalText":"     hello world.      "}],"files":{}}
```

https://user-images.githubusercontent.com/11256141/216586670-40e0d973-f127-42af-bd31-c07598620441.mp4

To confirm the goal of this PR is to imitate text area behavior (in relation to whitespaces) correct? 

Asking this as there are other issues where wrapping algo doesn't reflect the text area wrapping (I am planning to fix those myself as well) so just wanted to know if those are targeted in this PR, eg

Try editing the below element and the wrapping is not in sync

```
{"type":"excalidraw/clipboard","elements":[{"id":"ADAeb1A25mBlMlyHEFID7","type":"rectangle","x":529.5,"y":200.55078125,"width":97,"height":200,"angle":0,"strokeColor":"#000000","backgroundColor":"transparent","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":[],"roundness":null,"seed":271338260,"version":157,"versionNonce":491842988,"isDeleted":false,"boundElements":[{"type":"text","id":"xGatyhLnAg9RBunzxHpjf"}],"updated":1675422190975,"link":null,"locked":false},{"id":"xGatyhLnAg9RBunzxHpjf","type":"text","x":534.5,"y":250.55078125,"width":87,"height":100,"angle":0,"strokeColor":"#000000","backgroundColor":"transparent","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":[],"roundness":null,"seed":2303916,"version":153,"versionNonce":1321145108,"isDeleted":false,"boundElements":null,"updated":1675422190975,"link":null,"locked":false,"text":"Here I \nam 👋🏻🚀 \n🔥👋🏻 \n😀🥳","fontSize":20,"fontFamily":1,"textAlign":"center","verticalAlign":"middle","baseline":93,"containerId":"ADAeb1A25mBlMlyHEFID7","originalText":"Here I am 👋🏻🚀 🔥👋🏻 😀🥳"}],"files":{}}
```
Same with this as well

```
{"type":"excalidraw/clipboard","elements":[{"type":"rectangle","version":529,"versionNonce":2128371431,"isDeleted":false,"id":"ELbJD506EyC6cFn8MUIqo","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,"x":219,"y":186,"strokeColor":"#364fc7","backgroundColor":"transparent","width":240,"height":210,"seed":1291590823,"groupIds":[],"roundness":null,"boundElements":[{"type":"text","id":"Xzvha2xkG6NQN-erKno1E"}],"updated":1675330100833,"link":null,"locked":false},{"type":"text","version":585,"versionNonce":1888385223,"isDeleted":false,"id":"Xzvha2xkG6NQN-erKno1E","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,"x":226.00000000000009,"y":191,"strokeColor":"#364fc7","backgroundColor":"transparent","width":226,"height":200,"seed":635348297,"groupIds":[],"roundness":null,"boundElements":[],"updated":1675330102964,"link":null,"locked":false,"fontSize":20,"fontFamily":1,"text":"Hello there whats \nup?dskdjskdjskdjskjdsk\ndjskdjskdskdjskdjksdksj\ndkjskdsdjsjdksjdkskdjsk\ndjsjdksjdsjdjskjdksdjksj\ndksjdsddsdadasdadad\nasdsdasdadadadadas\ndsada","baseline":193,"textAlign":"center","verticalAlign":"middle","containerId":"ELbJD506EyC6cFn8MUIqo","originalText":"Hello there whats up?dskdjskdjskdjskjdskdjskdjskdskdjskdjksdksjdkjskdsdjsjdksjdkskdjskdjsjdksjdsjdjskjdksdjksjdksjdsddsdadasdadadasdsdasdadadadadasdsada"}],"files":{}}
```

**Comment by ignacio-cuadra** [comment]
> To confirm the goal of this PR is to imitate text area behavior (in relation to whitespaces) correct?

Yep, that's what i'm trying to do. 

I think that some issues are due to the textarea doesn't use the "bound text padding". But there is something else.

I will work on this, thanks for the review.

**Comment by ignacio-cuadra** [comment]
@ad1992 

Hi, i have been working on this and my conclusion is that it's necessary to use Intl.Segmenter to fix emojis problem (and other issues related to "complex characters"). This solution shouldn't be a problem but firefox does not support them.

Exists a pollyfill <a href="https://github.com/surferseo/intl-segmenter-polyfill">Intl Segmenter Polyfill</a> that works fine, but requires load a .wasm file that weighs 1.30MB

Do you have any idea?

**Comment by ad1992** [comment]
> @ad1992
> 
> Hi, i have been working on this and my conclusion is that it's necessary to use Intl.Segmenter to fix emojis problem (and other issues related to "complex characters"). This solution shouldn't be a problem but firefox does not support them.
> 
> Exists a pollyfill [Intl Segmenter Polyfill](https://github.com/surferseo/intl-segmenter-polyfill) that works fine, but requires load a .wasm file that weighs 1.30MB
> 
> Do you have any idea?

@ignacio-cuadra I am not sure which issues are you talking about with complex characters - but in my last comment what I meant is the first two issues that are breaking in the PR and work fine in prod so those surely need to be fixed.

As per the remaining ones, since that is not part of this PR, I will be picking it up soon so those can be skipped as I will be rewriting some parts of wrapping algos to fix those along with a few other issues.

As per `Intl.Segmenter` that can wait since those are specific cases so once text editor is strong enough we will come back to this.

So right now once those two blocking issues are fixed, we can start the code review.

**Comment by ad1992** [comment]
@ignacio-cuadra once I merge [this](https://github.com/excalidraw/excalidraw/pull/6187), the tests might need to get updated in your PR as now we will be moving to `canvas` measurements completely so mocking `measureText` for DOM methods will not be needed.

**Comment by ad1992** [comment]
@ignacio-cuadra I was reviewing the code, can we split this into two PRs? 
1. With only Refactoring for better readability (should work the same as prod)
2. With the bug fix for whitespace which you are targeting in this PR.

I was doing the refactor as I need it in another PR as well but since you have done refactoring in this PR hence wanted to know if you are fine splitting this into two PR.
As per the time complexity, I would still want to try to reduce it to the same as is currently in prod :) 
Let me know If I can go ahead with refactoring in a separate PR or if would you like to split yourself.

**Comment by ignacio-cuadra** [comment]
Hi, I'm sorry, I was working on other projects and forgot this one.

About your comment, yeah, it's a good idea but how can I split this PR?

should i create another PR with wrapText refactor?

I could use cherry pick or copy-paste... (i will use copy-paste definitely xD)

**Comment by ad1992** [comment]
> Hi, I'm sorry, I was working on other projects and forgot this one.
> 
> About your comment, yeah, it's a good idea but how can I split this PR?
> 
> should i create another PR with wrapText refactor?
> 
> I could use cherry pick or copy-paste... (i will use copy-paste definitely xD)

Yep Copy Paste will be better to use as the PR isn't up to date with `master` :D

**Comment by Mrazator** [comment]
Closing in favor of https://github.com/excalidraw/excalidraw/pull/8530

**Pull request closed without merging**
