### PR TITLE
feat: Add fitToContent and animate to scrollToContent

### PR DESCRIPTION
**Pull request by typehorror**
This PR relates to https://github.com/excalidraw/excalidraw/issues/6283

- [x] Add feature `fitToContent` as option to `scrollToContent`
- [x] Add tests for `fitToContent`
- [x] Add feature `animate` as option to  `scrollToContent`
- [x] Add tests for `animate`
- [x] Update Documentation

### CODE REVIEW

**Comment by dwelle** [comment]
Hey @typehorror, thanks for the PR and apologies for the delay! Looks very well written and also contains tests! ❤️

Checking the behavior, it's working really well.

The worry I had was about performance/smoothness with more elements on the scene, and there's indeed one issue around `fitToContent`. Every time we change zoom, it will bust the elements canvas cache (in `renderElement.ts`), unlike simple movement around the canvas — movement could still be an issue if the scrolled-to-elements weren't previously rendered, or were rendered on a different zoom level, but it's less likely to happen as opposed to zooming outright.

So, when `fitToContent` is `true`, I'd suggest to zoom to the target zoom level in the first frame instead of animating it.

Does that make sense?

**Comment by typehorror** [comment]
That makes a lot of sense, I'm not familiar with the intricacies of rendering on canvas but I can see why scrolling would be much cheaper than zooming... I'll get that adjusted.

**Comment by typehorror** [comment]
Hey @Fanoflix , 

this is just my opinion but in general you want to go with the most expressive form. Here, I'm using `startTime === undefined` even if it is overkill because it also tells part of the story (`startTime` will be `undefined`) which helps the reader understand the code. Having `!startTime` would imply that the variable could be `false`, `0`, `null`... which slightly murkies the water. The improvement is not game changing on it's own, but the accumulation of small improvements is.

**Comment by Fanoflix** [comment]
@typehorror Thanks for the reply. "Most expressive form" is a great way to put it. Thanks :)

**Comment by typehorror** [comment]
@dwelle This is ready for review, let me know if you have any question

**Comment by dwelle** [comment]
@typehorror sorry for the delay!

I've pushed some tweaks, namely:

- changing the easing function because the old one was having issues around the ending values (there was a jank).
- I'm also canceling in-progress animation if user starts panning or the scrollToContent is called in the middle.
- zoom to canvas center on initial anim instead of current scroll position
- added `opts.duration` customiztion
- updated docs

Thanks again for the PR! ❤️

**Review by dwelle — APPROVED** [review]

**Pull request merged**
