### PR TITLE
Choosing color before entering text does not update the swatch (Fixes #1897)

### LINKED ISSUE #1897: Choosing color before entering text content looks broken
Steps to repro:

1. Create a new text element
2. Before you type anything, try changing the stroke color to a different color

**What happens:**

The cursor color is changed, if you type you do get the new color. But the swatch keeps showing the color that was selected before you created the text element.

Screen Shot 2020-07-08 at 21 44 01

**What should happen:**

The swatch should reflect the newly selected color.

---

If you type at least one character this bug doesn't manifest.

### PR DESCRIPTION
**Pull request by msal4**
I'm checking if the element version is 3 and if it is we use the state.
I don't know if this is the ideal solution but it worked. let me know if there is a better way to handle this.

### CODE REVIEW

**Comment by dwelle** [comment]
I dug down and the root problem is we're deleting empty-text elements right during edit, so I addressed that instead. Hopefully nothing will break.

Pushed the fix myself because it'd be hard to convey.

Also took the opportunity to remove `onCancel` wysiwyg callback which was unnecessary.

**Comment by msal4** [comment]
Much better 👍

**Comment by dwelle** [comment]
Merging. Thanks @msal4 for looking into this, regardless! :)

**Comment by msal4** [comment]
My pleasure. I'm new to the codebase but I wanted to help anyways. I would be happy to participate if you could bear with me.

**Comment by vjeux** [comment]
@msal4: if you want to help, https://github.com/excalidraw/excalidraw/issues/1904 has concrete things that we'd like help with!

**Comment by msal4** [comment]
@vjeux sure! I'd love to.

**Pull request merged**
