### PR TITLE
fix: resize non solid lines/arrows/draws

### LINKED ISSUE #1606: Resizing non-solid lines may change the position of the object
Resizing non-solid lines (Lines, Arrows, Free draws) may change the position of the object.

### PR DESCRIPTION
**Pull request by dai-shi**
possibly fix #1606 

@lusingander can confirm?

@dwelle any idea for keeping the logic in sync?

### CODE REVIEW

**Comment by lusingander** [comment]
I don't know the condition to reproduce, but it seems to be fixed!

**Comment by dai-shi** [comment]
If you still have the reproduction, would you share the url here?

**Comment by dwelle** [comment]
While the shape has a reference for `options`, we sadly can't use it. I've factored out the option generation outside and exported it.

**Comment by dwelle** [comment]
I've deduplicated the helper some more. Will review my refactor before merge.

**Comment by dwelle** [comment]
Should be fine.

Thanks for the fix!

**Pull request merged**
