### PR TITLE
System clipboard

### PR DESCRIPTION
**Pull request by dwelle**
fix https://github.com/excalidraw/excalidraw/issues/859

Quickly hacked together, not sure if correct. Play with it and report, esp on browsers that don't support async clipboard API (firefox, safari?), and copy/paste between tabs/browsers, using various APIs (keyboard cmd-c/v, contextmenu...).

I'll tighten up the code and write tests later.

### CODE REVIEW

**Comment by lipis** [comment]
I could paste from all browsers to Chrome, Safari, but no Firefox.. could copy stuff from Firefox to other browsers though! Cool feature.

**Comment by dwelle** [comment]
> I could paste from all browsers to Chrome, Safari, but no Firefox.. could copy stuff from Firefox to other browsers though! Cool feature.

Cmd-c from chrome and then Cmd-v to Firefox doesn't work? AFAIK the only thing that shouldn't work is Cmd-c from other browser and contextmenu-paste to Firefox.

**Comment by lipis** [comment]
I didn't use the context menu.. just cmd+C/cmd+v.. out of the office now, so can't do more tests.

**Comment by dwelle** [comment]
Also note that I changed the schema of the object, so if you copied from a production and pasted into preview (or vice versa), then it wouldn't work.

**Comment by Fausto95** [comment]
It's a bit buggy when using keyboard shortcuts for copy/pasting between tabs/browsers.. but works just fine when using the CM

**Comment by dwelle** [comment]
> It's a bit buggy when using keyboard shortcuts for copy/pasting between tabs/browsers

Any specifics with steps would be appreciated!

**Comment by dwelle** [comment]
@lipis @Fausto95 gentle reminder, if you have reproduction steps on any bugs you have encountered with the copy/paste, please share

**Comment by Fausto95** [comment]
@dwelle on Safari, after drawing some elements, when you try copy with keyboard shortcuts then try to paste it in another tab or even in Chrome, it doesn't work. But if you do it with CM, it works just fine.

After copying/pasting with CM the first time, doing it using KS it works.

**Comment by lipis** [comment]
It seems that it works from all browsers that I tested (Chrome, Safari, Firefox)

I was using the shortcuts.

**Review by lipis — APPROVED** [review]

**Comment by dwelle** [comment]
> After copying/pasting with CM the first time, doing it using KS it works.

Oh, ok.. that sounds like the permission thing again. I'll try to investigate. Thanks.

**Comment by dwelle** [comment]
@Fausto95 I wasn't able to reproduce it across chrome/firefox tabs/browsers. The closest I could go is try to invoke the clipboard permission prompt (via contextmenu pasting) enough times without accepting that the browser automatically blocked further attempts. At that point I lost the ability to paste via contextmenu (until I manually reenabled the permission).

But what you're seeing I couldn't reproduce at all because keyboard shortcut pasting is preferentially handled via native `event.clipboardData.getData()` API which has no permissions attached. Not sure what else I can do.

As for single-tab copy/pasting, the above shouldn't happen at all (but it seems even you didn't encounter that) because the last fallback is in-memory clipboard.

If the issues happen only cross-tab/cross-browser, I think it's safe to go forward with this.

**Comment by lipis** [comment]
I think we can merge and improve later!

**Comment by dwelle** [comment]
I'll review and clean up the code, and potentially write tests. Will merge later today.

**Comment by Fausto95** [comment]
Let's merge this with current state.. and if users start to complain, will fix it

**Pull request merged**
