### PR TITLE
Create now.json for redirects

### LINKED ISSUE #1096: Redirect excalidraw.com/* to the root
- https://excalidraw.com/hola
- https://excalidraw.com/foo
- https://excalidraw.com/404

### PR DESCRIPTION
**Pull request by lipis**
Fixes #1096

### CODE REVIEW

**Comment by mbj36** [comment]
This first commit fixes the redirection..but it's some relative path issue..not sure why it is happening.

/(.*) - Infinite redirects

/(...*) - this works

**Comment by lipis** [comment]
I tried it.. it didn't

**Comment by mbj36** [comment]
https://excalidraw.mbj36.now.sh/hola/mola check this...redirection works but some errors in console

**Comment by lipis** [comment]
It seems that it redirects the static files as well.. :(

**Comment by mbj36** [comment]
Woah! It Worked @lipis 💯

**Comment by lipis** [comment]
It works partially now.. we are not redirecting anything with the `.` and it still fails.. any ideas?

**Comment by lipis** [comment]
Yeap!

**Pull request merged**
