### PR TITLE
Update FG_Virgil to support Russian and Greek characters

### LINKED ISSUE #469: Change hand-drawn font for non-latin support
I suggest change the hand-drawn font to another one for supporting not only latin languages.
Russian words do not look aesthetically pleasing (Cyrillic)

image

### PR DESCRIPTION
**Pull request by vjeux**
Ellinor Rapp was kind enough to add the characters to the font she built 18 years ago!

Fixes #469

### CODE REVIEW

**Comment by vjeux** [comment]
If someone speaking russian or greek could try it out and report if it's working, that'd be great! thanks https://excalidraw-l0g0ubrd2.now.sh/

**Comment by lipis** [comment]
Greek is looking good!

**Comment by vjeux** [comment]
Do you mind adding a screenshot of how it looks like?

**Comment by lipis** [comment]
https://deploy-preview-720--excalidraw.netlify.com/#json=5652956951085056,6tyE5E-64ePrpjAMd7SgmQ

(Can't drag and drop with my broken touch pad and forgot my external mouse at work)

**Comment by lipis** [comment]
image

**Comment by vjeux** [comment]
Looks like we mess up encoding while saving :x

image

**Comment by dwelle** [comment]
Can't repro.

**Comment by dwelle** [comment]
Oh, you mean saving to backend, not file. Can repro.

**Comment by dwelle** [comment]
Note that when we fix that, we need to ensure backward compat when decoding :/.

**Comment by vjeux** [comment]
Looks like we need to use TextEncoder/TextDecoder: https://stackoverflow.com/a/37902334/232122

**Comment by dwelle** [comment]
Yep, that works. At it seems to be backward compat without additional work.

**Comment by vjeux** [comment]
The russian letters are too small and bold. I'll circle back to see if this can be fixed before we merge it.

image

**Comment by dwelle** [comment]
When you're at it, *if* she ends up fixing it, you can tell her to fix the exclamation mark, if that's not too much trouble :).

**Comment by lipis** [comment]
kerning

Not sure if she could fix all these issues..  But there is some kerning issue in the `Γειά σου κόσμε` :) (Not the biggest deal though, and I'm amazed that she did it so fast..)

**Comment by vjeux** [comment]
@lipis can you provide a screenshot with explanation on the issue?

**Comment by lipis** [comment]
Also the Russian letters look a bit smaller than the rest..

Screenshot 2020-02-06 at 8 11 24 PM

**Comment by lipis** [comment]
> @lipis can you provide a screenshot with explanation on the issue?

73967708-41f08a00-48cd-11ea-80a0-36f09869276e

The space should be smaller between the first and second character.. 
(https://en.wikipedia.org/wiki/Kerning)

**Comment by szympajka** [comment]
It does not support polish 😅But I guess it's a problem for another day.
excalidraw-202026223532

**Comment by vjeux** [comment]
Ellinor made an update and the font now has 1038 glyphs! This looks great

image

**Comment by vjeux** [comment]
Here's the before:

image

**Comment by dwelle** [comment]
Awesome! Am I seeing it correctly that the `!` was fixed, too? Not quite the same as our own custom fix, but still pretty readable in my opinion.

**Comment by vjeux** [comment]
Yeah, it was updated too. I find it to be readable.

**Pull request merged**
