### PR TITLE
compile to es6 target

### PR DESCRIPTION
**Pull request by dwelle**
AFAIK we're not supporting pre-ES6 browsers, and we're certainly using APIs that aren't compatible with ES5.

This changes the TS compile target to ES6, which allows us (among other things) to iterate over maps without `downlevelIteration`, and doesn't compile async/await to generators blobs:

Currently (AFAIK) this:

```
async function test () {}
```

compiles to:

```
"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g;
    return g = { next: verb(0), "throw": verb(1), "return": verb(2) }, typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (_) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
function test() {
    return __awaiter(this, void 0, void 0, function () { return __generator(this, function (_a) {
        return [2 /*return*/];
    }); });
}
 
```

### CODE REVIEW

**Comment by dwelle** [comment]
Actually, this only changes TS compiler. But it seems the CRA uses babel or something else. So let's not merge this yet.

**Comment by dwelle** [comment]
Technically, we should already be compiling to ES6 considering our `browserlist` in package.json. So maybe telling TS we're already doing so is enough.

That said, the query we're using will target some very old browsers: https://browserl.ist/?q=%22%3E0.2%25%22%2C%22not+dead%22%2C%22not+ie+%3C%3D+11%22%2C%22not+op_mini+all%22

**Comment by dwelle** [comment]
I'd consider using this stricter query:

```
"last 2 versions and >0.2% and not dead and not ie 11"
```

https://browserl.ist/?q=%22last+2+versions+and+%3E0.2%25+and+not+dead+and+not+ie+11%22

**Comment by vjeux** [comment]
Here's the actual all time browser stats

```js
5,570	Chrome	79.0.3945.88	
5,409	Chrome	79.0.3945.130	
4,222	Safari	13.0.4	
3,525	Chrome	79.0.3945.117	
2,622	Chrome	80.0.3987.132	
2,072	Safari	13.0.5	
1,648	Chrome	80.0.3987.122	
1,290	Chrome	79.0.3945.93	
1,174	Firefox	72.0	
1,168	Chrome	79.0.3945.116	
991	Chrome	80.0.3987.87	
898	Chrome	79.0.3945.136	
750	Chrome	80.0.3987.116	
670	Chrome	78.0.3904.108	
612	Chrome	80.0.3987.106	
593	Firefox	73.0	
550	Firefox	71.0	
544	Chrome	78.0.3904.130	
423	Firefox	68.0	
404	Chrome	79.0.3945.79	
371	Chrome	79.0.3945.73	
329	Safari	13.0.3	
309	Safari	12.1.2	
309	Safari (in-app)	(not set)	
283	Chrome	80.0.3987.100	
246	Safari	13.0.1	
237	Chrome	80.0.3987.117	
192	Firefox	74.0	
174	Chrome	80.0.3987.119	
145	Chrome	78.0.3904.97	
139	Chrome	80.0.3987.99	
124	Chrome	80.0.3987.95	
123	Chrome	78.0.3904.87	
102	Samsung Internet	10.2	
99	Safari	605.1.15	
94	Safari	13.1	
87	UC Browser	11.9.4.974	
78	Android Webview	79.0.3945.116	
72	Chrome	77.0.3865.90	
69	Opera	65.0.3467.78	
68	Safari	12.1.1	
67	Chrome	76.0.3809.100	
67	Chrome	78.0.3904.70	
66	Chrome	80.0.3987.16	
65	Internet Explorer	11.0	
62	Chrome	77.0.3865.120	
58	Chrome	73.0.3683.75	
55	Android Webview	79.0.3945.93	
52	Android Webview	79.0.3945.136	
52	Chrome	71.0.3578.141	
52	Safari	12.0	
50	Chrome	76.0.3809.132	
46	Edge	18.18362	
46	Firefox	70.0	
46	Safari	13.0.2	
45	Chrome	75.0.3770.100	
42	Safari	12.1	
39	Mozilla Compatible Agent	5.0	
37	Chrome	73.0.3683.0	
32	Chrome	79.0.3945.94	
32	Firefox	69.0	
32	Firefox	75.0	
30	Edge	80.0.361.66	
29	Chrome	57.0.2987.133	
28	Chrome	75.0.3770.142	
28	Chrome	77.0.3865.92	
27	Chrome	72.0.3626.119	
27	Chrome	73.0.3683.86	
27	Chrome	77.0.3865.75	
27	Edge	18.18363	
26	Chrome	79.0.3945.123	
25	Safari	11.0	
24	Chrome	74.0.3729.157	
23	Chrome	69.0.3497.100	
23	Edge	18.17763	
23	Safari	13.0	
22	Chrome	72.0.3626.121	
22	Chrome	77.0.3865.116	
22	Chrome	78.0.3904.96	
22	Opera	66.0.3515.44	
21	Chrome	73.0.3683.103	
21	Internet Explorer	8.0	
21	Opera	55.2.2719.50740	
21	Samsung Internet	11.1	
20	Android Webview	66.0.3359.126	
20	Chrome	71.0.3578.98	
20	Chrome	74.0.3729.169	
20	Chrome	79.0.3945.86	
20	Chrome	80.0.3987.53	
20	Safari	10.0	
19	Firefox	60.0	
18	Chrome	78.0.3904.62	
18	Chrome	81.0.4000.3	
17	Android Webview	80.0.3987.132	
17	Chrome	74.0.3729.131	
17	Chrome	80.0.3987.42	
17	Opera	66.0.3515.72	
16	Chrome	60.0.3112.50	
16	Chrome	79.0.3945.131	
16	Chrome	81.0.4033.0	
16	Edge	80.0.361.62	
16	Samsung Internet	11.0	
15	Chrome	75.0.3770.80	
15	Firefox	66.0	
14	Chrome	53.0.2875.116	
14	Chrome	70.0.3538.110	
14	Edge	17.17134	
14	Safari	13.2	
14	Thomson Reuters - Inferno	(not set)	
13	Chrome	70.0.3538.77	
13	Chrome	80.0.3987.66	
13	Chrome	81.0.4044.34	
12	Chrome	76.0.3809.87	
12	Chrome	79.0.3945.119	
12	Chrome	81.0.4017.0	
12	Edge	80.0.361.54	
11	Chrome	75.0.3770.143	
11	Chrome	80.0.3987.78	
11	Chrome	81.0.4020.0	
11	YaBrowser	19.12.0.769	
10	Chrome	68.0.3440.106	
10	Chrome	69.0.3497.128	
10	Chrome	74.0.3729.136	
10	Chrome	76.0.3809.146	
10	Chrome	78.0.3904	
10	Edge	80.0.361.57	
10	Safari	12.0.3	
10	Safari	9.0	
9	Chrome	36.0.1985.125	
9	Chrome	76.0.3809.123	
9	Chrome	78.0.3904.84	
9	Chrome	78.0.3904.99	
9	Chrome	80.0.3987.18	
9	Chrome	80.0.3987.68	
9	Chrome	81.0.4021.2	
9	Chrome	81.0.4023.0	
9	Edge	79.0.309.71	
9	Edge	80.0.361.48	
9	Edge	81.0.410.1	
8	Chrome	65.0.3325.181	
8	Chrome	71.0.0.0	
8	Chrome	71.0.3578.99	
8	Chrome	74.0.3729.108	
8	Chrome	75.0.3770.90	
8	Chrome	78.0.3904.90	
8	Chrome	81.0.4033.2	
8	Chrome	81.0.4044.17	
8	Edge	80.0.361.50	
8	Safari	604.1	
7	Android Webview	80.0.3987.119	
7	Chrome	60.0.3112.113	
7	Chrome	73.0.3683.90	
7	Chrome	81.0.4044.26	
7	Edge	16.16299	
7	Edge	81.0.416.16	
7	Edge	81.0.416.6	
7	Opera	66.0.3515.27	
7	Safari	11.1.2	
7	Safari	12.0.1	
7	Samsung Internet	10.1	
6	Android Webview	80.0.3987.117	
6	Chrome	63.0.3239.132	
6	Chrome	70.0.3538.102	
6	Chrome	70.0.3538.64	
6	Chrome	77.0.3865.103	
6	Chrome	78.0.3904.106	
6	Chrome	80.0.3987.125	
6	Chrome	80.0.3987.58	
6	Chrome	80.0.3987.86	
6	Chrome	81.0.4028.0	
6	Chrome	81.0.4029.3	
6	Chrome	81.0.4044.43	
6	Chrome	82.0.4056.3	
6	Chrome	82.0.4077.0	
6	Firefox	56.0	
6	Firefox	58.0	
6	Opera	56.1.2780.51589	
6	Opera	64.0.3417.150	
6	Opera	66.0.3515.103	
5	Android Webview	62.0.3202.84	
5	Android Webview	80.0.3987.87	
5	Android Webview	80.0.3987.99	
5	Chrome	56.0.2924.87	
5	Chrome	57.0.2987.108	
5	Chrome	70.0.3538.25	
5	Chrome	70.0.3538.80	
5	Chrome	71.0.3578.89	
5	Chrome	81.0.4003.0	
5	Chrome	81.0.4014.0	
5	Chrome	81.0.4029.0	
5	Chrome	81.0.4031.0	
5	Chrome	82.0.4083.0	
5	Firefox	64.0	
5	Opera	66.0.3515.111	
5	Opera	66.0.3515.115	
5	YaBrowser	19.9.0.1768	
4	Android Browser	4.0	
4	Android Webview	78.0.3904.108	
4	Chrome	40.0.2214.85	
4	Chrome	61.0.3163.100	
4	Chrome	64.0.3282.137	
4	Chrome	66.0.3359.126	
4	Chrome	67.0.3396.87	
4	Chrome	67.0.3396.99	
4	Chrome	69.0.3497.81	
4	Chrome	71.0.3578.80	
4	Chrome	74.0.3729.186	
4	Chrome	76.0.3809.111	
4	Chrome	76.0.3809.131	
4	Chrome	76.0.3809.81	
4	Chrome	77.0.3865.93	
4	Chrome	79.0.3945.118	
4	Chrome	81.0.4027.0	
4	Chrome	81.0.4036.0	
4	Chrome	81.0.4040.5	
4	Chrome	81.0.4041.2	
4	Chrome	81.0.4043.2	
4	Chrome	82.0.4056.0	
4	Chrome	82.0.4062.3	
4	Chrome	82.0.4068.4	
4	Chrome	82.0.4069.0	
4	Chrome	82.0.4078.0	
4	Edge	80.0.361.56	
4	Edge	81.0.403.1	
4	Edge	81.0.416.28	
4	Edge	82.0.425.3	
4	Edge	82.0.439.1	
4	Firefox	43.0	
4	Firefox	65.0	
4	Firefox	67.0	
4	Opera	46.0.2254.145391	
4	Opera	64.0.3417.167	
4	Opera	67.0.3575.53	
4	Safari	538.1	
3	Android Webview	67.0.3396.87	
3	Android Webview	78.0.3904.62	
3	Android Webview	78.0.3904.96	
3	Chrome	55.0.2883.87	
3	Chrome	58.0.3029.110	
3	Chrome	61.0.3163.98	
3	Chrome	66.0.3359.181	
3	Chrome	68.0.3440.84	
3	Chrome	68.0.3440.91	
3	Chrome	70.0.3538.67	
3	Chrome	72.0.3626.109	
3	Chrome	75.0.3770.101	
3	Chrome	75.0.3770.103	
3	Chrome	76.0.3809.89	
3	Chrome	77.0.3865.129	
3	Chrome	77.0.3865.69	
3	Chrome	77.0.3865.73	
3	Chrome	79.0.3945.36	
3	Chrome	79.0.3945.8	
3	Chrome	80.0.3987.88	
3	Chrome	80.0.3987.89	
3	Chrome	81.0.4018.0	
3	Chrome	81.0.4034.0	
3	Chrome	81.0.4039.0	
3	Chrome	81.0.4044.4	
3	Chrome	81.0.4044.42	
3	Chrome	81.0.4044.5	
3	Chrome	82.0.4050.0	
3	Chrome	82.0.4070.0	
3	Edge	81.0.416.20	
3	Edge	81.0.416.3	
3	Firefox	52.0	
3	Firefox	57.0	
3	Firefox	62.0	
3	Firefox	63.0	
3	Internet Explorer	7.0	
3	Opera	65.0.3467.69	
3	Safari	8.0	
3	Samsung Internet	4.0	
3	Samsung Internet	9.2	
3	YaBrowser	19.12.3.332	
3	YaBrowser	20.2.0.1145	
2	''	(not set)	
2	Android Webview	66.0.3359.158	
2	Android Webview	74.0.3729.136	
2	Android Webview	74.0.3729.186	
2	Android Webview	76.0.3809.111	
2	Android Webview	77.0.3865.92	
2	Chrome	48.0.2564.109	
2	Chrome	48.0.2564.116	
2	Chrome	53.0.2785.134	
2	Chrome	62.0.3202.62	
2	Chrome	62.0.3202.94	
2	Chrome	64.0.3282.119	
2	Chrome	64.0.3282.140	
2	Chrome	64.0.3282.167	
2	Chrome	65.0.3314.0	
2	Chrome	65.0.3325.109	
2	Chrome	67.0.3396.79	
2	Chrome	72.0.3626.81	
2	Chrome	72.0.3626.96	
2	Chrome	74.0.3729.121	
2	Chrome	75.0.3770.120	
2	Chrome	76.0.3809.136	
2	Chrome	77.0.3849.0	
2	Chrome	78.0.3904.92	
2	Chrome	80.0.3987.136	
2	Chrome	80.0.3987.40	
2	Chrome	80.0.3987.67	
2	Chrome	81.0.3995.0	
2	Chrome	81.0.4001.0	
2	Chrome	81.0.4002.0	
2	Chrome	81.0.4016.0	
2	Chrome	81.0.4022.0	
2	Chrome	81.0.4026.0	
2	Chrome	81.0.4027.2	
2	Chrome	81.0.4028.2	
2	Chrome	81.0.4030.0	
2	Chrome	81.0.4037.2	
2	Chrome	81.0.4038.2	
2	Chrome	81.0.4040.0	
2	Chrome	81.0.4042.0	
2	Chrome	81.0.4044.3	
2	Chrome	81.0.4044.62	
2	Chrome	82.0.4047.0	
2	Chrome	82.0.4049.0	
2	Chrome	82.0.4051.0	
2	Chrome	82.0.4053.0	
2	Chrome	82.0.4060.0	
2	Chrome	82.0.4062.8	
2	Chrome	82.0.4065.1	
2	Chrome	82.0.4067.0	
2	Chrome	82.0.4078.2	
2	Chrome	82.0.4082.0	
2	Edge	79.0.309.65	
2	Edge	82.0.432.3	
2	Firefox	44.0	
2	Opera	65.0.3467.48	
2	Opera	65.0.3467.72	
2	Opera	66.0.3515.36	
2	Safari	11.0.3	
2	Safari	12.2	
2	Samsung Internet	8.2	
2	Samsung Internet	9.4	
2	w3m	(not set)	
2	YaBrowser	19.12.1.121.00	
2	YaBrowser	19.12.3.320	
2	YaBrowser	19.12.4.25	
2	YaBrowser	20.2.0.1043	
2	YaBrowser	20.2.0.215.00	
1	Amazon Silk	78.4.6	
1	Amazon Silk	78.5.26	
1	Amazon Silk	79.1.135	
1	Amazon Silk	79.3.13	
1	Amazon Silk	79.4.9	
1	Amazon Silk	80.1.145	
1	Android Webview	43.0.2357.121	
1	Android Webview	44.0.2403.119	
1	Android Webview	49.0.2623.91	
1	Android Webview	57.0.2987.132	
1	Android Webview	64.0.3282.137	
1	Android Webview	70.0.3538.110	
1	Android Webview	70.0.3538.64	
1	Android Webview	71.0.3578.141	
1	Android Webview	71.0.3578.99	
1	Android Webview	75.0.3770.143	
1	Android Webview	76.0.3809.132	
1	Android Webview	76.0.3809.89	
1	Android Webview	78.0.3904.83	
1	Android Webview	80.0.3987.68	
1	BlackBerry	10.3.3.3204	
1	BlackBerry	10.3.3.3216	
1	candroid	6.6.5	
1	Chrome	32.0.1667.0	
1	Chrome	38.0.1025.166	
1	Chrome	45.0.2454.101	
1	Chrome	49.0.2623.112	
1	Chrome	49.0.2623.221	
1	Chrome	53.0.2785.109	
1	Chrome	53.0.2785.143	
1	Chrome	53.0.2785.146	
1	Chrome	54.0.2840.68	
1	Chrome	55.0.2883.75	
1	Chrome	57.0.2987.98	
1	Chrome	59.0.3071.115	
1	Chrome	60.0.3112.101	
1	Chrome	60.0.3112.105	
1	Chrome	60.0.3112.78	
1	Chrome	60.0.3112.89	
1	Chrome	61.0.3163.128	
1	Chrome	61.0.3163.79	
1	Chrome	62.0.3202.89	
1	Chrome	63.0.3239.111	
1	Chrome	63.0.3239.73	
1	Chrome	65.0.3312.0	
1	Chrome	65.0.3325.230	
1	Chrome	66.0.3359.117	
1	Chrome	66.0.3359.158	
1	Chrome	69.0.3497.102	
1	Chrome	69.0.3497.105	
1	Chrome	69.0.3497.92	
1	Chrome	69.0.3947.100	
1	Chrome	70.0.3538.60	
1	Chrome	70.0.3538.75	
1	Chrome	72.0.3626.101	
1	Chrome	73.0.0.0	
1	Chrome	73.0.3683.10	
1	Chrome	73.0.3683.105	
1	Chrome	73.0.3683.68	
1	Chrome	73.0.3683.88	
1	Chrome	74.0.3724.8	
1	Chrome	74.0.3729.172	
1	Chrome	74.0.3729.6	
1	Chrome	75.0.3752.2	
1	Chrome	75.0.3765.0	
1	Chrome	75.0.3770.145	
1	Chrome	75.0.3770.159	
1	Chrome	75.0.3770.82	
1	Chrome	75.0.3900.0	
1	Chrome	76.0.3809.36	
1	Chrome	76.0.3809.46	
1	Chrome	76.0.3809.62	
1	Chrome	76.0.3809.86	
1	Chrome	76.0.3809.99	
1	Chrome	77.0.3831.6	
1	Chrome	77.0.3865.121	
1	Chrome	77.0.3865.35	
1	Chrome	77.0.3865.78	
1	Chrome	78.0.3887.7	
1	Chrome	78.0.3904.50	
1	Chrome	78.0.3904.94	
1	Chrome	79.0.3909.0	
1	Chrome	79.0.3939.0	
1	Chrome	79.0.3945.16	
1	Chrome	79.0.3945.56	
1	Chrome	79.0.3945.74	
1	Chrome	79.0.3945.83	
1	Chrome	80.0.3953.5	
1	Chrome	80.0.3955.4	
1	Chrome	80.0.3964.0	
1	Chrome	80.0.3965.0	
1	Chrome	80.0.3973.0	
1	Chrome	80.0.3983.2	
1	Chrome	80.0.3985.0	
1	Chrome	80.0.3987.107	
1	Chrome	80.0.3987.118	
1	Chrome	80.0.3987.39	
1	Chrome	80.0.3987.9	
1	Chrome	81.0.3992.4	
1	Chrome	81.0.3993.0	
1	Chrome	81.0.3997.0	
1	Chrome	81.0.4000.0	
1	Chrome	81.0.4005.0	
1	Chrome	81.0.4007.0	
1	Chrome	81.0.4013.0	
1	Chrome	81.0.4019.3	
1	Chrome	81.0.4029.4	
1	Chrome	81.0.4032.0	
1	Chrome	81.0.4035.0	
1	Chrome	81.0.4036.2	
1	Chrome	81.0.4040.6	
1	Chrome	81.0.4041.0	
1	Chrome	81.0.4041.3	
1	Chrome	81.0.4044.9	
1	Chrome	82.0.4052.3	
1	Chrome	82.0.4055.2	
1	Chrome	82.0.4057.2	
1	Chrome	82.0.4064.0	
1	Chrome	82.0.4068.0	
1	Chrome	82.0.4068.5	
1	Chrome	82.0.4071.3	
1	Chrome	82.0.4073.0	
1	Chrome	82.0.4074.0	
1	Chrome	82.0.4075.0	
1	Chrome	82.0.4084.0	
1	Chrome	82.0.4085.0	
1	DingTalkBot-LinkService	1.0	
1	Edge	13.10586	
1	Edge	15.15063	
1	Edge	18.19541	
1	Edge	18.19577	
1	Edge	79.0.309.54	
1	Edge	79.0.309.63	
1	Edge	79.0.309.68	
1	Edge	80.0.361.40	
1	Edge	82.0.437.0	
1	Firefox	31.0	
1	Firefox	45.0	
1	Firefox	46.0	
1	Firefox	48.0	
1	Firefox	55.0	
1	Firefox	59.0	
1	Firefox	76.0	
1	Internet Explorer	10.0	
1	Iron	2.9.1	
1	N	A	
1	netdisk;2.2.2;pc;pc-mac;10.14.5;macbaiduyunguanjia	(not set)	
1	Opera	12.14	
1	Opera	46.3.2246.127744	
1	Opera	53.1.2569.142848	
1	Opera	56.0.2737.50781	
1	Opera	56.0.2780.51441	
1	Opera	56.0.2780.51583	
1	Opera	62.0.3331.18	
1	Opera	62.0.3331.43	
1	Opera	63.0.3368.71	
1	Opera	63.0.3368.94	
1	Opera	64.0.3417.172	
1	Opera	64.0.3417.83	
1	Opera	64.0.3417.92	
1	Opera	65.0.3467.56	
1	Opera	66.0.3515.21	
1	Opera	66.0.3515.60	
1	Opera	67.0.3575.31	
1	Opera	67.0.3575.8	
1	Safari	10.0.3	
1	Safari	10.1.2	
1	Safari	11.0.2	
1	Safari	11.1.1	
1	Safari	12.0.2	
1	Safari	13.2.3	
1	Safari	5.1	
1	Safari	534.34	
1	Safari	603.3.8	
1	Safari	604.1.38	
1	Safari	604.5.6	
1	Safari	7.0	
1	SeaMonkey	2.49.5	
1	UC Browser	12.7.0.1235	
1	YaBrowser	18.7.1.773	
1	YaBrowser	19.12.2.106.00	
1	YaBrowser	19.12.2.119.00	
1	YaBrowser	19.12.2.68.00	
1	YaBrowser	19.12.3.101.00	
1	YaBrowser	19.12.4.87.00	
1	YaBrowser	19.9.4.104.00	
1	YaBrowser	20.2.1.248	
1	YaBrowser	20.2.3.213	
1	YaBrowser	20.2.4.5.00	
1	YaBrowser	4.0	
```

**Comment by dwelle** [comment]
So what do we do? Just change the TS config for now (won't change build)?

**Comment by vjeux** [comment]
Does changing the tsconfig actually do anything?

**Comment by j-f1** [comment]
Here’s a visualization of @vjeux’s stats: https://observablehq.com/d/48ec9a614277a96e

**Comment by dwelle** [comment]
TS config will only allow us to use certain constructs without failing on compilation (type checking), but AFAIK it won't change emitted code at all because we're not using TS compiler for that.

From the nice visualization @j-f1 did, it seems we're pretty safe going with ES6. Trouble is I don't know what `browserlist` query to use to achieve that.

This query may be unnecessarily strict:

```
last 2 versions and >0.2% and not dead and not ie 11
```

browserl.ist/?q=%22last+2+versions+and+%3E0.2%25+and+not+dead+and+not+ie+11%22

But any other query may or may not end up targeting pre-ES6 browsers. Feel free to come up with something (also note that the browserl.ist visualization is likely inaccurate, per some GH issues).

**Comment by j-f1** [comment]
Jamie Kyle [recommended](https://jamie.build/last-2-versions) [`>0.25%, not ie 11, not op_mini all`](https://browserl.ist/?q=%3E0.25%25%2C+not+ie+11%2C+not+op_mini+all)

**Comment by dwelle** [comment]
That also targets Safari 5 (pre-ES6), and Chrome 49.

**Comment by dwelle** [comment]
Let's close this for now as there's no clear way how to move forward.

**Pull request closed without merging**
