### PR TITLE
some refactoring in app.tsx 

### PR DESCRIPTION
**Pull request by ad1992**
use constants instead of hardcoded strings for better readability

don't use an inline function as it will create a new reference every time

I have made some minor refactoring in the code for better readability. 
Please let me know if this is acceptable.

### CODE REVIEW

**Comment by j-f1** [comment]
I don’t think it’s a good idea to make the events be a constant, but I’m ambivalent about the other ones.

**Comment by dwelle** [comment]
What's the issue? One benefit of constatns is you can do an easy reference lookup in vscode.

**Comment by j-f1** [comment]
I’m pretty sure `*.addEventListener` will autocomplete the event names.

**Comment by dwelle** [comment]
I meant vscode's `go to references`. E.g. clicking on `EVENT.COPY` will give you all occurrences in the codebase, which is better than doing a search which gives you unrelated results.

**Pull request merged**
