### PR TITLE
feat: allow props.initialData to be a function

### PR DESCRIPTION
**Pull request by es-romo**
- Allow `initialData` to be a function.
- Update `api/props/` and `api/props/initialdata` docs

The function is being called twice in development builds because of [strict mode](https://legacy.reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects) but it does not impact production builds.

close: #8107

### CODE REVIEW

**Comment by es-romo** [comment]
It's good for review! @dwelle

I'm not 100% convinced about the wording for the `initialData` doc so please let me know what you think.

**Review by dwelle — APPROVED** [review]

**Comment by dwelle** [comment]
Looks good, thanks for the PR!

**Comment by dwelle** [comment]
@es-romo I forgot to mention that the docs changes must be made in a separate PR merging them into [`docs-next`](https://github.com/excalidraw/excalidraw/tree/docs-next) branch, because we will be updating the public docs only after we release the next stable npm release (we currently don't version the docs).

When you're at it, could you also update the description of this page so it reflects the function signature https://docs.excalidraw.com/docs/@excalidraw/excalidraw/api/props/initialdata?

**Comment by dwelle** [comment]
Also, please update the changelog `packages/excalidraw/CHANGELOG.md` (unreleased -> features) 🤗

**Comment by dwelle** [comment]
Good to go, thanks!

**Comment by es-romo** [comment]
@dwelle thanks for merging it! I'm finishing up the docs now (sorry for the delay). I have one question though, it is in the other pr #8166.

**Pull request merged**
