### PR TITLE
chore(i18n): add zh-tw language

### PR DESCRIPTION
**Pull request by neighborhood999**

### CODE REVIEW

**Comment by lipis** [comment]
Is this a traditional Chinese?

We wanted to start with the simplified: https://crowdin.com/project/excalidraw/zh-CN do you mind continuing there, because we are using Crowdin for translations and for now, we don't support dialects per language.

**Comment by neighborhood999** [comment]
> Is this a traditional Chinese?
> 
> We wanted to start with the simplified: [crowdin.com/project/excalidraw/zh-CN](https://crowdin.com/project/excalidraw/zh-CN) do you mind continuing there, because we are using Crowdin for translations and for now, we don't support dialects per language.

Hi @lipis 

Yes, is called Traditional Chinese and it's not the language of the dialect.

Crowdin have this option:
螢幕快照 2020-03-19 上午9 31 45

**Comment by lipis** [comment]
https://crowdin.com/project/excalidraw/zh-TW You can continue translating them there and eventually it will me merged into the master.

**Comment by lipis** [comment]
https://github.com/excalidraw/excalidraw/pull/1011

**Pull request closed without merging**
