### PR TITLE
show reset icon with zoom percentage during zen mode

### PR DESCRIPTION
**Pull request by ad1992**
Fixes https://github.com/excalidraw/excalidraw/issues/1522

### CODE REVIEW

**Comment by dwelle** [comment]
Looking great!

One thing, that also affects my fix for the shape-lock icon. The `pointer-events: none` doesn't seem to work in that it doesn't allow for canvas pointer events underneath. I couldn't make it work myself, and forgot about it.

excal_zen_pointerevents_bug

Unsure if we can do something about it except `display: none`, which would prevent the fade-out/in animation :/.

**Comment by ad1992** [comment]
> Looking great!
> 
> One thing, that also affects my fix for the shape-lock icon. The `pointer-events: none` doesn't seem to work in that it doesn't allow for canvas pointer events underneath. I couldn't make it work myself, and forgot about it.
> 
> excal_zen_pointerevents_bug
> 
> Unsure if we can do something about it except `display: none`, which would prevent the fade-out/in animation :/.

@dwelle I have set the height and width to 0 in zen mode, If this looks fine we can do the same for the lock icon.

**Comment by dwelle** [comment]
> @dwelle I have set the height and width to 0 in zen mode, If this looks fine we can do the same for the lock icon.

That still leaves ~20px wide place where you can't interact with canvas, for some reason (probably something related to grid gaps). But since you're not animating the width/height, it effectively makes it visually identical with setting its `display` to `none`, so I suggest doing that directly (which will fix the 20px issue).

**Comment by ad1992** [comment]
> > @dwelle I have set the height and width to 0 in zen mode, If this looks fine we can do the same for the lock icon.
> 
> That still leaves ~20px wide place where you can't interact with canvas, for some reason (probably something related to grid gaps). But since you're not animating the width/height, it effectively makes it visually identical to setting its `display` to `none`, so I suggest doing that directly (which will fix the 20px issue).

@dwelle now you should be able to interact with the canvas. Please let me know if this looks fine.

**Comment by dwelle** [comment]
Works, but there's an annoying jump when toggling zen mode:

excal_zen_lock_jump

**Comment by ad1992** [comment]
> Works, but there's an annoying jump when toggling zen mode:
> 
> excal_zen_lock_jump

Yeah I had removed the visibility that's why the jump, I have removed the disable pointer class from lock icon and  the footer as it's not needed here now

**Comment by ad1992** [comment]
Now that I am setting the width and height to 0 for the lock icon so so the shapes toolbar shifts slightly to the right to come to the center. Is that fine or should I add some CSS so that it doesn't slide to right/left when toggling zen mode?

**Comment by dwelle** [comment]
Let's merge it and we can tweak it if it starts to bother people.

**Pull request merged**
