### PR TITLE
feat: ctrl/cmd+f to search text

### PR DESCRIPTION
**Pull request by dragonman225**
I've been using Excalidraw as a freeform whiteboard to jot down ideas and study things for a while. I appreciate its simplicity, performance, and hand-drawn styles. But there's a painful thing: when I'm reviewing things I've drawn/written and want to look for specific text, I have to do it manually with my eyes.

Searching through the issues I found related discussion in #3826, and an incomplete implementation in #3890. Given that #3890 is a bit old, I decided to hack together a new prototype based on the latest master branch.

Here's a sneak peek:

https://user-images.githubusercontent.com/25148955/178519581-68ea1b8b-3ac7-4a7b-ae88-de453b26cca6.mov

The code is modeled after the `Stats` component, and the UI is inspired by Firefox's Ctrl/Cmd+F search (still rough, though). It's fully working with fuzzy-search (via [Fuse.js](https://fusejs.io/)) and scroll-to-view (via exporting [`zoomToFitElements`](https://github.com/dragonman225/excalidraw/blob/82eba2928688ebbf2d75c2aabdfdcbb2a95bcb73/src/actions/actionCanvas.tsx#L215)).

I'd like to share it and I'm happy to discuss about points to polish if you want to move forward with this feature.

A non-exhaustive list of topics:
- Use icons for Prev/Next buttons -> What icons would you like to use? e.g. Material Icons
- Cmd/Ctrl+F when search is *already open* should focus the input, how to listen to such an event properly? (`autoFocus` prop on `<input>` only works when it is rendered the first time)
- Benchmark performance. Is it possible to listen to text create/delete events so we don't have to [build search index from scratch on every input value change](https://github.com/dragonman225/excalidraw/blob/82eba2928688ebbf2d75c2aabdfdcbb2a95bcb73/src/components/Search.tsx#L70)?
- Is it necessary to highlight text?
  - It's ok for me to just have scroll-to-view.
- Is it ok to export [`zoomToFitElements`](https://github.com/dragonman225/excalidraw/blob/82eba2928688ebbf2d75c2aabdfdcbb2a95bcb73/src/actions/actionCanvas.tsx#L215)? Or are there better ways to achieve the same effect?
- What is the desired behavior for mobile?
- Feedback on the UI.

Thanks for building this great project and reviewing my pull request!

### CODE REVIEW

**Comment by 7flash** [comment]
This seems very useful.

**Comment by sojusnik** [comment]
Any updates on this? This feature would rock!

**Comment by sstar0016** [comment]
This looks awesome!
I want to use Excalidraw to take notes on PDFs (well I guess image printouts of pdfs) but at this stage it wouldnt be useful at all as I wouldn't be able to scroll through to the relevant time I wrote "state space modelling" (instead of the 800 other times in the same pdf)

**Comment by 7flash** [comment]
> This looks awesome! I want to use Excalidraw to take notes on PDFs (well I guess image printouts of pdfs) but at this stage it wouldnt be useful at all as I wouldn't be able to scroll through to the relevant time I wrote "state space modelling" (instead of the 800 other times in the same excalidraw doc)

Are you importing those as images? I have actually built a feature that makes text from them transcribed and saved into database, allowing to perform the search globally beyond the current canvas. Let me know if that's what you need I will open a PR.

**Comment by sstar0016** [comment]
> Are you importing those as images? I have actually built a feature that makes text from them transcribed and saved into database, allowing to perform the search globally beyond the current canvas. Let me know if that's what you need I will open a PR.

Yes! That would be absolutely incredible! 
My current workflow is me trying to use Excalidraw+Obsidian as a Onenote replacement:
- take pdf and use online converter to download zip file of page jpgs
- import into excali and rearrange using your (@7flash) excellent script [Grid Selected Images](https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/master/ea-scripts/Grid%20Selected%20Images.md )
- Take notes

My current big issues are
- search option kinda sucks in excali for my workflow (so your offer would be greatly appreciated)

Feature improvements that would be cool:
- Fix a bug that makes integration with Obsidian a bit rubbish [BUG: Issues with the dimensions of area transclusions](https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/967 )
- A script to automate the process of importing pdfs so I could just select the file and it would insert the file and do OCR

**Comment by 7flash** [comment]
@sstar0016 Question about OCR: would you like to see the image actually replaced with text, either the text to be associated with the image element for searching purpose only? Thinking out loud, perhaps can keep both image because it looks better with original formatting and also text for copying on double click, like in iphones?

**Comment by sstar0016** [comment]
> perhaps can keep both image because it looks better with original formatting and also text for copying on double click, like in iphones?

Yeah 100%, that would be above and beyond what I would expect but if that is possible that would be incredible. 

The dream ocr feature would be text in location so if #5435 gets put into use we'd be able to have similar functionality to below, where we can go through all instances of a word in a doc, whether we wrote it or it is scanned in
image




image

**Comment by 7flash** [comment]
@sstar0016 Do you mind if search results are not shown in UI but rather appear as text/link elements referencing to specific coordinates on the canvas?

**Comment by sstar0016** [comment]
> @sstar0016 Do you mind if search results are not shown in UI but rather appear as text/link elements referencing to specific coordinates on the canvas?

I would be super happy with any implementation of search, I can adjust to any implementation so long as the functionality is there. I do think that simple text coordinates would not be as helpful as a link that would bring you to the point precisely but again, I would be greatly appreciative of any implementation that gets closer to the functionality Onenote has

**Comment by Mrazator** [comment]
Closing in favor of https://github.com/excalidraw/excalidraw/pull/8438.

**Pull request closed without merging**
