### PR TITLE
Fix resize logic (partly)

### PR DESCRIPTION
**Pull request by dai-shi**
- Extract refactored code from #1427, that will likely to conflict with others
- Fix negative flicker bug (#1443)

### CODE REVIEW

**Comment by dai-shi** [comment]
@dwelle Would you check the behavior if it works for you in terms of #1443?

There's another approach you might like, which is to change like the following
```ts
  const offsetPointer = 0;
  const minSize = 0;
```
in `resizeElements.ts`.

**Comment by dwelle** [comment]
This behaves weirdly --- it skips resizing below ~10px width/height from both sides:

excal_negative_resize_skip

**Comment by dai-shi** [comment]
Well, that's logically correct with `offsetPointer`.
I made it `0` in the latest commit. How do you like this one?
(No idea yet to solve both issues.)

**Comment by dai-shi** [comment]
> (No idea yet to solve both issues.)

I have one. How do you like this? A breaking change in UI.

image

**Comment by dai-shi** [comment]
OK, let me commit it, because it make a lot of sense.

**Comment by dwelle** [comment]
Works great, except one problem: resizing to the negative moves the shape by one pixel before expanding further.

excal_resize_negative_move

> I have one. How do you like this? A breaking change in UI.

I don't know. I wouldn't do this in this PR (let's create a discussion issue for it).

Also, this PR worsens a case we fixed one (https://github.com/excalidraw/excalidraw/pull/341): when you click on a handle to resize and move the mouse slightly, the element jumps and resizes to cursor position (the position of the handle you clicked on). This behavior is present even in prod, but in this PR it looks like it was made worse :/.

(Note that all the above bugs and the bug this PR fixes were all fixed and working ~month ago, so I'm just trying to make us fix these regressions to move us back to where we once were.)

**Comment by dai-shi** [comment]
I guess #341 doesn't take account the case of #1296 and negative flip.

> This behavior is present even in prod

Are you sure? That's the purpose of `offsetPointer`.

----

I actually don't understand why flicker happens, so maybe there's a better way to fix it. It should technically be possible.
Reverting a commit for now.

**Comment by dai-shi** [comment]
> I actually don't understand why flicker happens

It think I got it and fixed.

@dwelle Would you please check it again?

> resizing to the negative moves the shape by one pixel before expanding further.

I can't reproduce this issue. Maybe this only occurs in a low-resolution screen.
The possible hack I come up with is the following:

```diff
diff --git a/src/element/resizeElements.ts b/src/element/resizeElements.ts
index e05e463..95ff974 100644
--- a/src/element/resizeElements.ts
+++ b/src/element/resizeElements.ts
@@ -140,7 +140,7 @@ export const resizeElements = (
   const handleOffset = 4 / appState.zoom; // XXX import constant
   const dashedLinePadding = 4 / appState.zoom; // XXX import constant
   const offsetPointer = handleOffset + dashedLinePadding;
-  const minSize = 0;
+  const minSize = 0.1; // a magic number for low resolution screen
   if (selectedElements.length === 1) {
     const [element] = selectedElements;
     if (resizeHandle === "rotation") {
```

Does this mitigate your issue?

**Comment by dwelle** [comment]
Still suboptimal in that it freezes resizing below the given threshold. When I get a chance, I'll try to fix this since you're probably stabbing in the dark, being on high DPI screen yourself.

**Comment by dai-shi** [comment]
> When I get a chance, I'll try to fix this

That would be nice.

> this PR worsens a case we fixed once (#341)

I assume it is fixed with the last commit. Any chance this would be merged soon? I'd like to work on a follow-up PR.

> Still suboptimal in that it freezes resizing below the given threshold.

Hm, you mean it's suboptimal as is? To my understanding, we need to freeze it while switching handles going negative (ex. "e" -> "w"), unless we introduce a new UI (https://github.com/excalidraw/excalidraw/pull/1475#issuecomment-618709800).

**Comment by dwelle** [comment]
> Hm, you mean it's suboptimal as is? To my understanding, we need to freeze it while switching handles going negative (ex. "e" -> "w"), unless we introduce a new UI (#1475 (comment)).

No. It was working fine once, as I said. Either way, there's nothing fundamentally preventing it, unless there was a major change to the way we handle it that I'm not aware of (possible).

**Comment by dai-shi** [comment]
> It was working fine once

I don't know how it's working at the point of #341, but as it's using only delta, it will loose the position when going negative size. Same as #1296 

> there was a major change to the way we handle it

So, #1330 rewrote the whole logic to base on the pointer position without delta.
But, because it has `offsetPointer`, it deals with #341 case.

678c750 is probably providing a better behavior than before. It freezes resizing while changing handles, but otherwise it will loose the position (= make gap between the pointer and the handle).

**Comment by dai-shi** [comment]
I guess I'm a bit confused with discussion points. Let me try listing them.

- Ideal UI
- The current resizing logic (position based, no delta)
- What prevents merging this PR

**Comment by dwelle** [comment]
Let's merge it, and we'll make this work more optimally later.

**Pull request merged**
