### PR TITLE
Some a11y fixes

### PR DESCRIPTION
**Pull request by voluntadpear**
WIP: Some accessibility improvements.

### CODE REVIEW

**Comment by dwelle** [comment]
Genuine question: is there a point to making a graphics editor accessible? Or maybe it's targeted at people with not-so-severe visual impairments?

**Comment by voluntadpear** [comment]
> Or maybe it's targeted at people with not-so-severe visual impairments?

That's right. There are some people that even though they are sighted they find using a screen reader and other assistive technology or changing the color contrast useful for them.

This PR also contain fixes for keyboard navigation.

**Comment by vjeux** [comment]
Why is it a draft? That looks good to be merged!

**Comment by voluntadpear** [comment]
Thank you! I'm adding some improvements around our modal dialogs to add focus traps and the corresponding roles. I'll open it afterwards 🙂

**Comment by vjeux** [comment]
I added one more small fix: https://github.com/excalidraw/excalidraw/pull/556

**Pull request merged**
