### PR TITLE
Adding more Arabic localization

### PR DESCRIPTION
**Pull request by Mzaien**
i was surprised by how awesome your web app is but did not find Arabic in it, it was under the threshold so i made more translation to make it appear

### CODE REVIEW

**Comment by dwelle** [comment]
Hey @Mzaien. Could you make the translation over at our [Crowdin localization service](https://crowdin.com/translate/excalidraw/10/en-ar)? Otherwise it'd cause integration issues with our workflow and conflict with other translations. Thanks!

**Comment by ad1992** [comment]
@Mzaien we use Crowdin for managing the translations, could you add the translations for Arabic [here](https://crowdin.com/translate/excalidraw/10/en-ar)? post that the pr will be raised by crowdin with the updated translations.

**Comment by Mzaien** [comment]
Oh Sorry i did not know about Crowdin, i've put the translated words in it
Thank you for helping @dwelle @ad1992

**Comment by ad1992** [comment]
Thanks @Mzaien, closing this.

**Pull request closed without merging**
