### PR TITLE
Extract Sidebar panels into separate components

### PR DESCRIPTION
**Pull request by GasimGasimzada**
Extract the following panels into their respective components:

* Tools -> Tool Selector
* PanelColor -> Stroke and Background Color picker picker
* Selection -> Bring forward etc buttons
* Canvas -> View background color and clear canvas
* Export -> All export functionality

Additional Housekeeping: added Jest TS types

### CODE REVIEW

**Comment by dwelle** [comment]
I was actually planning to put e.g. all export logic into one component. Is there a reason why to put view/controller (or whatever we want to call it) in separate files? Doesn't it go against react componentization model? Right now, if one wants to work on export, we need to go into `panelExport.ts`, and `data.ts`...

**Comment by GasimGasimzada** [comment]
For the time being, I have not touched the control flow of the application yet. I have just been extracting components in small increments without changing anything that might break what is currently working. That's why all the components have a lot of props in them as these components are "dumb." If you want, I can move exports into it now but I just want to let you know, I want to change some of the state related stuff and will be writing issues for discussing these changes.

**Comment by dwelle** [comment]
Let's leave like this, then. I'll be working with export, shortly, and will investigate putting all the export logic into the `panelExport.tsx` in that PR (unless you want to first make the state changes).

**Comment by GasimGasimzada** [comment]
You can work on it. No problem. Should I merge it now?

**Comment by dwelle** [comment]
Yes, whenever you're ready.

**Comment by GasimGasimzada** [comment]
Done! :)

**Pull request merged**
