### PR TITLE
Add numeric hotkeys

### PR DESCRIPTION
**Pull request by jillesme**
Hello!

I used excalidraw and I loved it. One thing I found counterintuitive is the hotkeys. I added functionality to make them work numerically, too!

### CODE REVIEW

**Comment by jillesme** [comment]
An extended clip to see how easy it is to draw using numeric hotkeys.

**Comment by vjeux** [comment]
Thanks, this is great!

**Comment by vjeux** [comment]
Could you move the line before the text one while you’re at it?

**Comment by jillesme** [comment]
@vjeux it seems like you just merged it, do you still want me to move the line before the text in this PR?

**Comment by vjeux** [comment]
Another PR :)

**Pull request merged**
