### PR TITLE
add explanation for why we mutate collaborators state

### PR DESCRIPTION
**Pull request by warrenseine**
This `setState()` didn't trigger any update.

### CODE REVIEW

**Comment by warrenseine** [comment]
This PR is clearly discussable, as it's not fixing any bug, but it looked like an anti-pattern.

**Comment by dwelle** [comment]
I agree that mutating state is a problem, and yes this technically doesn't work correctly.

That said, the fact mouse movement doesn't rerender UI is what we want for performance reasons, so this is a pickle.

Need to figure out what to do here.

**Comment by warrenseine** [comment]
It makes perfect sense. Maybe the `collaborators` Map itself shouldn't be in the state, only an ID list?

**Comment by dwelle** [comment]
> It makes perfect sense. Maybe the collaborators Map itself shouldn't be in the state, only an ID list?

Wouldn't help. As long as we'd pass it to UI for some reason (which we seems to be doing) it would rerender if we mutated.

I agree it's not ideal, but let's shelve it for now :).

Nevertheless, I've pushed a reverting commit that contains an explanation comment for future reference.

**Pull request merged**
