### PR TITLE
ci: Add jest coverage report and threshold of 65 is allowed

### PR DESCRIPTION
**Pull request by siddhant1**
fix https://github.com/excalidraw/excalidraw/issues/6553

### CODE REVIEW

**Comment by siddhant1** [comment]
@ad1992 Added the coverage package, there is a problem tho, we can't test this using a fork

Check this https://github.com/ArtiomTr/jest-coverage-report-action#forks-with-no-write-permission

We should be able to merge and test though

**Comment by ad1992** [comment]
@siddhant1 can you instead test it against your forked repo for this branch ? That way we will be sure that its working before merging it.

**Comment by siddhant1** [comment]
Hey sure @ad1992 sorry for not following this, let me quickly test and report back

**Comment by ad1992** [comment]
@siddhant1 any update ?

**Comment by ad1992** [comment]
closing in favor of https://github.com/excalidraw/excalidraw/pull/5237

**Pull request closed without merging**
