### PR TITLE
Extract app into its own module

### PR DESCRIPTION
**Pull request by GasimGasimzada**
This PR just moved app component into its own file; so that, it is clearer where the entrypoint and the app component it.

### CODE REVIEW

**Comment by GasimGasimzada** [comment]
Actually, now that I think about it, it is going to break other PRs by adding a lot of merge conflicts. How do you think we should proceed with this?

**Comment by vjeux** [comment]
It doesn't strike me as essential to rename it. So I'm happy keeping it that way. But if you believe it's worth it, then feel free to move and the people with the PR will have to rebase.

**Comment by GasimGasimzada** [comment]
Let's keep it for now. Once the App component is split into multiple pieces, then we can separate them :) I do not want existing PRs to suffer because of it.

**Comment by vjeux** [comment]
This has now become stale. Closing it, feel free to re-open it if you think that we should still refactor this part

**Pull request closed without merging**
