### PR TITLE
More mobile tweaks

### PR DESCRIPTION
**Pull request by j-f1**
Ref #138 

- [x] language selector
- [x] remove lock button on mobile

### CODE REVIEW

**Comment by dwelle** [comment]
> Now the elements property is not visible when inserting new elements.. [---comment](https://github.com/excalidraw/excalidraw/pull/788#issuecomment-589684065)

just putting it here so we don't forget

**Comment by j-f1** [comment]
Fixed in 171569a

**Comment by dwelle** [comment]
> Should I show the  button when creating a line in mobile mode?

I'd say yes. Also when any shape tool is selected, to align with previous behavior.

**Comment by dwelle** [comment]
And drop the `appState.elementType === "selection"`. I'll see if I can write some tests to guide it.

**Comment by j-f1** [comment]
I copied the heuristic from here but originally got it wrong:

https://github.com/excalidraw/excalidraw/blob/c2855e2cb829adce5748d07d76cd7f22e24aa79e/src/index.tsx#L285-L291

**Comment by vjeux** [comment]
The done button for drawing arrows seems to be off by one. It only shows after you have added three points instead of two. When you confirm, it drops the last segment of the arrow

**Comment by dwelle** [comment]
Yea, the menu should show for `selection` tool only if some element is selected.

As for the tests, can't figure out why they don't work (it's really hard to debug DOM-based tests in a console, which also use an emulated DOM) and I'm out of time right now :(.

**Comment by vjeux** [comment]
The lock icon doesn’t make much sense to me in the bottom menu. It feels like it’s part if the shape actions. Is there a reason why it’s not up there like on desktop?

**Comment by vjeux** [comment]
The language selector is missing. Should probably be located in the hamburger menu

**Comment by j-f1** [comment]
> The lock icon doesn’t make much sense to me in the bottom menu. It feels like it’s part if the shape actions. Is there a reason why it’s not up there like on desktop?

Not enough space on iPhone SE.

**Comment by vjeux** [comment]
There’s a small jump while dragging elements
- dezoom to the maximum (to make it more obvious)
- create a circle
- touch down on the edge with one finger
- move by one or two pixels
- the circle jumps to more than a few pixels
- move by one or two more pixels
- the circle properly tracks your finger

Usually when I see this kind of bugs, it’s an issue where we don’t keep track of the offset where the element was started being dragged and instead we use the center.

**Comment by dwelle** [comment]
I think we can drop the lock for mobile altogether, no? It's more of a power feature.

**Comment by vjeux** [comment]
Missing zoom indicator. The pinch to zoom gesture is awesome. However it’s very easy to zoom in and out to large or small zooms and then when exported to normal images the scene will be at the wrong scale.

I’m not really sure what’s the right way to deal with it but it’ll likely be an issue

**Comment by dwelle** [comment]
> Missing zoom indicator. The pinch to zoom gesture is awesome. However it’s very easy to zoom in and out to large or small zooms and then when exported to normal images the scene will be at the wrong scale.
> 
> I’m not really sure what’s the right way to deal with it but it’ll likely be an issue

Maybe add a `reset zoom` button in the corner when zoomed?

image

**Comment by vjeux** [comment]
The hamburger and edit buttons should be active (like lock) when opened

**Comment by vjeux** [comment]
(Just to be clear, I’m just posting here all the things I’m seeing around mobile support, they are not required to be addressed in this PR)

**Comment by dwelle** [comment]
Also, I've started getting the translate-this-page bug again (https://github.com/excalidraw/excalidraw/issues/595), in this PR only, I believe. Weird :thinking:

**Comment by vjeux** [comment]
- Select a circle
- Click the edit icon to show the edition menu
- Click on the scene
- The edition menu still shows up (with less controls)
- There is no longer an edit icon to toggle it off

Should we always keep the edit icon visible?

**Comment by dwelle** [comment]
Another weird thing: when viewing the Zeit NOW deployment on desktop, it's forced into mobile view in 100% zoom (what seems like). Can anyone repro that? Wouldn't want this to be happening from now forward.

https://excalidraw-avxyp0czn.now.sh/

**Comment by vjeux** [comment]
Just wanted to say again that this is awesome. I’ve been drawing a quick scene and it works very well on my iphone 6!

I knew it had potential but it’s exceeding my expectations!

**Comment by j-f1** [comment]
> There is no longer an edit icon to toggle it off

Fixed.

> The done button for drawing arrows seems to be off by one. [...] When you confirm, it drops the last segment of the arrow

If you use the mouse to click two segments, then move to a third point without clicking, then hit enter, you’ll see the same thing. Not sure how to resolve it.

**Comment by dwelle** [comment]
> > The done button for drawing arrows seems to be off by one. [...] When you confirm, it drops the last segment of the arrow
> 
> If you use the mouse to click two segments, then move to a third point without clicking, then hit enter, you’ll see the same thing. Not sure how to resolve it.

That's a different thing with the mouse. The last point isn't committed yet, so it's correct that upon confirm it's discarded.

**Comment by j-f1** [comment]
`actionFinalize` removes the last point from the multi-point object it’s passed. This is because when you click with a mouse, another segment is automatically added that follows the cursor. How can I reconcile these two behaviors?

**Comment by dwelle** [comment]
I guess conditionally  remove the last point only if not on mobile.

**Comment by j-f1** [comment]
I’m also thinking of cases like Windows laptops where you might lay points down with a mouse or touch.

**Comment by j-f1** [comment]
I think the best option would be to record the pointer the most recent point was laid down with and only remove it if the pointer is a mouse. How would I store that so the finalize action can access it but it isn’t permanently stored in the document?

**Comment by j-f1** [comment]
> There’s a small jump while dragging elements

I can’t reproduce this on an iPhone 8 or simulated iPhone 11.

**Comment by dwelle** [comment]
> I think the best option would be to record the pointer the most recent point was laid down with and only remove it if the pointer is a mouse. How would I store that so the finalize action can access it but it isn’t permanently stored in the document?

I haven't checked the code. Yes, the best way is to identify whether you're in the created-temp-arrow-point mode and act on that.

**Comment by j-f1** [comment]
This might also be related to the fact that tapping once to start a line actually creates two points.

**Comment by vjeux** [comment]
Is this in a state to be merged in? If yes, we should probably do it and continue support in a follow up.

**Comment by lipis** [comment]
ZcP51VCV

Strange focus border when tapping on hamburger menu on Pixel 4..

**Comment by j-f1** [comment]
@lipis Weird — I can’t repro on iOS. I’ll try to use an Android emulator in the future, but I suspect it’ll be fixed by switching those buttons to be radio buttons, which I plan to do as part of a future refactor.

**Comment by j-f1** [comment]
Good to go @vjeux — I moved the incomplete tasks back to the issue.

**Comment by vjeux** [comment]
I disagree that the mobile UI should have less features because it’s on a phone. I use the lock icon a lot when drawing shapes with a bunch of lines. I wish we didn’t totally remove it as it’s useful.

I’m happy for it being behind a menu.

**Pull request merged**
