### PR TITLE
Remove eslint-plugin-json-format

### PR DESCRIPTION
**Pull request by lipis**
No need for that.. we format then using Prettier

### CODE REVIEW

**Comment by dwelle** [comment]
It's not for formatting, but for JSON validation. E.g. it guards against duplicate keys.

**Comment by lipis** [comment]
Right.. still I don't see it that useful.. less is more :) wdyt?

**Comment by dwelle** [comment]
Why didn't you bring it up when we were discussing it in https://github.com/excalidraw/excalidraw/pull/502? What changed?

**Comment by lipis** [comment]
Right.. didn't pay too much attention to it and was investigation yesterday maybe adding more ESLint rules and noticed this plugin.. So on a second thought I think we are still good without it.. It's not that common to have mistakes in JSON files.. the editors are doing good job showing the errors.

**Comment by dwelle** [comment]
Ok. But, you missed removing `json` filetype for `eslint` from `.lintstagedrc.js` (surprising it let you commit it).

**Pull request merged**
