### PR TITLE
Support different color inputs

### PR DESCRIPTION
**Pull request by warrenseine**
Implementation proposition for #1478.

### CODE REVIEW

**Comment by vjeux** [comment]
Nice trick to use canvas to normalize the color!

**Comment by vjeux** [comment]
This now allows `rgba(x, y, z, 0.2)` form which allows you to have transparent background. We hardcoded `transparent` to draw a full solid background in order to avoid having "motion blur" effects. But it no longer work for rgba variant. I was able to generate cool pictures like this:

image

I kinda like this bug to be honest, but if you feel like fixing it that would be great. Code is here https://github.com/excalidraw/excalidraw/blob/6771b505ad580037cd3c310086c2742b85dbed4d/src/renderer/renderScene.ts#L115-L121

**Comment by warrenseine** [comment]
Allowing `rgba()` was not my intention. I expected the canvas to normalize everything to hexadecimal, but forgot about the transparency case. Would you prefer that we support `rgba()`, and therefore add a new condition `sceneState.viewBackgroundColor.startsWith('rgba')`, or just reject the color by returning `null` from my normalization code?

I'll implement the first one, but tell me if you prefer avoiding this case.

**Comment by warrenseine** [comment]
(And yes, we really need a hidden toggle to keep this motion blur effect!)

**Comment by vjeux** [comment]
I don’t really care which way. You should probably also test for hsla and figure out if there are other variations from the css spec

**Comment by warrenseine** [comment]
Ok, thanks for the tip to check the spec. CSS4 introduces [new syntaxes](https://developer.mozilla.org/en-US/docs/Web/CSS/color#Specifications) I don't want to deal with. I'll just make sure normalization only returns opaque `#` values.

**Pull request merged**
