### PR TITLE
Rotation constraint on mobile (except for two-point lines/arrows)

### PR DESCRIPTION
**Pull request by dai-shi**
My idea for #1351

### CODE REVIEW

**Comment by dai-shi** [comment]
@mapbakery Hi, you can try this and see how you feel.

**Comment by dai-shi** [comment]
exdraw24

**Comment by mapbakery** [comment]
That works for boxes and for text (I think) but for lines it doesn't work, there is no center to go to (and there is no rotate handler on lines)

**Comment by lipis** [comment]
Interesting approach.. It should work only on mobile that way.. right?

**Comment by dai-shi** [comment]
Yes, mobile only.

**Comment by dwelle** [comment]
For lines, we'll need to implement rotation handle, anyway. So what about showing 2 handles on mobile?

image

Not sure about the lock icon.

**Comment by lipis** [comment]
Too many handles.. especially on mobile you want to have less..

**Comment by dwelle** [comment]
That's true. Bot for lines this PR's solution wouldn't work :(.

**Comment by mapbakery** [comment]
Two handles would be fine for me, I don't have objections against the additional handle. Perhaps it's good to  use the handle with the lock icon for bigger rotation steps like 22.5 degrees

**Comment by dai-shi** [comment]
For @mapbakery use case, rotating lines won't help, I presume.

**Comment by mapbakery** [comment]
Yes, it would help

**Comment by dwelle** [comment]
Is it hard to implement this solution: start rotating, and then place 2nd finger anywhere on the screen and rotate with 2 fingers to apply step-wise rotation. (would need a hint, for sure).

**Comment by dai-shi** [comment]
I'm positive to have all resize handles + rotation handle for 2-points lines/arrows. I know it's redundant, but it seems consistent.

**Comment by dai-shi** [comment]
Here's the thing: The original issue was about 2-point lines/arrow, which this PR doesn't solve. However, this PR approach works for all other shapes: rectangles, diamonds, ellipses, curved lines and texts. This feature is almost harmless, because you can not precisely rotate around the center anyway. If users are used to this feature, they can rotate widely and then narrows to the center to lock the angle. The center area could be a little bigger, but the current one is acceptable (and harmless). How do you guys think?

**Comment by mapbakery** [comment]
I agree, and it's useful for me!

**Comment by dai-shi** [comment]
@dwelle pls check this, whenever you get time

**Comment by vjeux** [comment]
I'm not a fan of this. We shouldn't arbitrarily restrict what we can do on mobile. I would try to find a way to emulate the shift behavior that makes sense with mobile-friendly controls.

**Comment by dai-shi** [comment]
I think if one wants to have the angle constraint, they always want it. If that's the case, it would be better to provide a global config. Same would apply for grid constraint.

**Comment by mapbakery** [comment]
My original request was some kind of config setting. In my case, for transit map sketches) I will always use the same (45 degrees) angle constraints for everything. So I'm also happy with the 22.5 degrees steps, to keep it consistent with how it works when using the SHIFT key normal devices.

**Comment by dai-shi** [comment]
Let me close this. I agree to look for more explicit ways.

**Pull request closed without merging**
