### PR TITLE
feat: pass current `theme` when installing libraries

### PR DESCRIPTION
**Pull request by dwelle**
for https://github.com/excalidraw/excalidraw-libraries/pull/106

Can be merged in any order.

### CODE REVIEW

**Review by h7y — COMMENTED** [review]
Why not pass only the `theme` as prop?

**Comment by dwelle** [comment]
> Why not pass only the `theme` as prop?

We'd have to have two separate `theme` props and I think it doesn't make much sense to make the excalidraw component be in a different theme than the library. If such requests come in, we can reconsider later.

**Comment by h7y** [comment]
> > Why not pass only the `theme` as prop?
> 
> We'd have to have two separate `theme` props and I think it doesn't make much sense to make the excalidraw component be in a different theme than the library. If such requests come in, we can reconsider later.

Oh I think I didn't put it well. What I meant it is why not pass just `theme={appState.theme}` to `LibraryMenuItems` instead of passing the entire `appState`.

**Comment by dwelle** [comment]
> Oh I think I didn't put it well. What I meant it is why not pass just `theme={appState.theme}` to `LibraryMenuItems` instead of passing the entire `appState`.

I somehow dropped the `only` when I read it, so my bad.

Mhm, good point — I forgot `this.state` is immutable, so doesn't retain referential integrity.

**Pull request merged**
