### PR TITLE
fix: Hide scrollbars on mobile

### PR DESCRIPTION
**Pull request by h7y**
There seems to be another issue. On Firefox, The scrollbars render by default (mobile & desktop) even on an empty canvas. Is this known?

Resolves:
#2923

### CODE REVIEW

**Comment by h7y** [comment]
The package build seems to be failing because there are no loaders to process .scss file which is being used in `src/is-mobile`. I'm using the `isMobile` function from that file to decide whether to render the scrollbars. Should I go ahead and add a loader?

**Comment by h7y** [comment]
> 
> 
> The package build seems to be failing because there are no loaders to process .scss file which is being used in `src/is-mobile`. I'm using the `isMobile` function from that file to decide whether to render the scrollbars. Should I go ahead and add a loader?

Hey @ad1992, any thoughts on this? :)

**Comment by ad1992** [comment]
> > The package build seems to be failing because there are no loaders to process .scss file which is being used in `src/is-mobile`. I'm using the `isMobile` function from that file to decide whether to render the scrollbars. Should I go ahead and add a loader?
> 
> Hey @ad1992, any thoughts on this? :)

We should ideally not need any scss loaders for `@excalidraw/utils` but right now since `exportToCanvas` uses `renderScene` and with this change, it's trying to load the variable from scss file for which loader is not defined.

So there are two ways
1. We add the loader if we want to allow the import from scss files so we still maintain consistency but with an additional loader.
2. We copy the variables in js to avoid this but the consistency will go off.

We can go with `1` as there can be these kinds of cases in future as well where we are reading from scss file and using it in utils unless we find a better solution.

@dwelle what do you think?

@h7y can you check whats the increase in bundle size after adding the loader? 

Also the `open-color/open-color.scss` should not get bundled since its not used anywhere in `is-mobile`.

**Comment by dwelle** [comment]
We shouldn't use `isMobile()` in `renderScene()` at all. We're already passing a convenient `options.renderScrollbars`, so let's use that.

**Comment by h7y** [comment]
I've made `_isMobile` a class variable to avoid a function call on every update to the component. Let me know if that's okay.

**Comment by dwelle** [comment]
Setting the value on construction won't catch updates. We have 2 options:

1. keep reading it on every update
2. set up an event listener in `componentDidMount` and remove on `componentWillUnmount`

I think we can get away with (1) coz from what I've tested it's super fast.

(Also, no need to prefix with `_` since we don't do that with other component props either.)

**Comment by h7y** [comment]
Is this fine? :)

**Comment by dwelle** [comment]
Yea, it's good, we can optimize later :). Thanks!

**Pull request merged**
