### PR TITLE
don't use unicode characters for shortcut help

### PR DESCRIPTION
**Pull request by dwelle**
fixes https://github.com/excalidraw/excalidraw/issues/1557

I used `Cmd` instead of `Command` because the long form is not used very often, and takes too much space.

### CODE REVIEW

**Comment by lipis** [comment]
While we at it.. the Japanese version of the shortcuts has some issues :)
Screenshot 2020-05-09 at 8 09 14 PM

**Comment by lipis** [comment]
Could be a separate issue if it's not an easy fix

**Comment by dwelle** [comment]
I tweaked the layout, and also made the dialog bigger by 100px so more fits in.

# before

Japanese

image

Arabic

image

# after

Japanese

image

Arabic

image

**Comment by vjeux** [comment]
Thank you!

**Pull request merged**
