### PR TITLE
Center element on paste

### PR DESCRIPTION
**Pull request by Fausto95**

### CODE REVIEW

**Comment by Fausto95** [comment]
This is not perfectly centered, but it should work!
@vjeux

**Comment by dwelle** [comment]
Did you close this unmerged intentionally? (Also, it doesn't seem to work in the preview deployment... maybe that's an older commit?)

**Comment by Fausto95** [comment]
Should work now

**Comment by dwelle** [comment]
Ok, I've been testing the `Cmd/Ctrl+V` variant (didn't know the implem differs). Should the hotkey implem default to (visible) canvas center?

**Pull request closed without merging**
