### PR TITLE
[WIP] Add node worklow

### PR DESCRIPTION
**Pull request by giovannigiordano**

### CODE REVIEW

**Comment by vjeux** [comment]
Omg, a CI system!! <3

**Comment by nanot1m** [comment]
Have we moved `from` yarn to `npm`?

**Comment by giovannigiordano** [comment]
> Have we moved from `yarn` to `npm`?

Yep, I firstly committed yarn.lock, but to avoid usage of a Github Action with Yarn i would prefer to use npm

**Comment by giovannigiordano** [comment]
@vjeux we want to deploy on each merge on master?

**Comment by vjeux** [comment]
I think so. At least in the early life of the project where we’re iterating super quickly

**Comment by giovannigiordano** [comment]
@vjeux for the deploy instead of adding a step, we need to set master as the source branch for github pages, so it will automatically grab new content from the source branch.

**Comment by vjeux** [comment]
How would that work by pointing it to master? The build step downloads everything from npm, runs webpack on-top of it to generate a single js file...

**Comment by giovannigiordano** [comment]
> How would that work by pointing it to master? The build step downloads everything from npm, runs webpack on-top of it to generate a single js file...

Sorry, you are right! I am a stupid 👍

**Comment by giovannigiordano** [comment]
@vjeux This is ready to be merged. When merged we have to check if everything is ok on the website.

**Comment by vjeux** [comment]
Go for it :)

**Pull request merged**
