### PR TITLE
feat: initial Laser Pointer MVP

### PR DESCRIPTION
**Pull request by are**
fix https://github.com/excalidraw/excalidraw/issues/5351

(work in progress)

### CODE REVIEW

**Comment by vpzomtrrfrt** [comment]
The referenced `@are/laser-pointer` package links to a private or missing repository (and also uses a different package name in the readme?)

**Comment by are** [comment]
@vpzomtrrfrt that was a temporary package, we migrated it to `@excalidraw/laser-pointer` (it should be cleaned up of old names). The source repository is private for the moment, but its under Excalidraw organization.

**Review by dwelle — APPROVED** [review]
🎉🚀

**Comment by vpzomtrrfrt** [comment]
And the dependency is... still private? Or have I just missed it?

**Comment by dwelle** [comment]
@vpzomtrrfrt private for now until we iron it out. Will be made public soon!

**Comment by ad1992** [comment]
Please make sure the size limit is updated when the PR breaks it, this PR increased the size of the bundle by ~6kb but it wasn't updated 🙏
cc @dwelle @are

**Comment by dwelle** [comment]
@ad1992 will make the check useless — it should keep bothering us to do something about it :).

**Pull request merged**
