### PR TITLE
feat: Change shortcuts menu to help menu

### PR DESCRIPTION
**Pull request by inwardmovement**
### [Preview](https://excalidraw-git-fork-inwardmovement-update-help-menu.excalidraw.now.sh/)

Fixes https://github.com/excalidraw/excalidraw/issues/2785

I don't know React but I tried.

Can I leave you change `ShortcutsDialog` to `HelpDialog`? I had a hard time with all the files/class names etc. and I messed up so I restarted without touching to naming.
Also I spotted some "shorcuts" names (with typos) here and there.

Help icon from [Bootstrap](https://icons.getbootstrap.com/icons/question-square-fill/).

### CODE REVIEW

**Comment by inwardmovement** [comment]
Maybe we could add documentation/guides as sections above shortcuts?

**Comment by lipis** [comment]
I updated more things.. But still not super happy about the design.. any thoughts? /cc @dwelle

**Comment by lipis** [comment]
@inwardmovement good idea.. added.

**Comment by inwardmovement** [comment]
> @inwardmovement good idea.. added.

I was thinking to directly show guides:

image

**Comment by dwelle** [comment]
1. let's use FontAwesome icons since that's what we use whenever possible. This one looks good: https://fontawesome.com/icons/question-circle?style=solid
2. I'd personally drop the first header. Looks cleaner.

	image

	image

**Comment by ad1992** [comment]
can we move the keyboard shortcuts to the top and move the rest to the footer? Also, the header `Help` might not be needed.

Excalidraw

**Comment by lipis** [comment]
> can we move the keyboard shortcuts to the top and move the rest to the footer? Also, the headers `Help/Support` might not be needed. Thoughts?

That's what we had before.. we want to promote the reset as well and to have a general thing.

**Comment by lipis** [comment]
> I was thinking about directly showing guides:

Maybe in an another PR.

**Comment by lipis** [comment]
@inwardmovement will you update the icon?

**Comment by inwardmovement** [comment]
> @inwardmovement will you update the icon?

Ok

**Comment by lipis** [comment]
Thanks @inwardmovement

**Pull request merged**
