### PR TITLE
Reintroduce multi-point arrows and add migration for it

### PR DESCRIPTION
**Pull request by GasimGasimzada**
- Convert old arrow format to new one
- Additionally, add failchecks for all point logic

Migration for: #338 #634

### CODE REVIEW

**Comment by dwelle** [comment]
Where's the base commit? :)

**Comment by GasimGasimzada** [comment]
https://github.com/excalidraw/excalidraw/issues/633 Also, we need to investigate this one, right?

**Comment by dwelle** [comment]
> #633 Also, we need to investigate this one, right?

Yes. Need to repro first.

**Comment by GasimGasimzada** [comment]
Thank you @dwelle for the help with GIT. If you check the deployment, currently old arrow spec (where there is no `points` array) gets converted to `points`. Here is an example JSON that you can test this on:

```
{
  "type": "excalidraw",
  "version": 1,
  "source": "https://excalidraw.com",
  "elements": [
    {
      "id": "X6IucAVRpr1aVAmO5KDec",
      "type": "arrow",
      "x": 767,
      "y": 457,
      "width": 240,
      "height": -133,
      "strokeColor": "#000000",
      "backgroundColor": "transparent",
      "fillStyle": "hachure",
      "strokeWidth": 1,
      "roughness": 1,
      "opacity": 100,
      "seed": 245146242
     }
  ],
  "appState": {
    "viewBackgroundColor": "#ffffff"
  }
}
```

**Comment by GasimGasimzada** [comment]
Both retina display issue and migration have been resolved! :) I am still going to investigate why identity matrix breaks in retina display

**Comment by dwelle** [comment]
status: DO NOT MERGE. There are some edge cases we want to fix, tomorrow.

**Comment by lipis** [comment]
While we are on.. don't we want the same behaviour with the line?

**Comment by dwelle** [comment]
Yes. I reckon we'll do that in a next PR, but we'll see.

**Comment by GasimGasimzada** [comment]
@dwelle @lipis I have some ideas about that. I will create an issue after multi-point arrow.

**Comment by GasimGasimzada** [comment]
I set up fail safes in `restore`. Please someone review and see if there is an issue. So far, I haven't found any (tried different combinations of JSON file to see what can happen).

**Comment by GasimGasimzada** [comment]
Merged!

**Comment by vjeux** [comment]
Omg omg omg! We need to celebrate :)

**Comment by voluntadpear** [comment]
Congrats @GasimGasimzada 🎉 🎉 great work on this!

I think we have to find a way to make this feature more discoverable. People that don't know about this support might never find out ;)

**Comment by dwelle** [comment]
@voluntadpear maybe #335?

**Pull request merged**
