### PR TITLE
Update to rough.js 4.0.1

### PR DESCRIPTION
**Pull request by pshihn**
* Support built in seeding
* Render order changed to resolve https://github.com/excalidraw/excalidraw/issues/211
* Related issue: https://github.com/excalidraw/excalidraw/issues/362

### CODE REVIEW

**Comment by dwelle** [comment]
Very cool.

One problem I noticed this introduced: the ellipse's outline doesn't quite match the bg & our bounding box.

image

Is that a problem on our side?

**Comment by pshihn** [comment]
@dwelle  this was not introduced, but always existed. It's part of the sketchiness where fills go out the lines. It looks more uniform in circles than polygons. It just depends on what random seed gets used. I will create an issue to make it more random for circles.

**Comment by pshihn** [comment]
@dwelle I do notice this more now as well... I will resolve this sometime today! Thanks for bringing this up

**Comment by dwelle** [comment]
@pshihn you're right, it existed even before, and was as much pronounced, if not more (I just didn't notice it for some reason). WTBS, in 4.0 the ellipse's outline is almost always smaller than the bg/bounding-box, while it doesn't need to be since it's remarkably uniform already (as is the bg).

**Comment by pshihn** [comment]
Yep, I have created an issue in rough to track this: https://github.com/pshihn/rough/issues/123
I don't like what it's doing right now. I'll have something today or likely by tomorrow.

**Comment by pshihn** [comment]
Turns out the fix for this was super easy, all I needed was a fresh look. 
And as a bonus, it reduced the build size of rough.js as well ;)
Will release after some testing :)

**Comment by matias-capeletto** [comment]
This is awesome! Thanks a lot @pshihn!

**Pull request merged**
