### PR TITLE
refactor: :recycle: wrapText

### PR DESCRIPTION
**Pull request by ignacio-cuadra**
wrapText refactor

- [x] Refactoring for better readability
- [x] Check and update tests (only if is necessary)
- [x] Improve performance

___

About the tests, i think that is necessary redefine them (like i did on the original PR), for example:

**current test:**
Test wrapText › When text contain new lines › should respect new lines and break all words when width of each word is less than container width
**for this input:**
```
Hello
whats up
```
**and this width:**
`90 (80 without padding)`
**the current expected result is:**
```
Hello
whats
up
```
**But, if each letter has width of 10, then:**
```
Hello = 50
whats = 50
 (space) = 10
up = 20
```
**then:**
`whats + (space) + up = 50 + 10 + 20 = 80`
`80 <= 80 = true!`
**the correct result must be:**
```
Hello
whats up
```
(that is my result)

### CODE REVIEW

**Comment by ignacio-cuadra** [comment]
Performance log
```
{
  text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, \n' +
    'sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. \n' +
    'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
  maxWidth: 10,
  loops: 50000
}
```
old wrap text: 975.995ms (before PR)
new wrap text: 6.351s (before last commit)
optimized wrap text: 1.777s (after last commit)

(this is a reminder note)

**Comment by ignacio-cuadra** [comment]
```
{
  text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, \n' +
    'sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. \n' +
    'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
  maxWidth: 10,
  loops: 50000
}
```
optimized wrap text (wip): 1.110s (second optimization)
old wrap text: 914.679ms (before PR)
optimized wrap text v1: 1.638s (first optimization)
new wrap text: 6.321s (before optimization)

**Comment by ignacio-cuadra** [comment]
```
{
  text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, \n' +
    'sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. \n' +
    'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
  maxWidth: 10,
  loops: 50000
}
```
master: 966ms | getLineWidth calls 2,050,023
third optimization (current): 1,141ms | getLineWidth calls 7,500,000
second optimization: 1,167ms | getLineWidth calls 21,700,000
first optimization: 1,959ms | getLineWidth calls 27,900,000
before optimization: 6,201ms | getLineWidth calls 27,900,000

**Comment by ignacio-cuadra** [comment]
I think that I finished this (unless I have to update the tests).
@ad1992 
Can you review this PR?

**Comment by ad1992** [comment]
@ignacio-cuadra Sorry about the delay, I have been busy making some changes to the way the text wrapping works to make it more stable, also adding more tests, and monitoring to make sure all is good. I still have a few open PRs which I will be merging very soon (some of them are touching the wrap algo as well).

As this PR is mainly refactoring so it can wait (Once text containers are completely stable we can come back to this but for now it would be better not to introduce any code change which is not necessary atm)

But since you were working on a bug fix about fixing the spaces thing, I wanted to ask you if you could do it above the current master code ?
If that can be done, then we can merge that fix and It would help us release the fix soon.

**Comment by ad1992** [comment]
> Yes, I can do it but that feature removes all trailing spaces (I mention it because it would be necessary to remove them in the tests).

Yep that's what we ultimately want and that would be anyways needed to update in the test so its completely fine

**Comment by ignacio-cuadra** [comment]
Oops, i'm wrong. I meant that this feature doesn't remove any trailing space (They are removed when the text is drawing).

**Comment by ad1992** [comment]
> Oops, i'm wrong. I meant that this feature doesn't remove any trailing space (They are removed when the text is drawing).

That would be when you fix the bug of spaces right? which you would be doing in a new PR as discussed on top of the master's code?

**Comment by ad1992** [comment]
@ignacio-cuadra been long time so wondering if you are working on the trailing space fix or should I pick it up ?

**Comment by Mrazator** [comment]
Just noticed this! Looks much better, though we went in the end for a full rewrite as part of CJK support. Hence closing in favor of https://github.com/excalidraw/excalidraw/pull/8530.

**Pull request closed without merging**
