### PR TITLE
chore(i18n): update zh-TW translations

### PR DESCRIPTION
**Pull request by huang47**
## before
image

## after

image

### CODE REVIEW

**Comment by dwelle** [comment]
Hello @huang47. As per readme, we're using Crowdin for translating. Can you please made those over there? https://crowdin.com/translate/excalidraw/10/en-zhtw

@lipis or can we merge this as is?

**Comment by huang47** [comment]
sure thing, will do it on crowdin!

**Comment by huang47** [comment]
I gonna close this PR in favor of Crowdin

**Comment by lipis** [comment]
Thanks!

**Pull request closed without merging**
