### PR TITLE
Automatically change brush color when joining a live-collaborative session

### PR DESCRIPTION
**Pull request by warrenseine**
Implement #1869 and #1868.

### CODE REVIEW

**Comment by warrenseine** [comment]
Can we merge it?

**Comment by dwelle** [comment]
Forgot about this. My concern is that the main use case when collaborating is to actually collaborate on the scene, in which case making everyone use a random color will not be useful. And since we don't have an easy way to reset to defaults, it'll add unnecessary friction (even if we did).

Another point is that by setting background color you're actually changing our default behavior which is for shapes to have no background color at all.

**Comment by warrenseine** [comment]
> Another point is that by setting background color you're actually changing our default behavior which is for shapes to have no background color at all.

That wouldn't be a problem for me to change this behavior and only change the stroke.

> Forgot about this. My concern is that the main use case when collaborating is to actually collaborate on the scene, in which case making everyone use a random color will not be useful. And since we don't have an easy way to reset to defaults, it'll add unnecessary friction (even if we did).
> 
> In other words this PR makes an assumption that collaboration scenes should be very different from regular scenes in terms of looks and behavior.

I understand. That's indeed a significant change. What about an opt-in checkbox "☑️ Assign a different brush color to each participant" in the "Share a live-collaboration session" popin?

**Comment by dwelle** [comment]
> What about an opt-in checkbox "ballot_box_with_check Assign a different brush color to each participant" in the "Share a live-collaboration session" popin? That was actually part of my initial proposition: #1869.

I'd rather avoid adding more UI and focus on sensible defaults.

I'm having trouble finding a real use case for this, apart from when you use Excalidraw for chatting and you want to distinguish which text was created by which person. Apart from that, what does it matter what rectangles/diagrams were created by who? Doesn't it somewhat go against collaboration principles, where many people collaborate and modify the same diagram? I assume you don't want a given shape to consist of many different colors...

**Comment by lipis** [comment]
On a second thought, I think agree with @dwelle.. while it's a good idea..maybe it's going to bring some confusion to new people that are joining the room.. (I also haven't use the collaboration in depth in real life).

**Comment by warrenseine** [comment]
> I'd rather avoid adding more UI and focus on sensible defaults.

I'd love to have this feature as a default 😉 

> when you use Excalidraw for chatting and you want to distinguish which text was created by which person

That's exactly my use case. Team retrospectives. I can also see it used for interviews. In a physical whiteboard room, I usually choose a different pen color than the interviewee.

> Doesn't it somewhat go against collaboration principles, where many people collaborate and modify the same diagram? I assume you don't want a given shape to consist of many different colors...

Well, that's not how it works at the moment either. If I build a red rectangle and someone joins the room to add another rectangle, it'll be black unless the collaborator manually changed their color. I agree _most of the time_ the diagram will be black, and it'll work out, but that's a pretty opinionated assumption of Excalidraw collaborative use cases.

I honestly feel like the current system is incorrect, as avatars have meaningless colors. You should see the confusion of coworkers trying to write in red with a blue avatar, while others did the opposite.

An alternative would be to dynamically change the color of the avatar based on the current chosen stroke color. That could be a bit confusing too if collaborators are frequently changing color, but in my use case at least, it's ok.

**Comment by dwelle** [comment]
Mhm, while I'm still not convinced (as are not some of the team members --- but some are so it balances out I guess), if the PR changes only the stroke color as discussed (so that it doesn't change the app default behavior), then we can ship this and see how people react to it.

I'll do a final review of the code once you make the change, if you agree.

**Comment by xixixao** [comment]
Here's the choices I see (with one new idea):

1) Don't make any changes
2) Add viewer's avatar.
  a) As the session leader, write on your board (or tell people) "Please choose the color of your avatar so we can tell who's who"
  b) If a viewer clicks on their avatar, it sets the stroke color to the color of the avatar (**new idea** I think)
3) Give an option when creating the session to automatically assign stroke color
4) Automatically change the stroke color for every session

|   | Pros | Cons |
| ------------- | ------------- | ------------- |
| 1 No changes  |  No added complexity  | The use case is practically infeasible |
| 2a Avatar | UI change feels harmless | Can run out of colors, matching colors is hard, needs coordination (hard to discover) | 
| 2b Click to assign | UI change feels harmless | needs coordination (hard to discover) | 
| 3 Session option | Fully automatic | Adds complexity in one of the worst parts | 
| 4 Automatic | Fully automatic | Might be surprising, annoying for people who don't want it |

I think 4 is bad. 3 is palatable, but feels like something we shouldn't start with. Hence I'd start with 2b (being strictly better than 2a), and escalate from there. From 2b I'd either go to 3 or back to 1.

**Comment by dwelle** [comment]
Ad (2.b) --- if that works only for your own avatar then that's fine. But this would be a very cryptic feature (and you might misclick on your avatar when clicking on others and end up with changing your colors).

**Comment by warrenseine** [comment]
That’s very cryptic indeed. Not only that but it would be extremely confusing as clicking on avatar currently follows cursors.

If that’s not an explicit opt-in feature, I’d prefer not to implement it at all. As long as I can see my own avatar (that’s one of the commits in this PR), I can select my own color to match it.

I could propose to add an option to select my avatar color from the color picker, but I’d understand if you said it’d clutter the interface.

**Comment by xixixao** [comment]
What about making those actions explicit and distinguishing the viewer avatar?

Screen Shot 2020-08-10 at 19 23 40

If we add the viewer avatar with the viewer color, we need an action on it anyway, no? (and the distinguishing) Otherwise it's still gonna be weird nothing happens?

But if you're ok with just showing the avatar and letting users select the color manually we can skip the separate action (2a).

--- 

I also thought of this (with the tooltips being persistent ala dropdown menus, not like the tooltips now, so you can select the text from them):

Screen Shot 2020-08-10 at 19 27 07

but I think selecting the stroke color on click is easier, and you can copy the color from there (and there isn't much utility in having the other people's color codes).

**Comment by dwelle** [comment]
> If we add the viewer avatar with the viewer color, we need an action on it anyway, no? (and the distinguishing) Otherwise it's still gonna be weird nothing happens?

The idea is not adding the author's avatar at all (if there's no utility in doing so).

I don't hiding this behavior under avatar clicking is a good idea in general.

We should consider this PR proposal on its own merits --- if it does make sense, let's either make it the default, or add an opt-in checkbox to the collab dialog. If it doesn't make sense, don't half-commit by implementing it under a non-intuitive, hidden workflow.

**Comment by warrenseine** [comment]
I believe that, even without this PR, I'd still make sense to showing oneself in the collaborator list. It's the default in most collaborative software.

As I said before, I'd be fine not implementing this color change as long as I can see myself in the list. It would require telling my collaborator to pick their own color at the beginning, but I can live with that.

**Comment by dwelle** [comment]
I know I was the one to say adding a checkbox is adding complexity, but maybe it's not so bad?

excal_pick_collab_color

**Comment by lipis** [comment]
> I know I was the one to say adding a checkbox is adding complexity, but maybe it's not so bad?

That's a very nice solution!

**Comment by warrenseine** [comment]
Ok, I'm on it. I'd like to discuss the text as "Set stroke color to my avatar color" does not explain that it'll change new collaborators' color too.

What about "☑️ Match main color with avatars"? Or "☑️ Use a different color for each collaborator"? Any variant?

**Comment by dwelle** [comment]
> Ok, I'm on it. I'd like to discuss the text as "Set stroke color to my avatar color" does not explain that it'll change new collaborators' color too.

It doesn't, it changes just your color. Also, I have a WIP implem so let's not duplicate effort. And finally, I'm not sure if we're in agreement for this implem.

**Comment by warrenseine** [comment]
Ok, the feature doesn't seem very useful if the room creator can't set this as the default.

**Comment by dwelle** [comment]
Ok, since this seems to be controversial (no consensus reached) and we can't do the checkbox thing until we implement #1878, I say we close this for now (and keep the original issue open) and revisit when the persisted rooms are implemented.

**Pull request closed without merging**
