### PR TITLE
remove remote pointers on client disconnect

### PR DESCRIPTION
**Pull request by dwelle**
fix for https://github.com/excalidraw/excalidraw/issues/910

The backend PR is at https://github.com/excalidraw/excalidraw-room/pull/5

### CODE REVIEW

**Comment by idlewinn** [comment]
Awesome! What do you think about having `client-disconnected` also pass the number of users in the room so we don't have to send two broadcasts? better perf, slightly less intuitive

**Comment by vjeux** [comment]
Haha, I asked a very similar thing on the other repo: https://github.com/excalidraw/excalidraw-room/pull/5#discussion_r391290407

**Comment by dwelle** [comment]
Yes, it is suboptimal. Will fix it tomorrow, if it's not in a rush. Or you can tweak it yourselves, should be a quick fix.

**Comment by dwelle** [comment]
Updated to consolidate events and make more robust as suggested.

Changes:

- removed `appState.remotePointers` & `appState.collaboratorCount` in favor of `collaborators` -- a map of collaborators which contains `pointer` object. To check count, we'll do `appState.collaborators.size`.

**Comment by dwelle** [comment]
This can probably be merged as it shouldn't cause breaking changes even if the server-side isn't deployed, it just won't work. That said, we should merge that one, too: https://github.com/excalidraw/excalidraw-room/pull/5

**Pull request merged**
