### PR TITLE
improvement: Add language separator and list English twice

### PR DESCRIPTION
**Pull request by lipis**
Now that we have too many maybe it's a good idea to add a separator and list English in the alphabetical order as well for easier search on Mobile..

Screenshot 2021-01-07 at 5 29 39 PM

### CODE REVIEW

**Comment by dwelle** [comment]
:+1: I hate it when I have to scroll through hundreds of languages to get to English.

**Review by ad1992 — APPROVED** [review]
improvement instead of a feature?

**Comment by lipis** [comment]
@ad1992 can you check why the semantic action has 2 checks?

**Comment by ad1992** [comment]
> @ad1992 can you check why the semantic action has 2 checks?

Yep looking into it. It's weird even in the actual action repo it's triggered twice so looks like a bug in the action itself.

**Pull request merged**
