### PR TITLE
Compress before broadcasting

### PR DESCRIPTION
**Pull request by kbariotis**
Re #962, this uses `pako` to compress the payload before encrypting and decompress after decryption.

https://github.com/nodeca/pako
https://bundlephobia.com/result?p=pako@1.0.11

*Couple of questions:*

- Does compressing before encrypting makes sense or should it be the other way around?
- How to efficiently test what impact will this have?

[Data set and results below](https://github.com/excalidraw/excalidraw/pull/1227#issuecomment-609411073)

### CODE REVIEW

**Comment by dwelle** [comment]
> Does compressing before encrypting makes sense or should it be the other way around?

Doing it before is the only way it makes sense, because compressing encrypted data (which has ~random/even distribution of bytes) would have no benefit.

Note that we have to version the links, and only decompress links that were compressed in the first place. We may also switch to different encryption algo in the future, and would need to keep backward compat.

**Comment by vjeux** [comment]
Let’s only do it for collaboration for now. Space isn’t really an issue for shared links right now and would be nice not to have to worry about backwards compatibility there

**Comment by vjeux** [comment]
You can use performance.now() to figure out how much time compression takes. And look at the size of the encrypted payload to see if it makes a material difference

**Comment by kbariotis** [comment]
```
Number of syncable elements 20
Size before compressing 6500
Size after compressing 1791
Compression took 2.600 milliseconds

Number of syncable elements 30
Size before compressing 9723
Size after compressing 2504
Compression took 2.609 milliseconds

Number of syncable elements 40
Size before compressing 12947
Size after compressing 3095
Compression took 7.880 milliseconds

Number of syncable elements 50
Size before compressing 16172
Size after compressing 3592
Compression took 9.379 milliseconds

Number of syncable elements 60
Size before compressing 19397
Size after compressing 4279
Compression took 5.065 milliseconds

Number of syncable elements 70
Size before compressing 22622
Size after compressing 4806
Compression took 3.155 milliseconds

Number of syncable elements 80
Size before compressing 25847
Size after compressing 5476
Compression took 3.969 milliseconds

Number of syncable elements 90
Size before compressing 29073
Size after compressing 6245
Compression took 3.024 milliseconds

Number of syncable elements 100
Size before compressing 32298
Size after compressing 6532
Compression took 2.665 milliseconds
--------
Number of syncable elements 200
Size before compressing 64049
Size after compressing 14538
Compression took 9.259 milliseconds

Number of syncable elements 300
Size before compressing 96056
Size after compressing 21297
Compression took 19.394 milliseconds

Number of syncable elements 400
Size before compressing 128068
Size after compressing 27383
Compression took 60.890 milliseconds

Number of syncable elements 500
Size before compressing 160062
Size after compressing 33640
Compression took 1047.115 milliseconds
-------
Number of syncable elements 1000
Size before compressing 320068
Size after compressing 65531
Compression took 115.534 milliseconds

Number of syncable elements 1500
Size before compressing 480061
Size after compressing 97093
Compression took 115.084 milliseconds
```

Time to compress (ms) vs  No of elements
chart

**Comment by dwelle** [comment]
Umm, even if that 1500ms compression is an outlier, even just ~100ms compression is too much when we potentially sync 10-20 times per second.

**Comment by kbariotis** [comment]
@dwelle 

<details>
  <summary>Data set</summary>
  
```
Number of syncable elements 20
Size before compressing 6555
Size after compressing 1879
Compression took 1.4550000196322799 milliseconds.
Encryption took 0.09499990846961737 milliseconds.
Decryption took 0.1799999736249447 milliseconds.
Uncompression took 13.294999953359365 milliseconds.

Number of syncable elements 30
Size before compressing 9809
Size after compressing 2390
Compression took 7.04499997664243 milliseconds.
Encryption took 0.3100000321865082 milliseconds.
Decryption took 0.2300000051036477 milliseconds.
Uncompression took 2.4899999843910336 milliseconds.

Number of syncable elements 40
Size before compressing 13060
Size after compressing 2999
Compression took 8.574999985285103 milliseconds.
Encryption took 0.13499998021870852 milliseconds.
Decryption took 0.169999897480011 milliseconds.
Uncompression took 5.119999987073243 milliseconds.

Number of syncable elements 50
Size before compressing 16316
Size after compressing 3623
Compression took 4.734999965876341 milliseconds.
Encryption took 0.6600000197067857 milliseconds.
Decryption took 0.1949999714270234 milliseconds.
Uncompression took 8.7000000057742 milliseconds.

Number of syncable elements 60
Size before compressing 19572
Size after compressing 4431
Compression took 1.7300000181421638 milliseconds.
Encryption took 0.1550000160932541 milliseconds.
Decryption took 0.14999997802078724 milliseconds.
Uncompression took 18.299999996088445 milliseconds.

Number of syncable elements 70
Size before compressing 22826
Size after compressing 4871
Compression took 2.624999964609742 milliseconds.
Encryption took 0.09999994654208422 milliseconds.
Decryption took 0.12499990407377481 milliseconds.
Uncompression took 4.514999920502305 milliseconds.

Number of syncable elements 80
Size before compressing 26079
Size after compressing 5408
Compression took 2.8849999653175473 milliseconds.
Encryption took 0.14000001829117537 milliseconds.
Decryption took 0.14999997802078724 milliseconds.
Uncompression took 5.434999940916896 milliseconds.

Number of syncable elements 90
Size before compressing 29334
Size after compressing 6082
Compression took 2.9199999989941716 milliseconds.
Encryption took 0.11499994434416294 milliseconds.
Decryption took 0.1550000160932541 milliseconds.
Uncompression took 1.600000075995922 milliseconds.

Number of syncable elements 100
Size before compressing 32590
Size after compressing 6586
Compression took 4.119999939575791 milliseconds.
Encryption took 0.0950000248849392 milliseconds.
Decryption took 0.17499993555247784 milliseconds.
Uncompression took 2.689999993890524 milliseconds.

Number of syncable elements 200
Size before compressing 65057
Size after compressing 14641
Compression took 10.604999959468842 milliseconds.
Encryption took 0.14500005636364222 milliseconds.
Decryption took 0.265000038780272 milliseconds.
Uncompression took 28.765000053681433 milliseconds.

Number of syncable elements 300
Size before compressing 97566
Size after compressing 20805
Compression took 49.27499999757856 milliseconds.
Encryption took 1.2150000547990203 milliseconds.
Decryption took 0.18500001169741154 milliseconds.
Uncompression took 11.71500002965331 milliseconds.

Number of syncable elements 400
Size before compressing 130074
Size after compressing 27217
Compression took 30.884999898262322 milliseconds.
Encryption took 0.1550000160932541 milliseconds.
Decryption took 0.1700000138953328 milliseconds.
Uncompression took 15.325000043958426 milliseconds.

Number of syncable elements 500
Size before compressing 162580
Size after compressing 33590
Compression took 26.320000062696636 milliseconds.
Encryption took 1.4250000240281224 milliseconds.
Decryption took 0.3249999135732651 milliseconds.
Uncompression took 18.875000067055225 milliseconds.
```
</details>

chart (1)

**Comment by dwelle** [comment]
Interesting. So decompression is much slower on small scenes.

**Comment by vjeux** [comment]
It's good to see that encryption and decryption are essentially free!

**Comment by vjeux** [comment]
Those numbers seem to indicate that we should invest in sending deltas rather than compression/decompression which is costly. We started by sending the entire scene as it's a lot easier to implement and get correct, but we knew that it would hit some limitations as the scene would get bigger.

We're seeing something similar happening with #1246.

**Comment by kbariotis** [comment]
I'm closing this but we should come back for reference. Implementation wise is quite easy so no need to keep it around.

**Pull request closed without merging**
