### PR TITLE
Allow opening empty excalidraw file

### LINKED ISSUE #1321: Downloading an empty file and loading back, throws an error
It shouldn't.. the file is just empty.

### PR DESCRIPTION
**Pull request by kbariotis**
Fix #1321

### CODE REVIEW

**Comment by dwelle** [comment]
This actually also disables invalid-file detection. Seems that it wasn't implemented correctly if it based it on whether elements aren't empty.

**Comment by dwelle** [comment]
Throwing this on line 19 should work:

```
throw Promise.reject(t("alerts.couldNotLoadInvalidFile"));
```

**Comment by kbariotis** [comment]
Thank you @dwelle great catch! Fixed.

**Comment by lipis** [comment]
I'm getting the screen of death with this JSON

```json
{
  "labels": {
    "linearElementMulti": "Press Escape or Enter to finish",
    "resize": "You can constraint proportions by holding SHIFT while resizing"
  }
}
```

**Comment by Fausto95** [comment]
> This actually also disables invalid-file detection. Seems that it wasn't implemented correctly if it was based it on whether elements aren't empty.
> 
> repro:
> 
> 1. load an empty file with  `json` extension, or containing e.g. `{}`

Yea. It was implemented that way to avoid importing invalid json files :)

**Comment by dwelle** [comment]
Now it display error splash as @lipis pointed. Weird..

**Comment by dwelle** [comment]
Pushed a fix. Apparently we can't reject with an error object in here. Rather than fixing the root cause, I just used what we did before → reject with a string.

**Comment by kbariotis** [comment]
Weird, it was working just fine by throwing a regular error. I personally avoid throwing strings and use native errors. In any case, thanks for fixing. :)

**Comment by dwelle** [comment]
No, you're right. I should have just fixed the one more case we pass `error` as string. Pushed a fix to go back to error objects to not subvert expectations :).

**Comment by kbariotis** [comment]
🚢

**Pull request merged**
