### PR TITLE
Initialize appearance with system preference on the very first load

### PR DESCRIPTION
**Pull request by tomayac**
Fixes https://github.com/excalidraw/excalidraw/issues/2025

### CODE REVIEW

**Comment by dwelle** [comment]
Maybe best to put it in the App constructor to keep `getDefaultAppState()` relatively pure and deterministic (we'll want to factor out the unpure `name` later as well).

**Comment by tomayac** [comment]
@dwelle Can you move it wherever you see a better fit? I need to focus on other things this afternoon. The logic is there…

**Comment by xixixao** [comment]
Two more reasons I wouldn't turn this on by default (if user has dark mode on in their browser/OS) (in addition to https://github.com/excalidraw/excalidraw/issues/2025#issuecomment-683299353):

- The RGB color codes are not transformed (which is intentional)
- The export still doesn't support dark mode

Makes more sense to me to have the user tap the toggle button a single time.

**Comment by dwelle** [comment]
Apart from the refactor (we'll also need to mock out `matchMedia` for tests), are we moving forward with this? I'm now thinking that leaving it up to the user may be best after all. It removes magic + probably better for the brand. The dark UI is bit harder to read, especially if a user lands on Excalidraw.com for the first time.

**Comment by tomayac** [comment]
Closing this, since the majority vote seems to be to make this a manual conscious decision. I'm not opposed, even though personally I wish more editor-like apps would honor my preferences from the start, but we're generally acknowledgedly not there yet.

**Pull request closed without merging**
