### PR TITLE
delay scene init until document active

### PR DESCRIPTION
**Pull request by dwelle**
fixes https://github.com/excalidraw/excalidraw/issues/1919

Not sure if this is 100% tight and won't cause issues elsewhere.

~~Someone please test on Safari using the steps outlined in the issue https://github.com/excalidraw/excalidraw/issues/1919~~ this can't actually be tested in the preview because share links aren't supported there.

@tomayac thoughts?

### CODE REVIEW

**Comment by tomayac** [comment]
(Sorry for the delay, I was OoO.)

Maybe forcing the window focus manually via [`Window.focus()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/focus) might help? Else, the delay workaround from the PR looks fine, too. Note that instead of removing the event listener after it has fired, you can also use the [`once`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Parameters:~:text=tree.-,once) option.

**Comment by dwelle** [comment]
No problem. Good point about the `once` option. As for `window.focus()`, that won't work (I tested). If browser allowed to programmatically focus tabs, it would defeat the purpose.

**Comment by dwelle** [comment]
I'm gonna merge this, and create a crbug when I get the chance because I think this can cause problems for many apps, and where the solutions wouldn't be as clear cut as this one.

**Comment by tomayac** [comment]
> No problem. Good point about the `once` option.

Cool.

> As for `window.focus()`, that won't work (I tested). If browser allowed to programmatically focus tabs, it would defeat the purpose of the interventions that cause the OP issue ITFP.

Yeah, fair.

**Pull request merged**
