### PR TITLE
Respect initial aspect ratio while resizing with shift pressed

### PR DESCRIPTION
**Pull request by enzoferey**
Part of https://github.com/excalidraw/excalidraw/issues/690.

Missing:

- [ ] Adjust `rollbackShiftElement` while resizing in aspect ratio mode so when you release the key the changes are applied to it.
- [ ] All handlers should respect aspect ratio.
- [ ] Aspect ratio while creating ? (maybe another PR ?).

### CODE REVIEW

**Comment by dwelle** [comment]
This should mirror the shape when going to the negative. Currently, it first stops at 0px height, and then doesn't remember the scale vector on the other side.

excalidraw_proportional_resize_3

I'm thinking if we shouldn't wait for @GasimGasimzada, where he potentially wanted to implement scale vector for all shapes, not just for arrows (https://github.com/excalidraw/excalidraw/pull/759)

Second, related point: the shape should remember its dimensions when you release shift and press it again, as long as you don't release mousedown.

**Comment by enzoferey** [comment]
It was not my intention to fix the whole issue, just to provide a way to keep initial aspect ratio as a low hanging fruit. That's why I wrote "Part of #690" and not "Closes #690" 😁 

I indeed didn't go as far as mirroring + recording initial state as I wrote in the issue. I had some minutes to kill, so I wrote some fix. Feel free to do whatever you want with the PR 👍

**Comment by dwelle** [comment]
Yep, I'm aware that you didn't want to fix the whole issue, but wasn't sure what part of it it was fixing. Either way, as it stands now it's a regression against current production, so I wouldn't merge it in this state, but we can keep working on this PR.

**Comment by lipis** [comment]
What's the status here? Does anyone wants to pick it up?

**Comment by enzoferey** [comment]
@lipis I said on Monday via the Twitter group that I could finish this up, but we need to align on the expected behaviour.

**Comment by lipis** [comment]
As Sketch does it :)

**Comment by j-f1** [comment]
Not sure how Sketch does it, but Keynote handles shift+side handle like this:

Screen Recording 2020-03-25 at 10 23 40

**Comment by lipis** [comment]
Let's copy someone's functionality.. but from a single source.. I mentioned Sketch as more popular, or we can do what Figma does as more open and free.

**Comment by j-f1** [comment]
Figma is the same as Keynote. Is Sketch any different?

**Comment by dwelle** [comment]
As per orig issue, we wanted to align with Figma.

**Comment by lipis** [comment]
So let's do Figma style..! @enzoferey are you up for it?

**Comment by enzoferey** [comment]
Sure thing ! 👍 I should be done by the end of the weekend.

**Comment by lipis** [comment]
@enzoferey a friendly ping :) 🍰

**Comment by enzoferey** [comment]
Hey @lipis, as I wrote on the Twitter group I was waiting for the rotation to land in order to avoid conflicts. I'm also quite busy rebuilding a whole platform from scratch at the moment, but I think I will manage to close this in the upcoming days 👍

**Comment by lipis** [comment]
Would be great.. whenever you have time, no rush.. was just wandering what's the status.

**Comment by enzoferey** [comment]
The code is not super clean but it works fine, but it would almost be the same thing for all other handlers as well (right now only "SE" works).

There are two things that concern me:

1. The handlers being outside the element: Figma's one are inside, so the patterns works better I feel.
2. I was not able to think of an implementation matching Figma's one that doesn't require adding 2 new element references in the app state (one for keeping aspect ratio, one for fallback when unpressing shift). Plus, the fallback unshift element needs to be updated as well while resizing with shift pressed.

Let me know if this is fine for you or if you have any better idea.

**Comment by dai-shi** [comment]
I'm not sure if I understand the Figma behavior, but I'm pretty sure what to be stored in the app state is the position&size (`element.x, element.y, element.width, element.height and element.angle`) of the element at the start of dragging. It should be common with #1024/#1225.

Note: #1296 is going to be a big rewrite. Check out the dependency graph in https://github.com/excalidraw/excalidraw/issues/1298#issue-595798631

**Comment by enzoferey** [comment]
Pinging @dwelle and @dai-shi here. So what's up ? Does this implementation work for you guys ?

If you want me to finish this, I need clear indications of what you expect. The maths for "SE" corner are there working, it should be trivial to adapt for the other handlers. Adjusting `rollbackShiftElement` while resizing in aspect ratio mode so when you release the key the changes are applied to it is not implemented but could be tackled in another PR as well as the creation aspect ratio.

I think you have a better vision on the interdependencies of these many resize features and it will be easier for you to merge this logic than it is for me. But waiting for your comments 👍

**Comment by dai-shi** [comment]
#1296 is merged, which no longer uses deltas. So, this needs to follow that. Sorry about this big change, but the UI is much better and the logic is much cleaner now.
Also, as we discuss now in https://github.com/excalidraw/excalidraw/pull/1225#issuecomment-612407129, the original ratio can be stored in local variables not in app state.

**Comment by dwelle** [comment]
> Also, as we discuss now in #1225 (comment), the original ratio can be stored in local variables not in app state.

That was my initial suggestion in chat. I forgot to follow up again because there was too much chaos going on.

**Comment by enzoferey** [comment]
I'm not sure how you want to implement shift unpress with local variables. Would you be exporting those so the `App.tsx` can use them ? For reference [shift unpress handler](https://github.com/excalidraw/excalidraw/pull/768/files#diff-c8a101915dc6871f1f3d7ad2208d8655R1119).

I still think it will take you less time to finish this up now that you have just changed the resize logic as it's pretty much rewriting this PR from scratch.

**Comment by dwelle** [comment]
Handle all of it inside the `pointerMove` handler nested in `pointerDown`. Set up a local variable `isShiftResizing: boolean` that you'll toggle on/off when you get to https://github.com/excalidraw/excalidraw/pull/768/files#diff-c8a101915dc6871f1f3d7ad2208d8655R1071. Using that you'll be able to figure out if you need to reset to orig x/y (when you go from `true` → `false`).

It's best not to add new state variables for things like these when we absolutely don't need to.

**Comment by dai-shi** [comment]
Pinging @jquintozamora here to see if he'd be interested taking this in the future.

**Comment by dai-shi** [comment]
Just a note: As a commit in #1467 showed, keeping ratio is basically one line of code. The real issue is handling key up/down events #1340 which is not well implemented currently. There's an unconfirmed suggestion in https://github.com/excalidraw/excalidraw/pull/1225#issuecomment-617168284.

**Comment by xixixao** [comment]
This should be simpler now that I added the PointerDownState, which is where the ratio can live.

https://github.com/excalidraw/excalidraw/blob/4ab4fce9981afb1d6ee6d61a1e5f22a026f0fd5d/src/components/App.tsx#L1990-L1992

**Comment by dwelle** [comment]
I'm gonna close this. We'd have to resolve the conflicts and from what I gather this PR needs a rewrite anyway. @enzoferey feel free to reopen  if I'm wrong.

**Pull request closed without merging**
