### PR TITLE
CSP: fix codesandbox

### PR DESCRIPTION
**Pull request by dwelle**
attemps to fix https://github.com/excalidraw/excalidraw/issues/1400

### CODE REVIEW

**Comment by dwelle** [comment]
This one still fails, on `https://yxwk8.csb.app/sass-transpiler.26602e31.worker.js`:

https://codesandbox.io/s/github/excalidraw/excalidraw/commit/68dd1c47636d1c0a979f25e3f267d033b46f92be

**Comment by Shriram-Balaji** [comment]
@dwelle I think the worker-src csp header also needs to be modified, if the script-src change doesnt' work.

**Comment by dwelle** [comment]
On it.

**Comment by dwelle** [comment]
Mhm, now fails on cloudflare

```
https://cdnjs.cloudflare.com/ajax/libs/sass.js/0.11.0/sass.sync.js
```

https://codesandbox.io/s/github/excalidraw/excalidraw/commit/9d8da96fd9432cd724f14193fe94a5435ba8b2c9

What do we do about those? Whitelisting speciic cloudflare-hosted libs isn't a good idea (would break anytime csb changes their versions). And allowing any cloudflare-hosted libs may not be secure?

**Comment by Shriram-Balaji** [comment]
@dwelle Cloudflare docs seem to have some instructions for them - https://support.cloudflare.com/hc/en-us/articles/216537517-Using-Content-Security-Policy-CSP-with-Cloudflare

**Comment by dwelle** [comment]
That doesn't help. AFAIK we'll have to whitelist their whole `cdnjs.cloudflare.com` domain. Not sure if we even can whitelist specific resources, but even if we could we'd end up with the problem I noted above.

**Comment by Shriram-Balaji** [comment]
For now adding https://cdnjs.cloudflare.com to the script-src should work.

**Comment by dwelle** [comment]
We could also go with @CompuIves's solution and disable CSP in dev mode. But that would require us to build `index.html` dynamically, AFAIK. Or does Zeit support adding CSP headers on the fly?

**Comment by dwelle** [comment]
Now we're failing on `unsafe-eval` :)

```
proxyConsole.js:64 EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive:
```

**Comment by dwelle** [comment]
I'm gonna go ahead and add everything to fix CSB, and then we can discuss what next before merging.

**Comment by Shriram-Balaji** [comment]
Ya I think that's better for now, but wondering why unsafe-eval is needed in the first place, because `eval` is always bad.

**Comment by dwelle** [comment]
This should be it. There are some parts of the app that still don't work (collab, shareable link etc.), but dunno if they ever worked on CSB.

Ad `unsafe-eval` → it may be used for lazyloading & evaling scripts (I do that often).

**Pull request merged**
