### PR TITLE
rounded icon for pwa

### PR DESCRIPTION
**Pull request by Fausto95**
Capture d’écran 2020-04-07 à 14 19 33

### CODE REVIEW

**Comment by Fausto95** [comment]
@nanot1m feel free to merge this whenever you PR is ready

**Comment by lipis** [comment]
Screenshot 2020-04-07 at 3 21 48 PM

What about completely round?

**Comment by lipis** [comment]
That's old school

**Comment by Fausto95** [comment]
Capture d’écran 2020-04-07 à 14 43 17

**Comment by lipis** [comment]
Can you add it here as well: https://github.com/excalidraw/excalidraw-logo

(and maybe some missing ones)

**Pull request merged**
