### PR TITLE
chore: Update to browser-fs-access v0.16.0

### PR DESCRIPTION
**Pull request by tomayac**
This should make Brave users, Firefox users, and Safari users universally happy. Background: https://github.com/GoogleChromeLabs/browser-fs-access/issues/41.

### CODE REVIEW

**Comment by tomayac** [comment]
Turns out neither the small hammer nor the bigger hammer worked reliably. Let's try a couple of microhammers. https://github.com/GoogleChromeLabs/browser-fs-access/commit/c188acdcac8b0c9d27e1cb4a1dfed31e74f31744

**Review by lipis — APPROVED** [review]

**Comment by tomayac** [comment]
See https://github.com/GoogleChromeLabs/browser-fs-access/blob/c188acdcac8b0c9d27e1cb4a1dfed31e74f31744/src/legacy/file-open.mjs#L33-L49 for the final solution to this problem.

**Comment by dwelle** [comment]
Thanks @tomayac, looks solid :)

**Comment by tomayac** [comment]
Thanks in turn for improving the initial hack and challenging it until we came up with the as proper as possible solution to a problem that doesn’t have a good solution at the moment.

**Pull request merged**
