### PR TITLE
feat: support vertical text align for bound containers

### PR DESCRIPTION
**Pull request by ad1992**
for https://github.com/excalidraw/excalidraw/issues/4586

https://user-images.githubusercontent.com/11256141/155977569-61945bbf-6ce7-44dc-a2ab-9f576cb78eda.mp4

TODOS

- [x] Support vertical-align for bounded text containers

- [x] Finalize the icon for vertical alignment, currently, I am using the align icons

### CODE REVIEW

**Comment by ad1992** [comment]
Screenshot 2022-03-01 at 10 02 38 AM
Updated the icons to ☝🏻

**Comment by dwelle** [comment]
I'd rename `verticalAlign` to `textVerticalAlign`, since the former is too generic.

A few bugs:

1. the text align icons don't have active state when wysiwyg active
2. the text align is reset to `top` after you edit
3. bottom vertical align acts incorrectly in specific cases, such as this:
	  1. create a sticky note of single line of text, and exit wysiwyg
	  2. set vertical align to bottom, and horizontal align to left or right
	  3. edit again, and add multiple new lines
	  
	  vertical_align_bottom_bug

**Comment by ad1992** [comment]
> I'd rename `verticalAlign` to `textVerticalAlign`, since the former is too generic.
> 
> A few bugs:
> 
> 1. the text align icons don't have active state when wysiwyg active
> 2. the text align is reset to `top` after you edit
> 3. bottom vertical align acts incorrectly in specific cases, such as this:
>    
>    1. create a sticky note of single line of text, and exit wysiwyg
>    2. set vertical align to bottom, and horizontal align to left or right
>    3. edit again, and add multiple new lines
>    
>    vertical_align_bottom_bug

I have pushed fix for the above issues, can you try now ?

**Comment by ad1992** [comment]
> Screenshot 2022-03-01 at 10 02 38 AM
> 
> Updated the icons to ☝🏻

one weird thing though, the vertical-align icons for right and center look different in your video @dwelle, any idea why ?

**Pull request merged**
