### PR TITLE
fix: resizing arrow labels

### LINKED ISSUE #6744: proportionally resizing arrow labels results in buggy sizing
Proportionally resizing text containers resizes the bound text as well. That should (?) apply to arrow labels, too, but right now the behavior is a little buggy.

When you resize below the original size, it doesn't resize the text. When you resize above the orig size, it does resize the text.

We should pick one, and keep it consistent.

I'd align with text containers, but maybe there's a good argument to be made to not do this for labeled arrows?

excal-proportional-resize-labeled-arrows-bug

/cc @ad1992 @zsviczian @alex-kim-dev

### PR DESCRIPTION
**Pull request by alex-kim-dev**
fix #6744

- make the arrow label width a fraction (0.7) of the container width
- calculate the label min width from its font size (`fontSize` * 11)
- resize the label simply by multiplying its font size by scale

also makes possible to resize the label of a vertical 2-point arrow

### CODE REVIEW

**Comment by dwelle** [comment]
Hey @alex-kim-dev, thanks!

The resizing behavior looks fixed. 💪

But, the max-width of labeled text seems to have regressed from production:

production: 
image

PR:
image

**Comment by alex-kim-dev** [comment]
image

image

**Comment by alex-kim-dev** [comment]
By the way, I just found out that the label isn't updated when moving the arrow point with shift. Is it on purpose?

Peek 2023-07-25 21-20

**Review by ad1992 — APPROVED** [review]
Thanks @alex-kim-dev, looks good 🚀

**Pull request merged**
