### PR TITLE
docs: Integrate docusaraus for docs

### PR DESCRIPTION
**Pull request by ad1992**
check https://docs-git-aakansha-docs-excalidraw.vercel.app/
- [x] Initial setup
- [x] Update template for excal
- [x] Only build docs when docs changes

Next
- [ ] Migrate package readme

### CODE REVIEW

**Comment by DanielJGeiger** [comment]
Would merging this make the `docs` preview build in #5483 and subsequent PRs?

**Comment by ad1992** [comment]
Docs wil
Screenshot 2022-07-26 at 2 14 59 PM
l only build when any change made in docs once this is merged
You can see [this](https://vercel.com/excalidraw/docs/7SNq14EEvhJPo6iBkFVtqX5BXvDc) for which build was ignored

**Review by dwelle — APPROVED** [review]

**Comment by DanielJGeiger** [comment]
> yeah once they are rebased with master after this is merged. Any concern with that ?
> 
> EDIT -> you are right this will start triggering for every PR's, I will add a check to make sure this triggers only for docs related changes

For what it's worth, by rebasing #2993 and #5449 I discovered a slight edge case.  That is, the `docs` build runs if pushing the rebase commit on a PR branched prior to #5482.

**Comment by dwelle** [comment]
> > yeah once they are rebased with master after this is merged. Any concern with that ?
> > EDIT -> you are right this will start triggering for every PR's, I will add a check to make sure this triggers only for docs related changes
> 
> For what it's worth, by rebasing #2993 and #5449 I discovered a slight edge case. That is, the `docs` build runs if pushing the rebase commit on a PR branched prior to #5482.

yeah, basically all active PRs will need to be merged/rebased on latest.

**Pull request merged**
