### PR TITLE
feat: Add shortcut to focus on opacity slider

### PR DESCRIPTION
**Pull request by h7y**
Pressing `o` will focus on the selected element's opacity slider.

Checks off one item in #2649

### CODE REVIEW

**Comment by dwelle** [comment]
We might wanna use `O` for Ellipse (either as an alias or a replacement for current `E`) to align with Figma.

**Comment by h7y** [comment]
I got `O` from the issue. How about `Shift+O` instead?

**Comment by h7y** [comment]
> I got `O` from the issue. How about `Shift+O` instead?

@dwelle any thoughts on this? :)

**Comment by dwelle** [comment]
> > I got `O` from the issue. How about `Shift+O` instead?
> 
> @dwelle any thoughts on this? :)

Not sure. In all other apps including Figma, opacity is handled via `0-9` keys, but sadly we're using them for the toolbar.

Anyway, I think opacity is a low-priority shortcut (at least in the way we'd implement it it wouldn't be super useful). I'd first focus on `stroke color` and `fill color`. I'll add a comment in the issue.

**Pull request closed without merging**
