### PR TITLE
refactor: simplify zoom by removing `zoom.translation`

### PR DESCRIPTION
**Pull request by dwelle**
🎄

This PR remove `zoom.translation` (https://github.com/excalidraw/excalidraw/pull/2319) which is unnecessary and only adds complexity to the codebase. Instead, we just appropriately offset `appState.scrollX`/`appState.scrollY`.

I kept `appState.zoom` type as `{ value: number }` for now.

Tested:

- [x] Macbook trackpad
- [x] mousewheel
- [x] keyboard (cmd-plus/minus/zero, shift-1)
- [x] Android
- [ ] iOS
	- I tested on iOS simulator, but the emulated touch events are not the real deal

Not sure what https://github.com/excalidraw/excalidraw/runs/4628291148?check_suite_focus=true#step:4:142 is about.

### CODE REVIEW

**Comment by zsviczian** [comment]
on ipad I found it difficult to select objects. The same works without issues in the production build. 


https://user-images.githubusercontent.com/14358394/147372428-2a3716c5-3d27-4db2-8211-f55ec20ac35b.mp4

**Comment by dwelle** [comment]
> On ipad using Edge browser I found it difficult to select objects.
> [...]
> After further testing, this time using Safari, zoom gut stuck, I could no longer select items, anywhere I touched the screen it was zooming in or out.

Very strange. The changes I made should hardly affect any of what you mention. At worst, it should affect zooming. I'll try to repro tomorrow.

**Comment by dwelle** [comment]
Can't repro on my ipad (ipadOS 14):

https://user-images.githubusercontent.com/5153846/147383515-f1bbca15-00a9-445b-a02d-e31480aee7a4.mp4

What's your OS version?

> After further testing, this time using Safari, zoom gut stuck, I could no longer select items, anywhere I touched the screen it was zooming in or out.

What you're describing sounds like https://github.com/excalidraw/excalidraw/issues/3553 and should be unrelated to this PR

**Comment by zsviczian** [comment]
Hm… I don’t know what happened yesterday. I can reproduce it either.

**Comment by dwelle** [comment]
@zsviczian this is now ready for merging

**Review by zsviczian — APPROVED** [review]
Tested it on iPad and also merging into the Obsidian build. Both worked as expected. 🎉

**Pull request merged**
