### PR TITLE
Move to the closest element when the 'Scroll back to content' button is pressed

### LINKED ISSUE #1260: Scroll to content should go to an element
See https://github.com/excalidraw/excalidraw/issues/1246#issuecomment-609494036

Instead of scrolling to the middle of the bounding box, we could look for the closest elements from the current location and scroll to that.

### PR DESCRIPTION
**Pull request by yongdamsh**
Resolves #1260 

scroll_back_to_content

### CODE REVIEW

**Comment by lipis** [comment]
In your example, all three could fit on the screen though.. :)

**Comment by yongdamsh** [comment]
Yes, it's a bit silly to move to the edge even though you can show it all on one screen. Even if the code gets a bit complicated, is it better to move it to the center in this case?

**Comment by lipis** [comment]
Makes more sence.

**Comment by yongdamsh** [comment]
It was applied. 6ad205f

**Comment by yongdamsh** [comment]
@lipis Is there anything else we need to do? And can you see the now.sh check error?

**Pull request closed without merging**
