### PR TITLE
Hide the UI elements when printing the page

### LINKED ISSUE #1652: Remove UI when printing
My daugther did a drawing and wanted to print it. Unfortunately it printed the UI as well which is suboptimal.

BFAFE07A-711B-4A5D-8EBB-855243C16AAF

### PR DESCRIPTION
**Pull request by YounessFkhach**
Fixes #1652

image

### CODE REVIEW

**Comment by lipis** [comment]
Related: #411

**Comment by petehunt** [comment]
thanks for the contribution!

**Comment by vjeux** [comment]
Thank you!

The scrollbars still appear, but it's likely going to be a bigger change. We'll need to have two canvas, one for the scene and one for the bars. Then we can hide the bars. Not sure if it's worth the complexity though.

**Comment by dwelle** [comment]
May be easier than that: [onbeforeprint](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeprint)

**Comment by dai-shi** [comment]
@vjeux How do you like this?

https://dai-shi.github.io/excalidraw-animate/#toolbar=no&autoplay=no&json=5201760293486592,mNc0uajAc-4Q8LyGTlgkjg

image

**Comment by vjeux** [comment]
I’m not sure what I’m supposed to look at

**Comment by dai-shi** [comment]
Hmmmmm, I myself am not sure what was my point... It's just the same as exporting SVG and open it in a browser. I mean to hide the scrollbars. Never mind.

(Well, I'm interested in how your daughter will react with the animation from her drawing.)

**Pull request merged**
