### PR TITLE
Wysiwyg text

### PR DESCRIPTION
**Pull request by nanot1m**
Some hacky implementation

Screen Recording 2020-01-06 at 14 58 05

### CODE REVIEW

**Comment by vjeux** [comment]
Omg, this is working really well! I'm impressed! This is a much better experience than the alert. It feels a lot more natural.

**Comment by vjeux** [comment]
Sorry but I have to revert it,
- the text isn't created at the exact same place (unlike your demo)
- moving the text is going twice as fast for some reason
- it doesn't take into account the stroke color

ezgif-7-61bafbd47710

Could you investigate and fix those three things and then we can put it back? Thanks!

**Comment by nanot1m** [comment]
@vjeux, sorry, but I can't reproduce issues you have found. Can you share your os and browser name?

**Comment by nanot1m** [comment]
I'll continue work in #238

**Pull request merged**
