### PR TITLE
Revert "Feature: Multi Point Arrows (#338)"

### PR DESCRIPTION
**Pull request by dwelle**
This reverts commit #338 because we need to write a migration first. https://github.com/excalidraw/excalidraw/issues/632

### CODE REVIEW

**Comment by dwelle** [comment]
Awaiting checks... :)

**Comment by AryanJ-NYC** [comment]
I also hope this fixes #633 .

**Comment by dwelle** [comment]
Reverted, landed. Try now @AryanJ-NYC.

**Comment by GasimGasimzada** [comment]
@dwelle since we reverted it, how do I do changes to to the PR?

**Comment by dwelle** [comment]
Pull your master, run `git revert fd63721`, commit it as one commit. Push as a new PR. And then we'll do the fixes in subsequent commits.

**Comment by dwelle** [comment]
Follow me back on twitter so we can talk more quickly.

**Comment by GasimGasimzada** [comment]
Okay doing it now! :)

**Pull request merged**
