### PR TITLE
Switch to `Sentence case` instead of `Title Case`

### PR DESCRIPTION
**Pull request by lipis**
For consistency, across the app.

It's probably going to ruin some translations, but it's an easy fix...

### CODE REVIEW

**Comment by dwelle** [comment]
Figma and Affinity uses Title Case, btw.

\*flies away\*

**Comment by j-f1** [comment]
Mac uses title case, whereas Windows doesn’t, I believe. We could go with switching translations by platform but that seems like too much work for too little benefit. I do think we should make titles be title case, though.

**Comment by lipis** [comment]
The translations will be fine.. Crowdin is suggesting the same translation when minor change is happening. macOS is using Title Case in the menus, we don't have many menus.. and we had a mix of cases!

Sentence case it's easier and no much to think about out.

**Comment by lipis** [comment]
17 strings it's not that bad I was expecting it to be worse..

**Comment by j-f1** [comment]
heh, macOS isn’t super consistent:

Screenshot_2020-04-07 09 51 18

**Comment by lipis** [comment]
Let's do this!

**Pull request merged**
