### PR TITLE
log console.error to sentry

### PR DESCRIPTION
**Pull request by dwelle**

### CODE REVIEW

**Comment by dwelle** [comment]
I should have tested it locally before pushing...

**Comment by dwelle** [comment]
Should work now. Can't test on preview because of CSP.

**Comment by lipis** [comment]
:D we should allow it?

**Comment by dwelle** [comment]
You mean sentry CSP?

**Comment by dwelle** [comment]
@lipis ping on the CSP. Otherwise, let's merge this.

**Comment by lipis** [comment]
If you need to update anything on CSP: https://github.com/excalidraw/excalidraw/blob/master/now.json#L24

I'm not sure what you need.. it's green light from me if you are good.

**Comment by dwelle** [comment]
Yea.. I'm not sure if we even want to log errors from preview. Merging for now.

**Pull request merged**
