### PR TITLE
Add french translation

### PR DESCRIPTION
**Pull request by thibautsabot**
By looking at the following PR : https://github.com/excalidraw/excalidraw/pull/500

I figured I could add french translations as well.

I took inspiration from Photoshop wordings to avoid using "generic translated words"

### CODE REVIEW

**Comment by lipis** [comment]
The shortcut for the `Flèche` is `F` that is not working.. the shortcuts should not change. Not sure if it's part of this PR though.

**Comment by dwelle** [comment]
@lipis I actually don't think we should tailor shortcuts to labels/translations. I'm not sure, how do other apps do it?

Be it as it may, there's an industry standards for tools such as selection (`V` instead of `S` --- at least for English). But like you said, that's for another PR.

**Comment by lipis** [comment]
#524

**Comment by Fausto95** [comment]
LGTM

**Comment by dwelle** [comment]
We can always improve it later. Merging!

**Pull request merged**
