### PR TITLE
docs: Add basic outline and info for codebase/contributing docs

### PR DESCRIPTION
**Pull request by LukaHietala**
@dwelle

### CODE REVIEW

**Comment by LukaHietala** [comment]
There might be some missing thing, so feel free to add new sections

**Comment by LukaHietala** [comment]
Should there be a section for i18n stuff?

**Comment by dwelle** [comment]
Renaming to `Contributing Guide` and moving all contributing-related docs to it is an interesting idea, and it makes sense.

I think we should also dedupe the `Development` and `Contributing` docs, and move it to contributing section as well.

/cc @ad1992

**Comment by LukaHietala** [comment]
Any updates?

**Pull request closed without merging**
