### PR TITLE
CMD + D to Duplicate Selection

### PR DESCRIPTION
**Pull request by Fausto95**
Adds support for: https://github.com/excalidraw/excalidraw/issues/981

### CODE REVIEW

**Comment by dwelle** [comment]
Let's use:

https://github.com/excalidraw/excalidraw/blob/master/src/element/newElement.ts#L103

**Comment by dwelle** [comment]
I'd also maybe select the newly duplicated element, what do you think?

**Comment by Fausto95** [comment]
Oh yeah, I done it @dwelle

**Comment by dwelle** [comment]
Nice, working great!

One more thing, you forgot the translation :).

**Comment by Fausto95** [comment]
Good catch.
Just added the locale.

**Comment by Fausto95** [comment]
We're good to go @dwelle

**Pull request merged**
