### PR TITLE
fix: rerender i18n in host components on lang change

### PR DESCRIPTION
**Pull request by dwelle**
fix https://github.com/excalidraw/excalidraw/issues/6222

We now export `useI18n()` hook which rerenders on `props.langCode` update.

This only applies to components rendered inside the `<Excalidraw/>` component due to depending on its jotai context.

I've also stopped using editor's jotai context for app-specific atoms so we further decouple the app from depending on editor internals, and so that we can surface package related jotai issues.

### CODE REVIEW

**Comment by LukaHietala** [comment]
Is this a know bug in this PR that will also be fixed?

https://user-images.githubusercontent.com/95122845/218314175-66848de6-1411-48a5-9ef4-a746fc0bd3d5.mp4

**Comment by dwelle** [comment]
@LukaHietala yeah, this PR actually regressed too many things due to the disconnect in initial langCode values of the atom and what's cached in the browser. I'm thinking on how to solve this.

**Comment by dwelle** [comment]
should be ready now!

**Comment by LukaHietala** [comment]
There is still one issue, when you have clean localstorage it does not update in the right way. I'll elaborate soon

**Comment by LukaHietala** [comment]
> There is still one issue, when you have clean localstorage it does not update in the right way. I'll elaborate soon

Oh, nevermind. The issue I had was there because the language I was testing was not fully translated

**Review by ad1992 — APPROVED** [review]
Please add the docs in https://github.com/excalidraw/excalidraw/pull/6251

**Comment by ad1992** [comment]
@dwelle please update the changelog as well

**Pull request merged**
