### PR TITLE
Move text insertion handler in onpointerdown

### PR DESCRIPTION
**Pull request by Fausto95**

### CODE REVIEW

**Comment by Fausto95** [comment]
I came up with this PR, let me know if there's something wrong @dwelle @j-f1.
Now I'm starting to see this bug(https://github.com/excalidraw/excalidraw/issues/1226) when going multiline.

**Comment by dwelle** [comment]
@Fausto95 that's because the `state.editingElement` is reset. It can be fixed by returning from this branch here:

https://github.com/excalidraw/excalidraw/blob/63cbe0bb0eb542b88b227157168cdd311a507753/src/components/App.tsx#L1577

but I'm not sure whether it has side effects. Would need to review the code.

**Comment by Fausto95** [comment]
> @Fausto95 that's because the `state.editingElement` is reset here:
> 
> https://github.com/excalidraw/excalidraw/blob/63cbe0bb0eb542b88b227157168cdd311a507753/src/components/App.tsx#L2414-L2421
> 
> It can be fixed by returning at the end of this branch here:
> 
> https://github.com/excalidraw/excalidraw/blob/63cbe0bb0eb542b88b227157168cdd311a507753/src/components/App.tsx#L1551-L1578
> 
> but I'm not sure whether doing so has side effects. Would need to review the code.

That fixed the bug :)

**Comment by Fausto95** [comment]
The tests are failing due to: https://github.com/excalidraw/excalidraw/blob/6537fc16776ca179d91fbbbd2e427a44d1b7d028/src/components/App.tsx#L1550

Need to figure how to fix them or whether or not I should use fakeTimers here

**Comment by dwelle** [comment]
My last commit seemed to have fixed the double rendering on mobile. We'll see if it has side-effects (if so, will fix in another PR).

What remains:

- [ ] fix tests
- [ ] ensure the double click is fired only if 2nd click is in the vicinity of the first click (to align with `onDoubleClick`).

**Comment by lipis** [comment]
What's the status of this one?

**Comment by Fausto95** [comment]
I assume that this can be closed

**Comment by Fausto95** [comment]
I will take a look at this soon

**Comment by lipis** [comment]
@Fausto95 @dwelle What's the latest? Can we fix the conflicts and tests and merge it.?

**Comment by dwelle** [comment]
No idea. I thought the double text rendering has been fixed a long time ago, but I'm not on iOS so can't test this (on Android I don't see any issues).

**Comment by Fausto95** [comment]
It has been fixed.. I think we can close this one

**Pull request closed without merging**
