### PR TITLE
fix: update og images 

### PR DESCRIPTION
**Pull request by jsjoeio**
Looks like #855 caused the og image to break because it switched them to use relative paths. 

This fixes that. 

Co-authored-by: Justin E. Samuels <js1599.msu@gmail.com>
@thugdebugger

### CODE REVIEW

**Comment by jsjoeio** [comment]
Well, it's showing up again! 

image

**Comment by jsjoeio** [comment]
Sorry, need to make one last change!

**Comment by jsjoeio** [comment]
When the white background was added in #702, the size of the image was changed. I believe this is the reason why the logo is not fitting the og image correctly so I resized it and added the white background.

**Comment by jsjoeio** [comment]
Trying to break the cache, so we're testing a fake hash on the name of the image. I'll merge when ready

**Comment by vjeux** [comment]
Thank you! Looks good, please merge when you’re ready :)

**Comment by jsjoeio** [comment]
image

Okay, we can't figure out why it looks squished now :( It's set up exactly how it was when #401 was merged in and it looked fine then. Could be caching, not totally sure. Once we fix CI, I'll merge it

**Pull request merged**
