### PR TITLE
refactor: reuse scss variables in js for SSOT

### PR DESCRIPTION
**Pull request by dwelle**
Import SCSS variables into JS so that we don't duplicate values which leads to regressions.

Had to suffix the `variables.scss` file with `.module` due to https://github.com/facebook/create-react-app/issues/10047#issuecomment-724227353

### CODE REVIEW

**Comment by dwelle** [comment]
what PR title do we use for this?

**Review by lipis — APPROVED** [review]
I'm not aware of this black magic.. but seems nice :)

**Comment by lipis** [comment]
> what PR title do we use for this?

Refactor or Chore I would say..

**Comment by dwelle** [comment]
Yea, I think this doesn't necessitate a public-facing changelog. /cc @ad1992 — you can merge if fine

**Review by ad1992 — APPROVED** [review]
looks nice 🚀

**Pull request merged**
