### PR TITLE
build: decouple package deps and introduce yarn workspaces

### PR DESCRIPTION
**Pull request by ad1992**
- [x] Decouple dependencies
- [x] Move to Yarn workspaces
- [x] The package code stays in packages/excalidraw, packages/utils
- [x] Excalidraw app should work
- [x] collaboration
- [x] PWA
- [x] Excalidraw package example should work
- [x] Excalidraw package - [test version](https://www.npmjs.com/package/@excalidraw/excalidraw/v/0.17.1-test)
- [x] fix tests
- [x] workflows
- [ ] ~update docs~ -> I will update post-merge of this PR since it would be easy to catch then 

BundleSize check fails since directory is updated so it will get fixed once the PR is merged

### CODE REVIEW

**Comment by ad1992** [comment]
@excalibot trigger release

**Comment by ad1992** [comment]
@excalibot trigger release

**Comment by ad1992** [comment]
@excalibot trigger release

**Comment by ad1992** [comment]
@excalibot trigger release

**Comment by ad1992** [comment]
@excalibot trigger release

**Review by dwelle — APPROVED** [review]

**Comment by bancek** [comment]
I think this PR broke a lot of translations: `429 new strings for translation (1,997 words).`

You should notify the translators or lock the Crowdin project so that people don't waste their time because this can all be automated.

https://crowdin.com/project/excalidraw

**Comment by ad1992** [comment]
> I think this PR broke a lot of translations: `429 new strings for translation (1,997 words).`
> 
> You should notify the translators or lock the Crowdin project so that people don't waste their time because this can all be automated.
> 
> https://crowdin.com/project/excalidraw

Hi @bancek 👋🏻, Apologies, I wasn't aware that Crowdin would not sync it properly and break the translations when updating the file path. Let me see, I am hoping there should be some way to automate it

**Comment by ad1992** [comment]
> > I think this PR broke a lot of translations: `429 new strings for translation (1,997 words).`
> > You should notify the translators or lock the Crowdin project so that people don't waste their time because this can all be automated.
> > https://crowdin.com/project/excalidraw
> 
> Hi @bancek 👋🏻, Apologies, I wasn't aware that Crowdin would not sync it properly and break the translations when updating the file path. Let me see, I am hoping there should be some way to automate it

All the translations till yesterday have been merged to master so I am hoping now things will be better. Let me know

**Pull request merged**
