### PR TITLE
Move language selection to the menu

### PR DESCRIPTION
**Pull request by vjeux**
There's no reason for the language to be its own thing. We can add it to the general menu instead.

### CODE REVIEW

**Comment by vjeux** [comment]
@lipis would love to get your feedback on this one

**Comment by dwelle** [comment]
I'd tweak the design:

image

Or at the very least, add the padding. Shall I make the change?

**Comment by lipis** [comment]
it's not the most used feature so having it on top there is not my favorite.. of we are about to add more settings maybe hiding that behind some sort of cog icon for settings.. ?

dunno..

**Comment by dwelle** [comment]
But I agree with @lipis... the bottom right was fine with me (it's common for languages).

**Comment by voluntadpear** [comment]
Bottom right looks good for the language selection for now. As @lipis mentioned, once we add more settings we can hide them all in a single "gear" icon settings button.

**Comment by vjeux** [comment]
Ok, going to close it.

**Pull request closed without merging**
