### PR TITLE
feat: add line shape

### PR DESCRIPTION
**Pull request by muzakparov**
Related to [#344](https://github.com/excalidraw/excalidraw/issues/344)

### CODE REVIEW

**Comment by dwelle** [comment]
The hitbox seems incorrect when the line is diagonal, starting from southwest to northeast (maybe there are other cases, didn't check extensively):

[excalidraw-line-hitbox.zip](https://github.com/excalidraw/excalidraw/files/4064199/excalidraw-line-hitbox.zip)

(note the cursor)

excalidraw_line_hitbox

**Comment by nanot1m** [comment]
Nice! Can you add stroke width and sloppiness params for lines? 
image

**Comment by Fausto95** [comment]
The icon has a bit of extra margin which makes it not perfectly aligned! 

Capture d’écran 2020-01-15 à 11 31 01

**Comment by muzakparov** [comment]
@dwelle fixed hitbox bug, thanks!

**Comment by muzakparov** [comment]
@nanot1m sorry I totally missed that one. Stroke width and sloppiness for line are added now. Thank you!

**Comment by muzakparov** [comment]
@Fausto95 thanks for noticing!:) pushed a fix.

**Comment by Fausto95** [comment]
LGTM, just needs to be updated with master

**Comment by muzakparov** [comment]
@Fausto95 updated with master, cheers!

**Pull request merged**
