### PR TITLE
Sort translations

### PR DESCRIPTION
**Pull request by lipis**
https://sortjson.com/

### CODE REVIEW

**Comment by dwelle** [comment]
Not sure what the use case is, but for this to have any, we'd need to the sorting to the `pre-commit` hook otherwise it'll get out of order on pretty much every change.

**Comment by dwelle** [comment]
But doing that, renames would end up in order changes and thus harder-to-decipher diffs. So I wouldn't do this ordering. What's the use case again?

**Comment by vjeux** [comment]
I’m not sure that this is a good change either. Translations are usually grouped together based on where they happen in the original source and related. Moving them to be alphabetically sorted breaks this.

**Comment by lipis** [comment]
It's consumed by the machines, but maintained by humans.. I believe it's easier to scan them if they are sorted, rather than area based.

**Comment by lipis** [comment]
So what do you guys think? It's grouped by sections anyway.

**Comment by dwelle** [comment]
You haven't really made a case for why sorting is useful.

Pros:

- since we'll have multiple, identically-structured translation files, it might be good to ensure all files are ordered the same

    That being said, we could make (and likely will need) a script to validate the translations, anyway.

Negatives:

- We can't group labels together, which is more semantic.

    e.g. sloppiness labels, will be sorted among unrelated labels:

    ```
    "architect": "Architect",
    "artist": "Artist",
    "cartoonist": "Cartoonist"
    ```

    Thus, we'll need to rename the labels to something like:

    ```
    "sloppiness_architect": "Architect",
    "sloppiness_artist": "Artist",
    "sloppiness_cartoonist": "Cartoonist"
    ```

    And soon we'll end up with a BEM scheme (for better or worse. But it offloads the friction to the developer).

- We need to set up a `pre-commit` script that will auto-sort it for us, because in no way we're gonna force devs to do this manually.

**Comment by dwelle** [comment]
Also, if we end up sorting and naming the labels BEM-style, we'd then need to force devs to adhere to that BEM naming. Unlike grouping related things together, which everyone does naturally by themselves. So we'd end up with rules upon rules, friction, and it would slow everyone down.

So unless you're withholding a very strong argument that didn't occur to me, I don't think this is a good idea.

**Comment by lipis** [comment]
Having a sortable JSON makes it easier to scan and find things when looking to change, update or add something. It's not always needs to be automated, even though we could. These files are maintained by humans.

As for spending too much time on it, I don't see how. If the file is sorted already it's obvious for someone that adds something to have it sorted, and if not it's not a huge deal, we have a reviews for that. Worst case scenario it will be caught in the next iteration.

Having the file sorted alphabetically, requires less thinking on where to add a new item.

These are my main reasons.

**Comment by lipis** [comment]
and I also don't see any harm in it :)

**Comment by vjeux** [comment]
Let's not do that. It doesn't provide any tangible benefits and is introducing merge conflicts and bikeshedding.

**Comment by dwelle** [comment]
Alright, let's close it.

@lipis if you want to retain at least some "order", consider reverting the German translation which you sorted in the initial PR (AFAIK).

**Pull request closed without merging**
