### PR TITLE
Change order of Text and Line

### LINKED ISSUE #432: Move text to be last icon
We should have the line to be right next to the arrow and text to be last.

image

### PR DESCRIPTION
**Pull request by lipis**
Fixes #432

### CODE REVIEW

**Comment by lipis** [comment]
I just rerun npm install.. maybe older node..

**Comment by lipis** [comment]
just the name.. check the diff

**Comment by lipis** [comment]
Not sure why it's failing... Glitch in the matrix?

**Comment by vjeux** [comment]
Can you try again? I just removed the domain from zeit.co

**Comment by lipis** [comment]
Green!

**Pull request merged**
