### PR TITLE
Fix code quality issues

### PR DESCRIPTION
**Pull request by withshubh**
[DeepSource](https://deepsource.io/) is a code review automation tool that detects code quality issues and helps you to automatically fix some of them. You can use DeepSource to track test coverage, Detect problems in Dockerfiles, etc. in addition to detecting issues in code.

All the features of the DeepSource are mentioned [here](https://deepsource.io/features/).
I'd suggest you integrate DeepSource since it is free for Open Source projects forever.

### Using DeepSource to continuously analyze your repository

- Merge this PR. I have included a `.deepsource.toml` in this PR, which you can use to configure your analysis settings.
- Install DeepSource on your repository [here](https://deepsource.io/signup).
- Activate analysis [here](https://deepsource.io/gh/excalidraw/excalidraw/).

### CODE REVIEW

**Comment by lipis** [comment]
I don't see TypeScript in the analyzers in their official site.

Screenshot 2020-12-15 at 5 13 38 PM

**Comment by dwelle** [comment]
Either way, we've recently discussed this and decided not to introduce such tools to the codebase at this point as it would likely only incur maintenance costs without clear benefits, which we would not be able to justify right now.

**Comment by lipis** [comment]
While I agree with @dwelle, out of curiosity I enabled it on my repo to test it.. It looks like we are clean :) https://deepsource.io/gh/lipis/excalidraw/

**Comment by withshubh** [comment]
Okay @dwelle  @lipis  Thank you :sparkles:

**Pull request closed without merging**
