### PR TITLE
Calculate rotated element bounds properly

### LINKED ISSUE #1303: Properly calculate bounds of rotated elements
From: https://github.com/excalidraw/excalidraw/pull/1273#issuecomment-610385649

This is more like request for comment.

I'm not sure if it's correct wording, but let's call `Coords` and `Bounds`.

For unrotated diamonds:
image

For rotated diamonds:
image

Now, Coords is used for resizing and rotating, and Bounds is used for selection detection and calculating canvas size. Bounds are also currently used for multiple element resizing.

Issue 1:
https://github.com/excalidraw/excalidraw/pull/1273#issuecomment-610345053 The selection doesn't detect the diamond because it's smaller than the Bounds.

image

Issue 2:
When exporting, there is an extra margin compared to unrotated elements.

image

----

What would be an ideal solution and maybe a practical workaround?

(edit)
We go with this https://github.com/excalidraw/excalidraw/issues/1303#issuecomment-610462010 and revisit the UI issue later.

### PR DESCRIPTION
**Pull request by dai-shi**
Close #1303

For diamonds and ellipses, the calculation should be fast.
For curved lines, it may require some computations. (There's probably room for improvement, but I'm not sure how.)

### CODE REVIEW

**Comment by dai-shi** [comment]
@dwelle Hope you have some time to check this out.

**Comment by dai-shi** [comment]
(Hm, the empty commit doesn't seem to help.)

**Comment by dwelle** [comment]
Cool.

One problem though. As discussed in the issue, this behavior has the downside of doing what Figma is doing incorrectly IMO. Rotated diamonds/circles use their individual bounding boxes for calculation of group/export bounding box.

In red is the desired bounding box:

image

Export (in red, the bounding box as it should be):

image

Also, not sure if outside the scope of this PR, but filled irregular shapes (which already have their bounding box + rotation) break group-selection.

Below, the elements don't have group bounding box at all:

image

**Comment by dai-shi** [comment]
@dwelle It's working for me.

image

image

> Also, not sure if outside the scope of this PR, but filled irregular shapes (which already have their bounding box + rotation) break group-selection.

That's the expected behavior as only three shapes are group resizable. #1218 
But, as you note, it may be confusing. Should we show the group selection rectangle without resize handles for now?

**Comment by dwelle** [comment]
I don't know what's up with me lately. Either I'm clicking on some old preview, or I must have used production in this case, else I don't know :(. Apologies for the confusion.

> But, as you note, it may be confusing. Should we show the group selection rectangle without resize handles for now?

Nah, let's ship this as it for now, and we'll fix it in #1218.

**Comment by dwelle** [comment]
Btw, I still don't understand the usefulness of showing individual bounding boxes. It only adds to the clutter.

image

Anyone has thoughts on this?

**Comment by lipis** [comment]
Especially now yes, that's confusing.. but there are cases that some elements are not resiziable and it's not going to be visible which elements will get resized.

**Comment by dai-shi** [comment]
I would like to keep it. It shows which object is selected. Without it, one would never know if a shape is selected or not in a group rectangle. My idea to mitigate it is to make the each shape rectangle lighter. How does that sound?

**Comment by dwelle** [comment]
> . It shows which object is selected. Without it, one would never know if a shape is selected or not in a group rectangle.

Why not do somthing like Figma/Affinity. Instead of showing the bounding boxes, render the selected element's borders in different color:

Figma:

image

Affinity:

image

**Comment by dai-shi** [comment]
I think it's a bigger question than what this PR addresses. So, I'd suggest to open a new issue.

My two cents is:

> render the selected element's borders in different color

It would be nice if we could do this with the current dashed lines with margins (and without changing the position of rotation handle). It would require some effort.

I understand the confusion, and it's a good discussion. (And, this is what I wanted to discuss in the original issue, so it's good.)

**Comment by dwelle** [comment]
Yes, we can leave for another PR.

In the issue I must have missed you wanted to display the individual bounding boxes to communicate which elements are selected and which not. We'll iterate on the design later.

**Comment by dwelle** [comment]
Alright. Seems to work fine. Thanks for this @dai-shi!

**Pull request merged**
