### PR TITLE
Refactor resize handle naming

### PR DESCRIPTION
**Pull request by dwelle**
Changed & aligned resize handles naming because it was getting very hard to orientate oneself.

- the `resizeHandler` was renamed to ~~`resizeHandle`~~ `transformHandle` (handler is a function that handles something, while *handle* is something you hold onto)
- the `resizeHandle` string (`sw`, `s`...) was renamed to ~~`resizeHandleSide`~~ `transformHandleType`

### CODE REVIEW

**Comment by dai-shi** [comment]
Nice. I had confused with the name. This will improve readability a lot.
How are you comfortable with one of `resizeHandleSide` being `rotation`?

**Comment by dwelle** [comment]
> How are you comfortable with one of resizeHandleSide being rotation?

Not that much. Any idea for better name? `resizeHandleName`/`resizeHandleCode`/`resizeHandleDirection`?

**Comment by dai-shi** [comment]
I mean "resize" doesn't mean "rotation" in general does it? For example, "resize" + "rotate" = "reshape", `reshapeHandle`???

**Comment by dwelle** [comment]
I see. From that perspective, `reshape` isn't good either -- rotation doesn't change shape. What about `transformHandle`?

**Comment by dai-shi** [comment]
That sounds good.

**Comment by dwelle** [comment]
pushed:

- `resizeHandle` → `transformHandle`
- transformHandleSide` → `transformHandleType`

**Pull request merged**
