### PR TITLE
Bring root fonts back 

### PR DESCRIPTION
**Pull request by Fausto95**

### CODE REVIEW

**Comment by lipis** [comment]
https://excalidraw-git-redirect-font-loading.excalidraw.now.sh/static/fonts/FG_Virgil.woff2

**Comment by Fausto95** [comment]
> Seems broken to me

@lipis same thing happens with `https://excalidraw.com/FG_Virgil.woff2`, but if you go to `https://excalidraw-git-redirect-font-loading.excalidraw.now.sh/static/fonts/FG_Virgil.woff2` and check the Network tab in devtoools, you should see the font file being loaded

**Comment by kbariotis** [comment]
Actually @Fausto95 you will have to change SVG paths as well https://github.com/excalidraw/excalidraw/blob/4228c2e094d16c5fe3d208a517854e55783b2c67/src/index-node.ts#L57

**Comment by vjeux** [comment]
Thank you!

**Pull request merged**
