### PR TITLE
Redirect excalidraw/* to root

### LINKED ISSUE #1096: Redirect excalidraw.com/* to the root
- https://excalidraw.com/hola
- https://excalidraw.com/foo
- https://excalidraw.com/404

### PR DESCRIPTION
**Pull request by mbj36**
Fixes #1096

### CODE REVIEW

**Comment by lipis** [comment]
This one is not working :)

https://excalidraw-git-fork-mbj36-master.excalidraw-team.now.sh/hola/mola/

**Comment by j-f1** [comment]
I think maybe you have to create Now routes to redirect anything that isn’t defined as a static file to the root?

**Comment by lipis** [comment]
We might need to add some rules in `now.json` instead https://zeit.co/docs/configuration#project/redirects

**Comment by mbj36** [comment]
@lipis does this mean we don't need code change to achieve this ?

**Comment by mbj36** [comment]
@lipis Just realised https://excalidraw.com/hola/mola is also not working. Above code handles redirection well.

**Comment by lipis** [comment]
Yeap.. we need to fix the `hola/mola` as well :)

**Comment by j-f1** [comment]
`/(.*)`?

**Comment by lipis** [comment]
what should go there to catch all?

**Comment by j-f1** [comment]
I think `/(.*)` is the catchall route.

**Comment by lipis** [comment]
Well that's what I have and it does infinite redirects..

**Comment by mbj36** [comment]
> Yeap.. we need to fix the `hola/mola` as well :)

If we fix this..do we even need now.json ?

**Comment by mbj36** [comment]
Whenever there is `hola/mola` then static content are not loaded because `http://localhost:3000/hola/fonts.css` request has been made. We need someway that static content are always requested from origin

**Comment by lipis** [comment]
We changed that because of the desktop app..

**Comment by lipis** [comment]
Hey @mbj36.. why did you close it?

**Pull request closed without merging**
