### PR TITLE
More prominent hint

### PR DESCRIPTION
**Pull request by lipis**
https://excalidraw-git-yellow-hint.excalidraw-team.now.sh

### CODE REVIEW

**Comment by vjeux** [comment]
I don't think that we need to make it bright yellow...

**Comment by lipis** [comment]
Lighter..

**Comment by lipis** [comment]
https://yeun.github.io/open-color/#yellow

**Comment by lipis** [comment]
@vjeux better?

**Comment by vjeux** [comment]
Still feels very much in your face. I'm not sure we need to draw that amount of attention to it. Even if people read it, it wouldn't help people know that they can do curved lines with excalidraw as it's not in the caption

**Comment by vjeux** [comment]
Going to close this for now.

**Comment by lipis** [comment]
I still believe that we can have them a bit more prominent.. give it a try locally with other colors.. maybe some gray. Now it's too hidden.

**Pull request closed without merging**
