### PR TITLE
fix cloning element.points

### PR DESCRIPTION
**Pull request by dwelle**
Wouldn't let me sleep if I let it like this :).

### CODE REVIEW

**Comment by dwelle** [comment]
Hold on actually..

**Comment by dwelle** [comment]
This may technically be bad, too...

**Comment by dwelle** [comment]
Ok, this is more like it. Probably not needed, but will ensure the same behavior as before the fixes (except, it still does a deep clone of points, of course).

**Comment by vjeux** [comment]
lgtm

**Pull request merged**
