### PR TITLE
Show move and resize cursors on hover

### LINKED ISSUE #250: Show respective cursor when hovering over element
Cursors like the resize arrows are shown only when the drag event has started. It'd nice to be able to change to the correct cursor when hovering over one of the edges.

I'm working on improving our `mousemove` event listener and hit testing to detect this kind of scenarios.

### PR DESCRIPTION
**Pull request by voluntadpear**
Fixes #250 

Now, the cursor should change accordingly if the user hovers over the elements without having any mouse button depressed.

Additionally:

* Refactors the resizing test logic so that `resizeTest` is not invoked again after the selected element has been found.
* Adds a `viewportCoordsToSceneCoords` to replace the proper `x` and `y` coords calculation relative to the drawing canvas that was done in most event handlers.

### CODE REVIEW

**Comment by vjeux** [comment]
Do you mind taking a small video to see how it looks by any chance? Thanks!

**Comment by voluntadpear** [comment]
Sure! Here is how it should look like. At the beginning, even though the move icon is visible when hovering over the hit testing regions of the element, I don't have any mouse button pressed:

cursor on hover

**Comment by vjeux** [comment]
This fixes https://github.com/excalidraw/excalidraw/issues/110 as well!

**Comment by vjeux** [comment]
Yay, thanks so much :)

**Comment by vjeux** [comment]
Just spent the past 10 minutes using excalidraw and it made a big different to have this kind of real time feedback! Thanks so much for building this!

**Pull request merged**
