### PR TITLE
feat: Right click panning

### PR DESCRIPTION
**Pull request by zsviczian**
Panning comes up as a regular question.
I see no harm in adding right-click panning, next to the already existing wheel-click and space+left-click panning.

See the most recent related issue raised for the Obsidian plugin: https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/307

### CODE REVIEW

**Comment by dwelle** [comment]
I'd wanna hold onto this. There's also a proposal to support right-click box-selection that would switch the box-selection model: https://github.com/excalidraw/excalidraw/issues/3983#issuecomment-922337156

**Comment by dwelle** [comment]
Can you create an issue request for this, and also list what apps are using RMB for panning? I'm aware only of Miro.

**Comment by zsviczian** [comment]
> Can you create an issue request for this, and also list what apps are using RMB for panning? I'm aware only of Miro.

#4448

**Comment by zsviczian** [comment]
parking this for now…

**Comment by ColemanDunn** [comment]
There are many apps that behave like this currently (LucidSpark, Miro, Unreal engine, Discord whiteboard, Figma (toggleable in settings)). Is it possible to re-open/look into this again? It is very helpful for navigating the canvas with one hand. Combined with scroll to zoom (also possible in the apps mentioned before), it is extremely powerful!

**Pull request closed without merging**
