### PR TITLE
fix: abort freedraw line if second touch is detected

### PR DESCRIPTION
**Pull request by zsviczian**
See also: [#1065](https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/1065) 
Placing a second finger on the canvas while drawing a freedraw shape results in a spike and the termination of the freedraw editing. Under normal conditions (i.e. drawing with your finger) this should not happen. This typically happens when using a pen, clicking the pen tool for the first time, and touching the canvas with your palm before touching it with the pen. In this scenario penMode does not activate before receiving the multi-touch input, resulting in the unwanted line.

The easiest way to simulate this situation is by touching the freedraw tool (i.e. not in penMode), then touching the canvas with one finger, and then, while the first finger stays on touching the canvas, touching the canvas with a second finger.

9B61D10B-6F27-4D02-8639-F9BEFB1D8DC8

image

### CODE REVIEW

**Comment by dwelle** [comment]
> This typically happens when using a pen, clicking the pen tool for the first time, and touching the canvas with your palm before touching it with the pen. In this scenario penMode does not activate before receiving the multi-touch input, resulting in the unwanted line.

What's the scenario there. If you the touch is a mistake before you touch with a stylus, that's a different case, no?

In any case, we should ship this, but:

1) Maybe we shouldn't limit based on size/points, but always discard the element on second touch event?
2) I'm actually thinking the use case should be to solve pinch zooming creating freedraw/line elements, hence upon discarding the element we shouldn't return so as to allow for zooming. https://github.com/excalidraw/excalidraw/issues/5176
3) extend this to arrow/line tools, at the very least. But to some extent it affects other tools, too. Line/arrow and freedraw are affected the worst, though.

**Comment by zsviczian** [comment]
> What's the scenario there. If you the touch is a mistake before you touch with a stylus, that's a different case, no?

Yes, this is the case. Not so much by mistake, but as you place your palm on the screen to draw often your hand will touch the screen before the pen, resulting in an initial spike.

> Maybe we shouldn't limit based on size/points, but always discard the element on second touch event?

That was my first solution, I added the size limitation later because I thought that it may happen that you are drawing a longer, more intricate freedraw line with your finger, holding the tablet with your other hand, which accidently touches the screen when you have already drawn a longer stretch of the line. This might be a very theoretical situation, I am ok to simply discard the freedraw if a second finger touches the screen.

> I'm actually thinking the use case should be to solve pinch zooming creating freedraw/line elements, hence upon discarding the element we shouldn't return so as to allow for zooming. https://github.com/excalidraw/excalidraw/issues/5176

The bigger issue with pinch zooming is not the unwanted lines, since once you are in penmode that is no longer an issue, but the accidental small zoom effects as you move your palm on the screen. Some noise filtering (i.e. discard small pinch zoom movements if in pen mode would help with that, but I think that should be handled in a different PR.

> extend this to arrow/line tools, at the very least. But to some extent it affects other tools, too. Line/arrow and freedraw are affected the worst, though.

Arrows and lines are a different case. Currently if you start a line with two fingers you will enter multipoint edit mode which is a great feature (albeit I am not sure it is intended). The issue with this feature today, is that depending on the relative position of the first and second touch, sometimes this gesture works as expected, and sometimes it doesn't. I think arrows and lines should be handled in a separate PR as they require a different logic and more thinking.

**Comment by zsviczian** [comment]
@dwelle 

> https://github.com/excalidraw/excalidraw/issues/5176

I removed the `return` statement, this way you can pinch zoom with the freedraw tool active and it won't draw a line. Checking for 

> Maybe we shouldn't limit based on size/points, but always discard the element on second touch event? 

The size limit on number of points ensures that if you are drawing a freedraw element and switch to pinch zooming without first picking up your first finger, the element you've drawn until that point will not be deleted and the zoom will be executed.

**Comment by dwelle** [comment]
> > What's the scenario there. If you the touch is a mistake before you touch with a stylus, that's a different case, no?
> 
> Yes, this is the case. Not so much by mistake, but as you place your palm on the screen to draw often your hand will touch the screen before the pen, resulting in an initial spike.

That's for when you pick the tool with your finger instead of the stylus I presume. I tend to use stylus for that so it doesn't happen to me, but I get the issue.

> > Maybe we shouldn't limit based on size/points, but always discard the element on second touch event?
> 
> That was my first solution, I added the size limitation later because I thought that it may happen that you are drawing a longer, more intricate freedraw line with your finger, holding the tablet with your other hand, which accidently touches the screen when you have already drawn a longer stretch of the line. This might be a very theoretical situation, I am ok to simply discard the freedraw if a second finger touches the screen.
> 
> [...]
>
> The size limit on number of points ensures that if you are drawing a freedraw element and switch to pinch zooming without first picking up your first finger, the element you've drawn until that point will not be deleted and the zoom will be executed.

Those do seem edge-casey, but ok, let's keep the heuristic for now and see how it works in practice. If it's not working great, there are other heuristics we can try, such as checking if the points are a small cluster suggesting you've been moving your finger in place a lot before placing the 2nd finger. We can also add a time element (if below certain time since creation, discard).

> > I'm actually thinking the use case should be to solve pinch zooming creating freedraw/line elements, hence upon discarding the element we shouldn't return so as to allow for zooming. #5176
> 
> The bigger issue with pinch zooming is not the unwanted lines, since once you are in penmode that is no longer an issue, but the accidental small zoom effects as you move your palm on the screen. Some noise filtering (i.e. discard small pinch zoom movements if in pen mode would help with that, but I think that should be handled in a different PR.

My remark wasn't related to penMode per se, but to the linked issue of drawing your hand and then panning/zooming around while the freedraw/line/arrow tool is still active.

> > extend this to arrow/line tools, at the very least. But to some extent it affects other tools, too. Line/arrow and freedraw are affected the worst, though.
> 
> Arrows and lines are a different case. Currently if you start a line with two fingers you will enter multipoint edit mode which is a great feature (albeit I am not sure it is intended). The issue with this feature today, is that depending on the relative position of the first and second touch, sometimes this gesture works as expected, and sometimes it doesn't. I think arrows and lines should be handled in a separate PR as they require a different logic and more thinking.

That behavior isn't intended. The whole multi-point creation flow on mobile is very bad and will need to be reworked, so we can leave that for another PR then.


> I moved `this.updateGestureOnPointerDown(event);` to the beginning of `handleCanvasPointerDown` to allow pinch zoom with the freedraw tool active. I'm not sure how to test if moving `updateGestureOnPointerDown` to earlier in the code has any unwanted side effects.

Can't either, but I think it's safe to keep the pointer-related statements that were above the `updateGestureOnPointerDown()` in the same order, so let's move them above the new `updateGestureOnPointerDown()` position as well.

**Comment by zsviczian** [comment]
@dwelle are we good to proceed with this? I've been using this modification for a few days now and have experienced no side effects.

**Comment by dwelle** [comment]
> clicking the pen tool for the first time, and touching the canvas with your palm before touching it with the pen. 

So I'm now actually checking the iPad behavior, and this PR doesn't solve the above case.

Not only do we not check for `pen` event:

https://github.com/excalidraw/excalidraw/pull/6440/files#diff-86963609bec6fda3d34233676d5ae33f6aa4b9bbe2758a10cd4863b704b37093R3511

But it seems that we may not even be able to handle it as the `pen` event isn't registered if the finger is still touching the canvas.

**Comment by dwelle** [comment]
I'll merge this and we can improve in a follow up PR. Thanks! 🚀

**Review by dwelle — APPROVED** [review]

**Pull request merged**
