### PR TITLE
add now.json

### PR DESCRIPTION
**Pull request by mbj36**

### CODE REVIEW

**Comment by lipis** [comment]
Let's see!

**Comment by mbj36** [comment]
@lipis Can you please authorise this deployment, I am not able to do it

**Comment by mbj36** [comment]
@lipis this does solve the redirection issue (tried deploying to now locally), but it seems like static content are not loaded with this fix. Any pointers ?

**Comment by lipis** [comment]
Somethiing is wrong with this PR... I'll open a new one.

**Comment by lipis** [comment]
https://github.com/excalidraw/excalidraw/pull/1191 and we don't need authorization.. let's continue there..

**Pull request closed without merging**
