### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by lipis**

### CODE REVIEW

**Comment by j-f1** [comment]
Do we want to adjust this to target `dev` instead?

**Comment by j-f1** [comment]
Looks like you have to make any edits @lipis

**Comment by lipis** [comment]
To `production` you mean?

**Comment by j-f1** [comment]
This is what I’m seeing on crowdin, which is probably not what we want. 

image

**Comment by lipis** [comment]
Right.. check it tomorrow!

**Pull request merged**
