### PR TITLE
Add Quick Guide

### PR DESCRIPTION
**Pull request by lipis**
To be completed eventually.. and eventually it could be rendered online maybe :)

### CODE REVIEW

**Comment by Fausto95** [comment]
Could you build an UI for this too?

**Comment by lipis** [comment]
Let's kick it off as `.md` for now and think of a UI later.

**Comment by dwelle** [comment]
I'm not against this, but shouldn't we wait until the app is bit more mature? Right now there are so many changes that we'd need to be updating the document constantly.

**Comment by lipis** [comment]
My idea was to keep it in sync as we move forward.

**Pull request closed without merging**
