### PR TITLE
Update expiring origin trial token

### PR DESCRIPTION
**Pull request by tomayac**
https://www.google.com/appserve/mkt/p/AFnwnKUwZ7ofhCQhlxxDNFZMdDCdf9b9v3EYRD8U6SxPpY6Gbc8IcdhhPYia7pyqXB0waaDtEdbu3BGQhWGJKb_4NRgdzKr8MYmeYyrl3fsI7lY-Hlt_S7jKMtXl1uW41XuN2DfK3xfwxfKATuePkyy5Dfk

### CODE REVIEW

**Comment by vjeux** [comment]
What is this thing?

**Comment by tomayac** [comment]
That’s the origin trial token for the Native File System API.

**Comment by vjeux** [comment]
I see, how often does it need to be updated?

**Comment by tomayac** [comment]
The next time on April 4, 2020. 

F2A3AD1C-E0B9-4F28-B249-B49D55886A5D

**Comment by vjeux** [comment]
That’s very short! Is it going to be like this forever or is it going to be longer after it goes out of beta or something?

**Comment by tomayac** [comment]
Once the API is stable the token won’t be needed anymore. More context: https://github.com/GoogleChrome/OriginTrials/blob/gh-pages/developer-guide.md.

**Pull request merged**
