### PR TITLE
Performance hack

### PR DESCRIPTION
**Pull request by nanot1m**
This PR cuts off this lines from **rough**

https://github.com/pshihn/rough/blob/6c6a556add77551c2759fda0b2b2cb07aaffb5e3/src/canvas-base.ts#L52-L56

Demo scene to check performance
[StresTest.zip](https://github.com/excalidraw/excalidraw/files/4047952/StresTest.zip)

### CODE REVIEW

**Comment by vjeux** [comment]
Can you provide more context? Why is this line not needed but is a performance bottleneck? What savings are we talking about?

**Comment by dwelle** [comment]
Trying out before & after using the supplied stressTest scene, the difference in performance is striking!

**Comment by nanot1m** [comment]
Sorry, I'm little bit busy today, and couldn't investigate what the downsides of current solution.

@dwelle, used chrome profiler, and it showed that most time takes 'computeBBox' method

**Comment by vjeux** [comment]
The root cause is that we are regenerating all the shapes on every mouse move. This is a regression from this PR: https://github.com/excalidraw/excalidraw/pull/233#issuecomment-572293502

There was a two steps process where when you created the shape, we would store the generated commands. But this two-step process got removed and now we're regenerating the shapes in the draw operation.

Storing the generated commands would make mouse move fast again. This PR would still help with the first draw but I don't think it's bad enough that it's worth adding a hack for it that may have some unintended side effects.

cc @pshihn, you may be interested in knowing about this.

**Comment by vjeux** [comment]
This shouldn't be such a big issue after #316

**Comment by dwelle** [comment]
I see no performance benefit after #316. The testScene from this PR is still unusable, so unless we come up with other perf optimizations, I'd reopen this. /cc @vjeux

**Comment by nanot1m** [comment]
The better solution would be to cache shape image in offscreen canvas, and then reuse it to draw the scene.

It will help us to get rid of caching shape in the element and also will help to avoid expensive calls of draw function on every render.

**Comment by pshihn** [comment]
Can you test this scenario in the latest  (with the new roughjs 4.0)
The codepath mentioned at the top of this issue is not used anymore for filling polygons, so I am hoping you should see a performance improvement automatically. But I might be missing something, so it would be nice to know.

**Comment by dwelle** [comment]
@pshihn yes, the perf issue seems to be solved (for me at least) :fire: :heart:

**Comment by nanot1m** [comment]
@pshihn, it's awesome! thanks!

**Pull request closed without merging**
