### PR TITLE
More portal

### PR DESCRIPTION
**Pull request by KentBeck**

### CODE REVIEW

**Comment by KentBeck** [comment]
Looks like I screwed this up and put an already committed commit into this PR. Should I close it and open a new one or can you fix it?

**Comment by vjeux** [comment]
You can force push in that branch

**Comment by lipis** [comment]
Try to merge from master and don't mind the extra commits.. we are squashing our PRs anyway!

**Comment by dwelle** [comment]
Rebased on master to fix the commit and conflict issues.

**Comment by lipis** [comment]
But force push could be avoided, to not ruins OP local branches..

**Comment by dwelle** [comment]
Force push doesn't ruin anything. You can `git pull --rebase` and you're all set.

**Pull request merged**
