### PR TITLE
Issues/1827 group-ungroup icons

### PR DESCRIPTION
**Pull request by ReneCode**
Add group and ungroup icons to the action icons

fix for issue:[#1827](https://github.com/excalidraw/excalidraw/issues/1827)

I do my very best creating both icons  - unfortunately I'm not a designer. But I think it's looks usable.

### CODE REVIEW

**Comment by dwelle** [comment]
Thanks. I'd should the icons only when applicable, in particular

- [ ] don't show `group` button if selected only a single element or a single group of elements
- [ ] don't show `ungroup` button if selection doesn't contain any groups

**Comment by ReneCode** [comment]
ok, I will add that behaviour.

**Comment by lipis** [comment]
> * [ ]  don't show `group` button if selected only a single element or a single group of elements
> * [ ]  don't show `ungroup` button if selection doesn't contain any groups

Then it will appear like the same button doing the group and ungroup..! Might be OK.. need to see it in action.

**Comment by ReneCode** [comment]
I will also change the logic of the visibility of the context-menu-item for ```group```

* old:  more than 1 element is selected
* new: more than 1 element is selected && the selected elements are **not** a single group of elements

I will used the ```hidden```attribute from the the ToolButton and not the ```visible``` for show/not show the icon, because the ```visible``` leaves a gap on ```visible={false}```. That does not look good:

Bildschirmfoto 2020-07-24 um 19 01 50

**Comment by dwelle** [comment]
> Then it will appear like the same button doing the group and ungroup..! Might be OK.. need to see it in action.

We can tweak the look so it's more distinct.

**Comment by lipis** [comment]
Feels good to me...!

**Comment by ReneCode** [comment]
> > Then it will appear like the same button doing the group and ungroup..! Might be OK.. need to see it in action.
> 
> We can tweak the look so it's more distinct.

unfortunately I'm no designer. I have no idea how to make the icons "more distinct".

**Comment by lipis** [comment]
We can come up with a better icon in a separate PR.. looks great! Thanks!

**Pull request merged**
