### PR TITLE
fix: restoreElementWithProperties drops "parent" property

### PR DESCRIPTION
**Pull request by josephbuchma**
This bug causes invalid reconciliation during collaboration.
Here is a demo with buggy behavior:

https://user-images.githubusercontent.com/3718145/194401588-33aae198-546a-4867-840f-9fb7b5eb9ab5.mov

### CODE REVIEW

**Comment by dwelle** [comment]
@josephbuchma thanks for the PR and catching this! ♥ I've refactored it slightly and changed the key to something less generic which I wanted to do for some time.

Merging 🚀

**Review by dwelle — APPROVED** [review]

**Comment by josephbuchma** [comment]
I found another similar bug, and I narrowed it down to `Collab#queueSaveToFirebase`

On this demo, I changed `SYNC_FULL_SCENE_INTERVAL_MS` to 2s, and `Collab.syncElements` looks like this:
```ts
  syncElements = (elements: readonly ExcalidrawElement[]) => {
    // this.broadcastElements(elements);
    this.queueSaveToFirebase();
  };
```

https://user-images.githubusercontent.com/3718145/194723972-35aadf2f-995f-4d81-bf25-7865209e85a7.mov

**Comment by dwelle** [comment]
Ok, so maybe that's what https://github.com/excalidraw/excalidraw/pull/5681 was trying to fix? I'll look into this tomorrow.

**Comment by josephbuchma** [comment]
Hey @dwelle, any news?

**Pull request merged**
