### PR TITLE
fileHandle refactor & fixes

### PR DESCRIPTION
**Pull request by dwelle**
- fix https://github.com/excalidraw/excalidraw/issues/2250
- move `fileHandle` to appState
	- added support for async actions as part of this move
- remove `any` assertions on blobs

/cc @tomayac you may wanna take a quick look to ensure I didn't mess anything up

### CODE REVIEW

**Comment by tomayac** [comment]
I haven't looked into the "why" yet, but it doesn't seem to work as it should right now. I tested with the [preview](https://excalidraw-git-fixfilehandle.excalidraw.vercel.app/) using these steps:

1. Load a file and make a random change.
1. Save the change using the "Save" button.
1. Reload Excalidraw and see the restored scene.
1. Make another change and press "Save".
1. A new "Save as" dialog pops up.

In the last step, it should re-use the file handle and just save without popping up a dialog. It looks like you add the file handle in `commitHistory`, but then seem to not restore it again (but this is where I didn't investigate closely).

**Comment by dwelle** [comment]
Yep, but this is the production behavior and something this PR wasn't meant to fix. I'd leave that for another PR as it'll require storing the file handle to IDB (if that workflow works at all as we once discussed in DM), and since the fileHandle is now stored in appState, it's likely blocked by https://github.com/excalidraw/excalidraw/pull/1643 (damn, embarrassing that we haven't yet merged it :sweat_smile:).

**Comment by tomayac** [comment]
Oh, I see. So this is essentially removing the ugly global on `window` that I have introduced. In this case LGTM. I just naively thought it was dealing with the full story.

**Review by tomayac — APPROVED** [review]
LGTM, approval

**Comment by dwelle** [comment]
>  I just naively thought it was dealing with the full story.

Ha, no problem. This PR was mainly to fix this bug #2250, but I took the opportunity to refactor a bit. Thanks for the review.

**Pull request merged**
