### PR TITLE
fix: maintain relative position when resizing multiple linear elements together

### PR DESCRIPTION
**Pull request by ryan-di**
TODOs
- check `resizeMultipleElements`
- try a different way of bounding linear elements and compare

### CODE REVIEW

**Comment by dwelle** [comment]
will need to re-review if we can upstream some of the other refactor

**Comment by ryan-di** [comment]
@dwelle now that the ops curve bounds algorithm is adopted, I think we can safely close this draft PR : )

**Comment by dwelle** [comment]
> @dwelle now that the ops curve bounds algorithm is adopted, I think we can safely close this draft PR : )

I was thinking about the `getLinearElementAbsoluteCoords` rewrite which no longer uses the path ops — don't recall if it was causing any issues in other parts of the app (linear editor) or that was because of the type and we can use your simplified implem?

**Comment by ryan-di** [comment]
@dwelle From our discussion, I tried using points as bounds, which led to the changes in `getLinearElementAbsoluteCoords`, for resizing. It solved the resizing issue but raised other issues that we talked about on Discord. Since Alex has fixed the resizing problem by fixing the function `rescalePoints`, it shows that ops curve bounds can be safely used for resizing as well. So we can just leave out the changes to `getLinearElementAbsoluteCoords` in my branch.

**Pull request closed without merging**
