### PR TITLE
fix: #5666  — change size font when resize container

### PR DESCRIPTION
**Pull request by pavelpower**
change size of a text element by difference old size and new size of a associated container with this text element

What does a bug look like?

https://user-images.githubusercontent.com/301646/188576833-7af41864-9619-4cec-9f2d-66f9f1912a1b.mov

### CODE REVIEW

**Comment by dwelle** [comment]
Hey @pavelpower. This is by design as we want to make the existing text (size) fit into the container and break if necessary. We don't want to fit auto-resize the text to fill the container.

**Comment by alex-kim-dev** [comment]
Hey @dwelle, I just want to make sure, is this by design?
That's happening when resizing with aspect ratio locked:
Peek 2022-10-25 16-37

**Comment by Kasahs** [comment]
Any updates on this. Its breaking workflow completely.

https://user-images.githubusercontent.com/3906901/202285861-679a5ccb-74f5-4f47-80ff-2c6887f7ae70.mp4

**Comment by dwelle** [comment]
closing as the related bug should be fixed now, and the larger behavior being by design.

**Pull request closed without merging**
