### PR TITLE
sync remote selection

### PR DESCRIPTION
**Pull request by dwelle**
Fixes https://github.com/excalidraw/excalidraw/issues/1109

First take. Will refactor tomorrow.

(The stroke rendering courtesy of @vjeux)

excalidraw_sync_selection

Related: I think we should use a subset of bright colors for remote users. I often get gray/dark-blue/purple remote color which is hardly distinguishable from local color (black).

### CODE REVIEW

**Comment by dwelle** [comment]
Btw, sometimes the selection renders, but not the element (on remote). Happens usually during init. Can't repro easily, so it's hard to debug. Don't think it's related to this PR as I've been seeing invisible (i.e. unsynced) elements when I worked on collab earlier.

**Comment by lipis** [comment]
We should probably remove the white from the pool:

Screenshot 2020-04-04 at 12 28 57 AM

**Comment by j-f1** [comment]
How do you feel about having nested solid focus-outline-style selection instead of indicating using dashed lines?

**Comment by lipis** [comment]
I kind of like the current behaviour.. if more than two it doesn't really matter anyway who is touching it.. and looks cool!

**Comment by vjeux** [comment]
I'm playing with it right now and the current dashed line behavior looks a bit weird. But not sure if it's because I'm just playing alone.

I feel like it's worth shipping right now as it's working and we can tweak the rendering later. Should be pretty easy.

**Comment by lipis** [comment]
Agree.. 

Make it work, then make it better!

**Pull request merged**
