### PR TITLE
fix: make link icon clickable in mobile

### PR DESCRIPTION
**Pull request by ad1992**
fixes https://github.com/excalidraw/excalidraw/issues/4704

### CODE REVIEW

**Review by dwelle — APPROVED** [review]

**Comment by zsviczian** [comment]
@ad1992, I am still not able to navigate to links on mobile, except by clicking on the element to invoke edit mode, and then clicking the link in the popup link editor… however this approach is far less than ideal, if you have an element with a link as part of a group. 

Maybe this is down to precision of my touch and the other elements in the neighborhood. The link icon should have precedence and maybe a slightly larger (transparent) footprint.

**Comment by dwelle** [comment]
@zsviczian can't reproduce. For me clicking on the icon works fine both in view and edit mode on mobile 🤔 — are you on latest?

**Comment by dwelle** [comment]
> I believe I am on the latest. I tried both this preview and on excalidraw.com with my iPad.

Ok, you're right. I was checking just Android. https://github.com/excalidraw/excalidraw/issues/4740

**Comment by zsviczian** [comment]
I've now played with this in many different settings and devices. I am not sure what I am doing wrong, but I see no effect of this change on my iPad or on my Android. I am trying to tap on the link icon, I also tried with my pen hoping it would be more precise, but nothing. 

The idea is I tap the blue link icon and the page opens? The only thing that works now is double-tapping the element, and the link editor comes up. There I can open the link. But this is not very convenient, especially if the element with the link is part of a group.

**Pull request merged**
