### PR TITLE
fix(fonts): move fonts to public folder so that its served as static assets via cra & works in export

### PR DESCRIPTION
**Pull request by ad1992**
Since its not possible to keep fonts outside public so created fonts.css inside public which can be
included in excalidraw app and bundle separately. this way the file will not be requested twice as
well which is currently happening

fix https://github.com/excalidraw/excalidraw/issues/2263

cc @dwelle

### CODE REVIEW

**Comment by dwelle** [comment]
Can we put the fonts back to top-level, otherwise this will break existing SVG files.

**Comment by dwelle** [comment]
Btw, how does this fix the npm bundling issue?

**Comment by dwelle** [comment]
Regardless, let's merge this for now to fix the regression.

**Comment by ad1992** [comment]
> Btw, how does this fix the npm bundling issue?

I have bundled the fonts.css file via webpack so fonts still be bundled

**Pull request merged**
