### PR TITLE
fix: disable contextmenu on non-secondary `pen` events or `touch`

### PR DESCRIPTION
**Pull request by dwelle**
fix https://github.com/excalidraw/excalidraw/issues/4674

### CODE REVIEW

**Comment by zsviczian** [comment]
This is a good improvement. I tested it on iPad with pencil and touch and on Samsung Note with touch and S-Pen. Works as expected.

Not related to this change... but do you have any idea why the context menu won't on a long press with the apple pencil, but does show with a long press with the S-Pen. This difference is the same for both the current excalidraw.com version and this PR.

**Review by zsviczian — COMMENTED** [review]
What is the purpose of this? 
```typescript
event.nativeEvent.pointerType === "pen" &&
          event.button !== POINTER_BUTTON.SECONDARY
```

**Comment by dwelle** [comment]
> Not related to this change... but do you have any idea why the context menu won't on a long press with the apple pencil, but does show with a long press with the S-Pen. This difference is the same for both the current excalidraw.com version and this PR.

Good catch. AFAIK iOS doesn't support touch-hold to open contextMenu, so we're detecting it manually. We should include pens in that. It also means this PR doesn't handle iOS touch — gonna fix.

**Comment by dwelle** [comment]
> What is the purpose of this?
> 
> ```ts
> event.nativeEvent.pointerType === "pen" &&
>           event.button !== POINTER_BUTTON.SECONDARY
> ```

Allow opening contextmenu via the pen button that usually is used for opening contextmenus (it usually emits the same `event.button` type as right-click on a mouse).

**Comment by dwelle** [comment]
https://github.com/excalidraw/excalidraw/pull/4675/commits/50a67ccf1cf7d084a5da8fd471f8641b7a5e6487

this fix will require more work because of how it's implemented. I'll remove the commit for now as it actually needs timeout clearing which I'm not doing for pen. I'll open a new PR for this fix later.

**Comment by dwelle** [comment]
@zsviczian merging?

**Pull request merged**
