### PR TITLE
Shortcuts to zoom in/out and to reset zoom

### PR DESCRIPTION
**Pull request by nanot1m**
- <kbd>shift/meta</kbd> + <kbd>-</kbd> — zoom out
- <kbd>shift/meta</kbd> + <kbd>+</kbd> — zoom in
- <kbd>shift/meta</kbd> + <kbd>0</kbd> — reset zoom

### CODE REVIEW

**Comment by enzoferey** [comment]
We were actually thinking about overriding browser's one (ctrl + XXX).

Dunno what would be best.

**Comment by nanot1m** [comment]
In this PR browser zoom has been overridden.

But there is no way to override <kbd>meta</kbd> + <kbd>1-9</kbd> on mac os. These keybindings are used for tab switching.

I want to add support for zoom-to-fit on <kbd>shift</kbd> + <kbd>1</kbd> and  zoom-to-selected on <kbd>shift</kbd> + <kbd>2</kbd> later

**Comment by enzoferey** [comment]
> In this PR browser zoom has been overridden.

Oh oh, right :+1:

---

The zoom-to-fit and zoom-to-selected can be tackled in another PR yes. But indeed Figma for example only implements them with `shift`.

**Comment by dwelle** [comment]
LGTM.

**Pull request merged**
