### PR TITLE
Properly center the shape switcher

### LINKED ISSUE #896: Put the toolbar to the center of the empty area instead of the actual center.
Screenshot 2020-03-10 at 1 50 32 AM

### PR DESCRIPTION
**Pull request by j-f1**
Fixes #896. I can also change this to ignore the 🔒 button for the purposes of alignment.

### CODE REVIEW

**Comment by nanot1m** [comment]
These changes shift the shape switcher from the center to the right
image

**Comment by j-f1** [comment]
It seems centered to me:

Screenshot_2020-03-09 21 20 39

(banner hidden to get accurate pixel measurements)

Maybe we should include the corner thingy in the grid so we center between it and the sidebar?

**Comment by nanot1m** [comment]
Sorry, I mean it shifted from the actual center
76270196-9f814900-6274-11ea-803c-14bd6999a316

As for me it looks like it hanging in the random place

**Comment by j-f1** [comment]
cc @lipis ⬆️

**Comment by dwelle** [comment]
On smaller screens this change is ok I guess, but on bigger/regular ones I prefer current behavior. The new one feels way off center.

**Comment by lipis** [comment]
Yes, that true.. on smaller screens looks nice, I noticed that on the Desktop app.. :) Dunno.. we need a designer :)

**Comment by dwelle** [comment]
We can center against total viewport (current behavior) only above certain breakpoint.

**Comment by lipis** [comment]
Or maybe always attached to the left side?

**Comment by j-f1** [comment]
I kinda like the suggestion from @nanot1m in the issue — right align it.

**Comment by lipis** [comment]
I think we can just close this one for now..

**Pull request closed without merging**
