### PR TITLE
Show shortcut context menu

### LINKED ISSUE #2440: Show shortcut keys in the context menu (right aligned)
Most of the things achievable via shortcuts so it's nice to show them where possible.

### PR DESCRIPTION
**Pull request by ReneCode**
### Preview: https://excalidraw-git-issue-2440-show-shortcut-context-menu.excalidraw.vercel.app/

-----

- [x] created a new file ``src/action/shortcuts.ts`` because I didn't want to polute ``src/utils.ts`` (may be there is a better place)
- [x] started with only shortcuts used by context menu.
- [x] the shortcuts are take from ``ShortcutsDialog.tsx``
- [x] in ``regressionTests.test.tsx``the tests are changed from label text to ``data-testid=<shortcutName>``that is added in the ``ContextMenu.tsx``
- [x] because of the regressionTests all context menu items have to have a shortcutName.

next steps / PRs:
- add all shortcuts into ``shortcuts.ts``
- use them from ``ShortcutsDialog.tsx``

Fixes #2440

### CODE REVIEW

**Comment by ReneCode** [comment]
ahggr, again I've problems with ``fixture/*.png``files. (not knowing how to fix it :-/

**Comment by lipis** [comment]
The "right column" should be as big as the biggest shortcut..

Screenshot 2020-12-11 at 11 28 24 AM

**Comment by lipis** [comment]
Can we hide them on mobile view? 

```
    @media #{$media-query} {
      display: none;
    }
```

**Comment by dwelle** [comment]
We need to remember that if we ever switch from `grid` to `flex` layout, those `self-align: left/end` won't work [pretty much anywhere](https://caniuse.com/mdn-css_properties_align-self_flex_context_left_right)

**Review by lipis — APPROVED** [review]

**Comment by dwelle** [comment]
We should rebase on master and add a shortcut for the newly added `Cut` (unless it's automatic — don't recall).

**Pull request merged**
