### PR TITLE
Deploy static to gh-pages

### LINKED ISSUE #68: Setup website
I just bought excalidraw.com. We should figure out how to setup CI to build and publish it somewhere, either github pages or netlify

### PR DESCRIPTION
**Pull request by nanot1m**
Fixes #68

### CODE REVIEW

**Comment by nanot1m** [comment]
@vjeux can you enable github pages from the repository settings?

**Comment by vjeux** [comment]
image

It should already be enabled

**Comment by vjeux** [comment]
@nanot1m I just added you admin to the repo

**Comment by nanot1m** [comment]
@vjeux thanks! Now we need to configure DNS. It should point to excalidraw.github.io/excalidraw

**Comment by vjeux** [comment]
Okay, should be done. We'll see if it works in a few hours

**Comment by nanot1m** [comment]
Ok, configured script `deploy` — it is deploying excalidraw app to github pages

**Comment by vjeux** [comment]
It's happening!

image

**Comment by vjeux** [comment]
Should be ready to ship no?

**Comment by nanot1m** [comment]
I'll resolve conflicts and will merge it

**Comment by vjeux** [comment]
<3

**Pull request merged**
