### PR TITLE
feat: replaces fontSize and fontFamily text with icons

### PR DESCRIPTION
**Pull request by hitgo00**
Screenshot 2021-01-26 at 5 40 15 AM

Changes the font family and font size text with icons as discussed in #2454.
Same for fontAlign is in #2379.

### CODE REVIEW

**Comment by lipis** [comment]
Could you include the changes from this PR to yours: #2379 so we'll take them in one go?

**Comment by hitgo00** [comment]
Sure, will do that.

**Comment by dwelle** [comment]
Thanks for the PR!

Some points:

- Can we use FontAwesome icons for the [pen](https://fontawesome.com/icons/pen?style=solid) & [code](https://fontawesome.com/icons/code?style=solid) to align?
- Let's align the letter icons look with the look of other property icons (add padding, make the letters bolder...), especially so that the letter in `fontFamily` isn't so visually different to the sibling icons (especially in terms of height/padding)

**Comment by hitgo00** [comment]
Screenshot 2021-02-11 at 2 28 47 AM
Preview screenshot for icons update.

**Comment by dwelle** [comment]
Looking good, but I think these icons need even less height. I've tried 16px and 14px. Personally would go with 14px:

image image

We'll also need to fix a case when you're changing the props while editing text. It shouldn't kick you out (confirm).

**Comment by dwelle** [comment]
Also, how about changing the label from `Font family` → `Font style`? /cc @lipis

**Comment by lipis** [comment]
`Font style` makes more sense.. Family is the CSS thingy :)

**Comment by lipis** [comment]
> Looking good, but I think these icons need even less height. I've tried 16px and 14px. Personally would go with 14px:

14 is good.. and we can tweak later if needed.

**Review by lipis — APPROVED** [review]
`npm run test:update` I guess

**Comment by hitgo00** [comment]
@lipis @dwelle Rebased with master and updated tests ✅.

**Comment by dwelle** [comment]
@hitgo00 cool, thanks. One last thing: can you change the height to 14px as [proposed above](https://github.com/excalidraw/excalidraw/pull/2857#issuecomment-777416891)? I didn't want to hack it via padding and not sure what you used to edit the SVG.

**Comment by hitgo00** [comment]
@dwelle sure, but I think we'll still need to give padding to svg, otherwise size of the button will also be reduced which we don't want I guess 🤔. 

Does this look good?
Screenshot 2021-03-22 at 3 25 27 AM
`    width: 36px;
    height: 14px;
    padding: 2px;`

**Review by ad1992 — APPROVED** [review]

**Comment by dwelle** [comment]
Thank you @hitgo00 ❤️

**Pull request merged**
