### PR TITLE
Set Trailing Comma to `all`

### PR DESCRIPTION
**Pull request by lipis**
https://medium.com/@nikgraf/why-you-should-enforce-dangling-commas-for-multiline-statements-d034c98e36f8

### CODE REVIEW

**Comment by dwelle** [comment]
Haven't read the article (yet), but I def agree. When there's prettier involved, it's very useful to have dangling commas. :+1:

**Comment by lipis** [comment]
Better diffs among other cool things regarding dangling commas :)

(I think in the upcoming version 2, it will be default)

**Comment by voluntadpear** [comment]
That reason #2 for dangling commas from the medium post makes a lot of sense! Copy and pasting can be really annoying without them 😅

**Comment by lipis** [comment]
@vjeux?

**Comment by vjeux** [comment]
Sure, go for it

**Pull request merged**
