### PR TITLE
clear selection from copied/duplicatated group

### PR DESCRIPTION
**Pull request by ReneCode**
fix for [#1894](https://github.com/excalidraw/excalidraw/issues/1894)

The bug is: ```appState.selectedGroupIds``` stays on the old copied group. It has to set to the new created group(s)

two places to fix:
- App.addElementsFromPasteOrLibrary (cmd-v)
- actionDuplicationSelection (cmd-d)

one new utility-function: getGroupIdsFromElements

### CODE REVIEW

**Comment by ReneCode** [comment]
Resolve the merge conflicts (globalScene / this.scene)

**Comment by dwelle** [comment]
Reviewed and ended up not needing the `getGroupIdsFromElements()` helper and instead reused the `selectGroupsForSelectedElements()`. This also fixes a bug where if you duplicated nested groups, you ended up selecting even the nested ones. `selectGroupsForSelectedElements()` accounts for this.

FYI for the future: avoid mutating `appState` (which you did in the duplicate action). We currently don't type check against it (I made the passed `AppState` readonly, but it wouldn't catch the nested mutation --- for that we'd need to use deepReadonly which may be pretty slow I reckon and we'd need to import it from somewhere).

And finally, just in case you're interested: your `getGroupIdsFromElements()` helper could have been shorter:

```
return [...new Set(elements.flatMap((element) => element.groupIds))];
```

**Comment by dwelle** [comment]
Thanks for the PR!

**Comment by ReneCode** [comment]
@dwelle Thank you a lot for your detailed comment / explanation. 

That is the kind of feedback I like a lot. It helps me be to become a better developer.

**Pull request merged**
