### PR TITLE
Easier testing

### LINKED ISSUE #895: Create a manual test plan and turn it into automated tests
We should develop a comprehensive manual test plan and turn it into automated tests. Here's what I have so far:

* Draw every shape, multi-segment arrow, multi-segment line, single-line text, and multi-line text on the canvas
* Change the properties (color etc) of a shape and text
* Resize an element (try every resize handle)
* Click select an element and drag it.
* Alt-drag to duplicate an element
* Click an an element, shift-click others to select a group. Drag the group.
* Pinch-to-zoom works on both desktop touchpad and iOS
* 2-finger-scroll works on desktop touchpad
* Export the file. The preview looks correct. Download the file
* Click the trash button. It clears the screen.
* Reload the file saved above. It looks correct.
* Load a [big file](https://drive.google.com/open?id=1Yb4UPBiHVXQMmqMN73tirl2zHkKlabE3) and drag one of the elements. It drags smoothly.

### PR DESCRIPTION
**Pull request by petehunt**
This diff fixes #895. Adds some test utils and snapshot tests for the various pieces of application state so we can protect against unintended regressions.

It implements the full manual test plan described in #895 with the following exceptions:
* jsdom doesn't support WYSIWYG text
* jsdom doesn't support workflows with `window.confirm`, so I couldn't test exporting the scene
* I left out performance testing. However, since we're snapshotting the render count, these tests would have caught previous performance regressions I think, so I feel that they're pretty good as is.

### CODE REVIEW

**Comment by j-f1** [comment]
Could you use `jest.mock` to mock the `nanoid` module so we could keep using it?

```js
let counter = 0;
const reset = () => (counter = 0);
jest.mock("nanoid", () => () => counter++);
```

**Comment by petehunt** [comment]
i brought back `nanoid()` in a slightly different way per your suggestion and i added a *lot* more tests

**Comment by petehunt** [comment]
This PR now closes #895

**Comment by vjeux** [comment]
Thanks! That's going to be super helpful!

**Pull request merged**
