### PR TITLE
fix: Fix centering element on init

### PR DESCRIPTION
**Pull request by andresriveratoro**
Elements aren't being centered correctly when initializing the scene because scene.appState isn't taking into account width and height props when passed.

### CODE REVIEW

**Comment by ad1992** [comment]
is this still needed @andresriveratoro ? works fine for me on init.

**Review by lipis — APPROVED** [review]
This is a fix for mobile.

**Comment by lipis** [comment]
> This is a fix for mobile.

Or at least that's what I though.. not sure if this does anything after all.

**Comment by dwelle** [comment]
It's needed for non-zero canvas offsets. Ultimately, we should handle this differently than explicitly passing into one calculation, but I guess for now it works.

**Comment by dwelle** [comment]
Thanks for the PR @andresriveratoro.

**Pull request merged**
