### PR TITLE
confirm arrow on doubleclick

### LINKED ISSUE #673: Arrow: clicking on the last point should finish the arrow
Right now, it just creates another point. The only way to finish the arrow is to press escape.

### PR DESCRIPTION
**Pull request by dwelle**
10px delta too big?

Also tends to create text right after (https://github.com/excalidraw/excalidraw/issues/740), but that's for another time.

Fixes #673

### CODE REVIEW

**Comment by vjeux** [comment]
Are you also going to update the mouse move rendering to not draw the last point if you're one the "commit zone"?

**Comment by dwelle** [comment]
> Are you also going to update the mouse move rendering to not draw the last point if you're one the "commit zone"?

Sounds good, lemme see if it's easy to do.

**Comment by dwelle** [comment]
Mhm, it'll require tracking separately whether we're inside the commit zone or not, so as to know whether we can safely remove the last (uncommitted) point. My brain is dead right now, so will leave it for tomorrow.

**Comment by lipis** [comment]
Works nice though.. If we ignore about the new text element after finishihg.

**Comment by dwelle** [comment]
@lipis I'm done with that too, but it turned out into some codebase refactor that I want to make a different PR for first, and when that's merged, rebase this one on it.

**Comment by dwelle** [comment]
Force-pushed with full implem. Not sure if current behavior is ideal: when you create a new point, the next uncommitted point (preview) is not shown until you leave the commit zone (10px). If you leave the commit zone and then go back (hover over last committed point), the uncommitted point is removed (and cursor changes).

Any tips how to make this look better welcome.

excalidraw_confirm_arrow

Note: if we want to show a hint, we'd probably need to create a special state prop for `isInsideCommitZone`.

**Comment by lipis** [comment]
I think it's great. We can just change the current hint on how to finish the line.. Adding the double click as the first option.

**Comment by dwelle** [comment]
Went with `Click on last point or press Escape or Enter to finish` because you don't necessarily need to double click. If you come up with something better, feel free to change. I'm off to sleep.

**Comment by petehunt** [comment]
how about mobile? can we add longpress as a replacement for double click?

**Comment by vjeux** [comment]
There's a [√] button at the bottom to finalize the curve. It's not very visible though

**Comment by dwelle** [comment]
> This is awesome, thanks for pushing this through. The only small thing is that when you click to create a new point, it doesn't change the cursor from + to the hand, it stays with the +. You need to move by 1px to have the cursor change.

@vjeux fixed. I was living under confirmation bias, thinking it's a browser behavior we can't work around. But that's only related to CSS, not JS :).

**Pull request merged**
