### PR TITLE
Implement redo

### LINKED ISSUE #188: Implement redo
Besides `Cmd + Z` to undo, it would be nice to support `Cmd + Shift + Z` to redo changes.

I'd like to work on that!

### PR DESCRIPTION
**Pull request by voluntadpear**
Closes #188

### CODE REVIEW

**Comment by Fausto95** [comment]
I think that adding undo/redo buttons would be nice too.

**Comment by Fausto95** [comment]
Btw, I just tried <kbd>Shift + Cmd + Z</kbd> and nothing happened

**Comment by voluntadpear** [comment]
> I think that adding undo/redo buttons would be nice too.

Agree! I'll add it as part of this

> Btw, I just tried Shift + Cmd + Z and nothing happened

I'll debug that a bit and see why could it be. It seems to be working fine for me so far.

**Comment by vjeux** [comment]
The code is surprisingly small! Great job :)

cmd-shift-z works well for me.

**Comment by vjeux** [comment]
I just added you as a collaborator!

**Pull request merged**
