### PR TITLE
Add Manifest File

### PR DESCRIPTION
**Pull request by Fausto95**
TODO: 
- [x] Home Icon
- [x] Splashscreen image
- [ ] StatusBar color

### CODE REVIEW

**Comment by j-f1** [comment]
It looks like the iOS splash screen has to be the exact size of the device it’s run on, and one article I saw online enumerated the sizes:

```js

<!-- iPhone Xs Max (1242px x 2688px) --> 
<link rel="apple-touch-startup-image" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3)" href="/apple-launch-1242x2688.png"> 
<!-- iPhone Xr (828px x 1792px) --> 
<link rel="apple-touch-startup-image" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2)" href="/apple-launch-828x1792.png"> 
<!-- iPhone X, Xs (1125px x 2436px) --> 
<link rel="apple-touch-startup-image" media="(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3)" href="/apple-launch-1125x2436.png"> 
<!-- iPhone 8 Plus, 7 Plus, 6s Plus, 6 Plus (1242px x 2208px) --> 
<link rel="apple-touch-startup-image" media="(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3)" href="/apple-launch-1242x2208.png"> 
<!-- iPhone 8, 7, 6s, 6 (750px x 1334px) --> 
<link rel="apple-touch-startup-image" media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2)" href="/apple-launch-750x1334.png">  
<!-- iPad Pro 12.9" (2048px x 2732px) --> 
<link rel="apple-touch-startup-image" media="(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2)" href="/apple-launch-2048x2732.png"> 
<!-- iPad Pro 11” (1668px x 2388px) --> 
<link rel="apple-touch-startup-image" media="(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2)" href="/apple-launch-1668x2388.png"> 
<!-- iPad Pro 10.5" (1668px x 2224px) --> 
<link rel="apple-touch-startup-image" media="(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2)" href="/apple-launch-1668x2224.png"> 
<!-- iPad Mini, Air (1536px x 2048px) --> 
<link rel="apple-touch-startup-image" media="(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2)" href="/apple-launch-1536x2048.png">
```

I think it would be best if the splash screen matched the actual app UI to some degree. Maybe we could render them during the build process?

**Comment by Fausto95** [comment]
> It looks like the iOS splash screen has to be the exact size of the device it’s run on, and one article I saw online enumerated the sizes:
> 
> ```
>  
> <link rel="apple-touch-startup-image" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3)" href="/apple-launch-1242x2688.png"> 
>  
> <link rel="apple-touch-startup-image" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2)" href="/apple-launch-828x1792.png"> 
>  
> <link rel="apple-touch-startup-image" media="(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3)" href="/apple-launch-1125x2436.png"> 
>  
> <link rel="apple-touch-startup-image" media="(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3)" href="/apple-launch-1242x2208.png"> 
>  
> <link rel="apple-touch-startup-image" media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2)" href="/apple-launch-750x1334.png">  
>  
> <link rel="apple-touch-startup-image" media="(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2)" href="/apple-launch-2048x2732.png"> 
>  
> <link rel="apple-touch-startup-image" media="(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2)" href="/apple-launch-1668x2388.png"> 
>  
> <link rel="apple-touch-startup-image" media="(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2)" href="/apple-launch-1668x2224.png"> 
>  
> <link rel="apple-touch-startup-image" media="(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2)" href="/apple-launch-1536x2048.png">
> ```
> 
> I think it would be best if the splash screen matched the actual app UI to some degree. Maybe we could render them during the build process?

Yeah, I still work on this

**Comment by lipis** [comment]
That's a bit annoying to have separate image per device.. are you sure we can't get away with fewer ones? I think on Android it puts it in the middle and the rest is background color.. and works fine.

**Comment by j-f1** [comment]
@lipis Nope — according to [this article](https://medium.com/appscope/adding-custom-ios-splash-screens-to-your-progressive-web-app-41a9b18bdca3) and my tests, the current launch image doesn’t work.

**Comment by lipis** [comment]
Don't we love the Apple way of doing things sometimes?! 🤕 🤦‍♂

**Comment by Fausto95** [comment]
I'm surprised that the launch image is working on Android(just tested it), anyway.. I'll be working on improving all of the things on the Todo list.

**Comment by lipis** [comment]
Android ❤️

**Comment by j-f1** [comment]
I wonder if it would make sense to make this a React Native app too.

**Comment by Fausto95** [comment]
@lipis I don't have an Android rn, could you test this?

**Comment by Fausto95** [comment]
Just tested on Android and is working just like the iOS version 😍

**Comment by lipis** [comment]
Works nicely on Android..

**Comment by Fausto95** [comment]
So nice!

**Comment by lipis** [comment]
Next thing.. offline support.

**Comment by lipis** [comment]
@Fausto95 could you add all the images from this PR to the https://github.com/excalidraw/excalidraw-logo repo?

Create an initial PR the way you think it's best and we could iterate for possible structure :)

**Comment by Fausto95** [comment]
yea, I can do that!

**Pull request merged**
