### PR TITLE
make container fullscreen

### PR DESCRIPTION
**Pull request by dwelle**
This PR ensures the app doesn't scroll in case of overflow (mainly due to `.sidePanel`) by making it `fixed` and spanning the window, and making the `.sidePanel` scrollable, if need be.

Without this fix, there are 2 issues:

1. Double scrollbar (i.e., one `window` scrollbar, and one inside the canvas).
2. Bug in current mouse events position computation:
    excalidraw_offset_bug

The (2) can be fixed by changing the algo, I guess. (1) can't be without a fix like this PR.

Caveat: since the `.sidePanel` must have fixed with (AFAIK), some elements such as the tools which must (?) fit on one line must be hacked around to ensure they're not covered by scrollbar. Currently, they can fit if we discard the fixed `margin-right` for them, and instead space them out with `justify-content: space-between`. But this will work only so far as we don't add another tool (which I reckon we might: the `line` tool) --- then we'll either need to wrap, or change their width.

### CODE REVIEW

**Comment by dwelle** [comment]
Btw, do we want to introduce LESS/SCSS to make working with CSS easier?

**Comment by vjeux** [comment]
Feel free to merge when you think it's ready

**Comment by vjeux** [comment]
For less/scss, if that makes you happy, go for it.

**Comment by vjeux** [comment]
Though, I'm not sure it's supported in create-react-app so that will make it annoying...

**Comment by dwelle** [comment]
SCSS is supported by default by CRA, so will use that.

**Pull request merged**
