### PR TITLE
Consistent icons across the UI 

### PR DESCRIPTION
**Pull request by tomfejer**
icons changed to feather and feather styled icons

### CODE REVIEW

**Comment by Fausto95** [comment]
image

Cropped icons :(

**Comment by tomfejer** [comment]
> 
> 
> Cropped icons :(

🙏 @Fausto95 . fixed:
Screenshot 2020-08-15 at 19 33 28

**Comment by dwelle** [comment]
I'm not sure, but the toolbar buttons themselves may not need a bg. Does it look better? Just throwing both variants + original so people can judge more easily:

image
image
image

**Comment by lipis** [comment]
@vjeux What do you think?

**Comment by vjeux** [comment]
Thanks @dwelle for the before/after. I actually prefer the existing set of icons. I'm not sure if it's because I'm used to them by now or if they are better. My recommendation would be to keep it as is.

Thanks for suggesting a different set of icons!

**Comment by lipis** [comment]
Sorry @tomfejer, but @vjeux is the _boss_ 😃 

Thanks for your time..!

**Pull request closed without merging**
