### PR TITLE
chore: host workbox locally

### PR DESCRIPTION
**Pull request by dwelle**
fix: https://github.com/excalidraw/excalidraw/issues/3121

unclear what the PR prefix should be

### CODE REVIEW

**Comment by lipis** [comment]
> unclear what the PR prefix should be

If in doubt... chore :)

**Review by lipis — APPROVED** [review]

**Comment by lipis** [comment]
Add the file to `.prettierignore`

**Comment by dwelle** [comment]
> Add the file to `.prettierignore`

does prettier reuse `.eslintignore`?

Let's wait a bit before merging, wanna ensure it works correctly.

**Comment by dwelle** [comment]
Turns out we need to include a whole lot more files. I've added all of them, to see what is fetch and what is not, and we'll remove the unnecessary ones in the next step.

**Comment by lipis** [comment]
There is no package for it to download during built time?

**Comment by lipis** [comment]
https://www.npmjs.com/package/workbox-sw

**Comment by dwelle** [comment]
> There is no package for it to download during built time?

Yea, I don't like it either, but with an npm package we'd probably have to set up custom webpack config, which we can't (also I can't figure out which files are required and which not... probably the dev + map files can be removed safely).

**Comment by lipis** [comment]
Would be the ideal though.. as we will get easier the updates.. and not polluting the repo.

instead of webpack we can also have a good old school script copying the files before build..

**Comment by dwelle** [comment]
> Would be the ideal though.. as we will get easier the updates.. and not polluting the repo.

Updates is what we don't want actually, until we migrate to latest workbox/sw (we're still kinda using CRA@3 version).

Either way, it seems out of scope for now. It's much nicer now:

image

Btw, why are we setting eslint to use `.gitignore`:

https://github.com/excalidraw/excalidraw/blob/master/package.json#L100

**Comment by lipis** [comment]
> why are we setting eslint to use `.gitignore`

If I recall the .eslintignore file is ignored automatically, so just adding the ignored files from there on top. Not sure if the latest eslint ignoring them by default..

**Comment by dwelle** [comment]
> If I recall the .eslintignore file is ignored automatically, so just adding the ignored files from there on top. Not sure if the latest eslint ignoring them by default..

It is, but only if not overwritten by `--ignore-path`, apparently. And you can't use multiple paths: https://github.com/eslint/eslint/issues/9794#issuecomment-400252532

Switched to using `.eslintignore`

**Review by lipis — APPROVED** [review]

**Comment by lipis** [comment]
Should we at least file an issue to use the package in the future and do the webpack magic?

**Comment by dwelle** [comment]
> Should we at least file an issue to use the package in the future and do the webpack magic?

If you think it's worthwhile — but it would have to be a non-webpack solution as you suggested, unless we wanted to eject the CRA.

**Pull request merged**
