### PR TITLE
feat: redesigned collab cursors

### PR DESCRIPTION
**Pull request by arnostpleskot**
Updated cursors for collaborators

### CODE REVIEW

**Comment by arnostpleskot** [comment]
Todo:
- [ ] fixed minimal height
- [ ] use the same icon for idle and away
- [ ] move outline/fill to not bleed into each other to prevent dark outline when the cursor has opacity set

**Comment by dwelle** [comment]
one other thing:

- [ ] let's align with Plus and pick random username `<adjective> <animal>` if none is saved in localStorage

**Comment by dwelle** [comment]
Was playing with it and the issue with rotating the colors based on current assigned colors size is that:

1. if the local maps differ per client, they'll assign different colors per remote client (which is prob not a big deal, but if you're on a call and say "click the red avatar" and red is different on each client, that'd be not good)
2. I still think we should prioritize color stability per-id first, especially in the context of Plus where sockets may potentially renew across scenes but you don't want users to get different colors every time when they switch rooms
3. the rotation worked in a way that if it worked out then we'd always pick the same colors in the same order for every room for the first X clients. Not necessarily a problem, but I think the actual first X colors weren't necessarily the best either.

The algo I'm using (which is similar to production) ensures stable colors per id (in OSS, socket, in Plus, user id) with the downside that multiple clients can get the same or similar color.

I'm using hue step size of 10 to not generate very close colors. I'm also increased the lightness a bit because `80` can generate a bit too dark colors for black text (`83` that I used still can though).

**Review by dwelle — APPROVED** [review]

**Comment by dwelle** [comment]
yep, merging. Thanks! 🚀

**Pull request merged**
