### PR TITLE
Add copy to PNG option on context menu

### PR DESCRIPTION
**Pull request by christianalfoni**
I use the canvas as a whiteboard so I am building up lots of drawings. It is very nice to quickly be able to select something and copy it directly to the clipboard as a PNG... I paste stuff very often into Notion, but this would of course work with anything else as well.

### CODE REVIEW

**Comment by dwelle** [comment]
Hi. Good idea. I cleaned it up, made it to work with no selection at all, tweaked the label (requires update of your translation), added a few checks, tweaked the export call.


I was also thinking of a keyboard shortcut, but am not sure what to choose.

**Comment by vjeux** [comment]
More context: https://twitter.com/christianalfoni/status/1238728429127839744?s=21

**Comment by dwelle** [comment]
Missed that thread, cool :).

**Comment by dwelle** [comment]
For keybiding, we could go with `Cmd/Ctrl + Alt/Shift + C`. Not sure what clashes with what out there (or browser/system).

**Comment by vjeux** [comment]
Sounds good to me if we can override it

**Comment by dwelle** [comment]
Used `Cmd/Ctrl + Alt/ + C` (because I thought `Cmd + Shift + C` is more likely to collide with something somewhere). Someone check if this works on Mac, please.

**Comment by vjeux** [comment]
cmd-alt-c is inspect element keybinding on chrome it turns out

image

**Comment by dwelle** [comment]
Ok. `Ctrl + Shift + C` is element-inspection on Windows.

We can go `Alt + Shift + C` or `Cmd/Ctrl + Alt + Shift + C`.

**Comment by vjeux** [comment]
cmd-shift-c also opens the elements inspector :(

**Comment by vjeux** [comment]
```js
    if (event.code === "KeyC" && event.altKey && event.shiftKey) {
```

if we want to make it alt shift c.

We should get some kind of feedback though, it's not clear that it actually copied something to the clipboard

**Comment by dwelle** [comment]
> ```js
>     if (event.code === "KeyC" && event.altKey && event.shiftKey) {
> ```
> 
> if we want to make it alt shift c.

`event.key` doesn't work on Mac? Using `event.code` won't be layout-agnostic.

> We should get some kind of feedback though, it's not clear that it actually copied something to the clipboard

Yes, that's needed even for other actions I think. Will need to be done in another PR.

**Comment by vjeux** [comment]
If you want to use `key`: "Ç"

**Comment by dwelle** [comment]
`Ç` seems even more brittle. I'll use `event.code` then.

**Comment by j-f1** [comment]
I wonder if we should just have Cmd/Ctrl+C copy the element data into JSON and copy PNG/SVG images at the same time

**Comment by vjeux** [comment]
@j-f1 can we actually do that :o

**Comment by dwelle** [comment]
I'll investigate.

**Comment by j-f1** [comment]
I think so? You should be able to call `dataTransfer.setData` with different MIME types and they shouldn’t override each other.

**Comment by dwelle** [comment]
We can't use sync clipboard API for images. But it should work with async API, too. Lemme see.

**Comment by vjeux** [comment]
That'd be ideal! I feel like the overhead of copying the pixels shouldn't be a big deal.

**Comment by dwelle** [comment]
Ok, so here's the deal. We can't (so far AFAIK) copy 2 different MIME types (in fact any MIME type other than `image/png`) using the `ClipboardItem` constructor (and I don't know how to use `DataTransfer` transfer with [async clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/write) --- maybe @tomayac can help).

That said, it wouldn't really matter if we could do that because if we want to migrate to system clipboard for in-app copying of elements again, then storing both `image/png` *and* `text/plain` on the clipboard will likely result in most apps preferring the text over the image, defeating the purpose.

So, either we stick to in-memory for in-app clipboard (elements), and we can use `Cmd+C` right for `image/png` even now, or the deal is over :).

**Comment by dwelle** [comment]
I'll go with `Alt + Shift + C` for now, and when we decide how to proceed with in-app clipboard, we can switch to `Cmd + C`.

**Comment by j-f1** [comment]
Why not `vnd/excalidraw+json` for the JSON data? That would probably not be picked up by other apps.

**Comment by christianalfoni** [comment]
Just wanted to say thanks 😍

**Comment by lipis** [comment]
@christianalfoni Thank you!

**Comment by tomayac** [comment]
> Ok, so here's the deal. We can't (so far AFAIK) copy 2 different MIME types (in fact any MIME type other than image/png) using the ClipboardItem constructor

@dwelle In theory we can, but it's not implemented. Here's a quick [demo](https://brick-flame-snowman.glitch.me/) that fails with `DOMException: Support for multiple ClipboardItems is not implemented.`.

**Comment by dwelle** [comment]
@tomayac yea, I've gotten that far, too :). Wasn't sure if I was doing something wrong, or it wasn't implemented.

**Pull request merged**
