### PR TITLE
Make iOS "safe area" respect dark mode

### PR DESCRIPTION
**Pull request by tomayac**
Before (note the bottom):

Screen Shot 2020-08-20 at 09 19 06

After (note the bottom):

Screen Shot 2020-08-20 at 09 34 52

### CODE REVIEW

**Comment by dwelle** [comment]
Why not use the same bg color as we use instead of black?

**Comment by tomayac** [comment]
> Why not use the same bg color as we use instead of black?

I looked (too briefly?), but I didn't find one. It should be the canvas fill color. Is it defined in the CSS? I could see the island background color, but it would be too bright. It should be pure black IMHO.

**Comment by dwelle** [comment]
It's actually the canvas background color from `appState.viewBackgroundColor`, so not sure how we'd apply that to the `html` unless setting it via JS.

We can keep the black.

**Comment by tomayac** [comment]
> It's actually the canvas background color from `appState.viewBackgroundColor`, so not sure how we'd apply that to the `html` unless setting it via JS.
> 
> We can keep the black.

Sounds good. Merge?

**Comment by dwelle** [comment]
Yep, thanks!

**Pull request merged**
