### PR TITLE
feat: multiple fonts fallbacks

### PR DESCRIPTION
**Pull request by Mrazator**
Adds the possibility to specify an array of base URLs in `EXCALIDRAW_ASSET_PATH`, so that we could register font faces for our bundled fonts with multiple fallbacks, in case of unreachable resources due to:
- network restrictions (vpns, corporate policies, firewalls etc.)
- ad blocker #8290 (only solves first-party if an appropriate filter is set to allow such fonts)
- offline mode
- unknowns

Excalidraw-app now has three font URLs for our bundled fonts:
- DO CDN
- Root domain `excalidraw.com` [_fallback_]
- UNPKG CDN [_fallback_]

Fonts are fetched in the order specified above (with automatic fallbacks), for both:
1. `window.document.fonts.load` API
    - out-of-the-box fallbacks due to multiple sources specified as part of the FontFace object in a CSS familiar `@font-face#source` manner
2. fetch for SVG fonts inlining
    - added custom fallback mechanism
    - in case none of the URLs is reached (i.e. when working offline), we will just inline the last specified URL (unpkg for our bundled fonts or whatever URL we have for other fonts)
    
 Additional improvements:
 - setting CORS for excalidraw.com as the only origin for all the new fonts
 - treating DO CDN as SSOT with a build-step

### CODE REVIEW

**Review by dwelle — APPROVED** [review]

**Comment by dwelle** [comment]
👍

**Comment by zsviczian** [comment]
If Helvetica is used in the scene I get this error
image

**Comment by Mrazator** [comment]
It's probably because I've let it register `Helvetica` font face (line changed below), since I did not observe any impact. Is this thrown for some reason just in Electron? I cannot repro on the PR deployment.

https://github.com/excalidraw/excalidraw/pull/8286/files#diff-f5ccf5aca114071dcadadf871453d462f106971c70d3face46b3a855664e13bfL127

**Comment by Mrazator** [comment]
@zsviczian could you perhaps confirm #8303 solves this?

**Comment by zsviczian** [comment]
I confirm #8303 solves the issue.

The screenshot above is from Excalidraw web: https://excalidraw-7vmwury8n-excalidraw.vercel.app/#json=t11M0HM6UHAPuCgd97kcC,BjJyC9R4u_fj73hS_U5QJQ

I used the preview from the most recently merged PR: https://github.com/excalidraw/excalidraw/pull/8302

**Pull request merged**
