### PR TITLE
Add APJapanesefont.ttf for Japanese handwritten

### PR DESCRIPTION
**Pull request by tell-y**
This PR is for #1615
I'm not sure what is the best way to add new handwritten font for particular language.
I'd like to take reviews about it.
Anyway I'm not picky about APJapanesefont.ttf.

### CODE REVIEW

**Comment by dwelle** [comment]
@tell-y before moving forward, can you supply a link to `APJapanesefont.tff` source with license?

**Comment by tell-y** [comment]
Thank you for considering my PR. @dwelle 
The url link of the font source is [this](http://www8.plala.or.jp/p_dolce/font/ap1.zip), is zip file.
The author provides the font without specific license type at [here](http://www8.plala.or.jp/p_dolce/site3.html) and ReadMeあんずもじ.txt in the zip file.
Today I contacted the author to ask about permission to use the font. Then the author has been accepting about it :)

**Comment by dwelle** [comment]
> Today I contacted the author to ask about permission to use the font. Then the author has been accepting about it :)

Unclear whether he responded and if he is aware of the full extent it will be used to. 

In particular, in his FAQ he specifies (google translated):

> ・Redistribution is prohibited. What is redistribution?
> 　To give, distribute, or sell the font file itself.
> 
> ・Can I use it for apps (for sale)?
> 　It's ok to embed fonts in your app, but
> 　it's NG to have them installed from your own server.
> 　It will be redistributed.

I've sent him an email myself, with more details.

**Comment by dwelle** [comment]
@tell-y the font author hasn't replied to me in 9 days, so perhaps it's best to look elsewhere?

**Comment by tell-y** [comment]
Hi @dwelle 
Sorry for late to take action. I received a email from the author about it. I have asked him/her to send a reply to you.
He/She is trying to understand how the font is used on excalidraw. I explained about basic usage and export feature.

> it's best to look elsewhere?

Can we wait a reply more few days? I want to wait a reply because he/she basically agree to use the font. Of course, I know it's better to choice any font which has more clear license. But I don't know a japanese font that is supported [joyo-kanji](https://en.wikipedia.org/wiki/J%C5%8Dy%C5%8D_kanji), is good handwritten style and is maintained now.

**Comment by dwelle** [comment]
> Can we wait a reply more few days?

Absolutely.

**Comment by dwelle** [comment]
@tell-y I've gotten no replies. If you can find an alternative, that would be great.

**Comment by dwelle** [comment]
Closing as there seems to be lack of interest.

**Pull request closed without merging**
