### PR TITLE
feat: update design of ImageExportDialog

### PR DESCRIPTION
**Pull request by are**
This PR updates the design of the image export dialog.

### CODE REVIEW

**Comment by dwelle** [comment]
- [ ] when opening the dialog while in dark mode, the export preview is in dark mode regardless of the export theme setting

    image

- [ ] the settings buttons should have dark mode styling (when in dark mode)

    image

    same for this border:
    
    image


- [ ] the export buttons should have `:hover` and `:active` styling

    image

- [ ] same with at least the scales radio buttons (later we should do so with the toggle buttons as well, but we'll need to figure out the design for it)

    image

- [ ] let's make all the buttons' `outline` CSS only on `:focus-visible` (change from production)

    image

- [ ] present in production, but let's fix this and make sure the buttons prevent user selection

    image

- [ ] the preview should fill preview container (with some padding), as long as the exported content is big enough (i.e., do not scale the preview above 100% of the actual content size). You can check how it behaves in production.

    image

**Comment by are** [comment]
Thanks for the feedback! I implemented all of those changes. Here is the final look:
export-dialog

**Comment by dwelle** [comment]
A few more tiny things:

- [ ] let's keep the preview container padding from production, which used:

    ```css
    --preview-padding: calc(var(--space-factor)*4);
    padding: var(--preview-padding);
    box-sizing: border-box
    ```

    image

- [ ] something wrong with the padding rendering of the radio buttons container, when it's just 1px. Chrome sometimes misaligns vertically, or the 1px padding looks too small. Unsure if rendering bug, or css. I'd nevertheless increase to 2px (I've pinged on figma).

**Comment by dwelle** [comment]
Pushed a few changes:

- removed the `background` for `RadioGroup` `:hover` because it didn't look that great with 0 gap between them. Changed to darker color, which is barely visible, but let's leave it for now. [`2690ef5` (#6614)](https://github.com/excalidraw/excalidraw/pull/6614/commits/2690ef5a880e971b6adbb8a00648e7517528b643)
- changed RadioGroup padding as per latest figma discussion [`4601363` (#6614)](https://github.com/excalidraw/excalidraw/pull/6614/commits/460136364ad571d2818e39f16993a93e36d43170)
- tweaked `Switch` `:active` styling for better feel [`29484aa` (#6614)](https://github.com/excalidraw/excalidraw/pull/6614/commits/29484aad25273ed3458a787c345a6b066d2bd177)
- aligned Model fade-in animation with Plus which is something I wanted to do for a long time. Much better feel. [`928d7f1` (#6614)](https://github.com/excalidraw/excalidraw/pull/6614/commits/928d7f135e666454df85835be3d8ba103f3a3b3c)
- made the `props.title` required, making you to pass `false` explicitly if needed, for better type safety. And merged `props.wide` & `props.small` into `props.size`.  [`82cb451` (#6614)](https://github.com/excalidraw/excalidraw/pull/6614/commits/82cb451084bec7cf6829d6885da11e06038da702)

**Review by dwelle — APPROVED** [review]
Alright, let's merge! Woohoo 🎉

**Pull request merged**
