### PR TITLE
Store background color in backend

### PR DESCRIPTION
**Pull request by lipis**

### CODE REVIEW

**Comment by dwelle** [comment]
LGTM.

Btw, great job with the backend & url export!

**Comment by lipis** [comment]
Thank you! Can you take care of #476

**Comment by dwelle** [comment]
Top-right corner already has the GH icon. Also not sure how this ties to @vjeux's idea of simple UI. If he, or @nanot1m gives a thumbs up, I can work on it. Otherwise I'd first discuss it?

**Comment by lipis** [comment]
Top left.. my bad :)

**Comment by lipis** [comment]
Let's continue the discussion there if needed..

**Pull request merged**
