### PR TITLE
prettify codebase

### PR DESCRIPTION
**Pull request by dwelle**
We updated prettier recently which changes styling in several files. So let's update the codebase so we don't push unrelated changes in other PRs.

### CODE REVIEW

**Comment by lipis** [comment]
Why it's passing the linting tests though on previous PRs..? Something is fishy here..

**Comment by dwelle** [comment]
Mhm and not passing on this one. Am I still on an older one myself? Lemme investigate.

**Comment by lipis** [comment]
delete `node_modules` and stop using yarn!

**Comment by dwelle** [comment]
> delete node_modules and stop using yarn!

That's not it. I wasn't on latest. How many times have we updated prettier in the last few days?

Closing.

**Comment by lipis** [comment]
https://github.com/excalidraw/excalidraw/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed+Bump+prettier+from

**Pull request closed without merging**
