### PR TITLE
Add keybindings for color picker

### PR DESCRIPTION
**Pull request by vjeux**
This adds the ability to navigate using left/right/bottom/up keys and shows key bindings for all the different colors. This is only optimized for the qwerty keyboard layout, but unfortunately it's not possible to detect other keyboard layouts :(

### CODE REVIEW

**Comment by vjeux** [comment]
cc @emilsjolander, let me know what you think! Next step to finish your workflow is to create a shortcut to open this panel (maybe `c` for stroke color and `b` for shape background color)

**Comment by dwelle** [comment]
I'm thinking about preventing other hotkeys when picker is open. Currently, when you mistype `5` and instead hit `6`, it changes tool to `line`.

**Comment by vjeux** [comment]
Good idea, should be trivial: move the stopImmediatePropagation outside of the if :)

**Comment by dwelle** [comment]
Also maybe double-key to confirm? And `Enter` to confirm, too?

**Comment by vjeux** [comment]
Enter is equivalent to space, it selects the color. Pressing enter/space again to close would make sense to me

**Comment by dwelle** [comment]
Made `focus` (i.e. selecting color in any way) update color, and `enter` to confirm. Also, ensured that picker has pre-selected active color on open.

**Pull request merged**
