### PR TITLE
Adding pull request template

### PR DESCRIPTION
**Pull request by Rafi993**
## What type of PR is this?

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [x] Documentation Update

## What does it do?
Adds template for PR to make it easier for the maintainers

## Related issue

https://github.com/excalidraw/excalidraw/issues/2777

## QA Instructions, Screenshots, Recordings

NA
### UI accessibility concerns?
NA
## Tests?

- [ ] yes
- [x] no, reason? this is a pull request template update
- [ ] I need help with writing tests

### CODE REVIEW

**Comment by lipis** [comment]
I'm not the biggest fan of these templates.. do we really need it?

**Comment by dwelle** [comment]
Agreed with @lipis. Rationale in https://github.com/excalidraw/excalidraw/issues/2777#issuecomment-759566307

**Comment by dwelle** [comment]
Though we may have a template with one single comment:

```
<!-- For guidlines, see https://github.com/excalidraw/excalidraw/blob/master/CONTRIBUTING.md -->
```

@lipis wdyt?

**Comment by lipis** [comment]
Isn't the contributing link shown to the non-members of the project when they are creating PR anyway.. I remember something like that.. I prefer to have nothing, we didn't have any issues so far with the contributions anyway.

**Comment by dwelle** [comment]
Yea, I dimly remember something like that. Ok, let's leave it as is.

**Pull request closed without merging**
