### PR TITLE
feat: render footer as a component instead of render prop

### PR DESCRIPTION
**Pull request by ad1992**
Partially fixes https://github.com/excalidraw/excalidraw/issues/5960

We don't render the footer in mobile hence there is no need to use the device when rendering the footer in the host.
It will be taken care once have hamburger api

- [x] Remove `renderFooter` prop and render it as a component instead, the api would for package consumers would be 👇🏻 

```js
<Excalidraw>
<Footer>
</Excalidraw>
```

- [x] Create a FooterCenter component and export as Footer to host
- [x] Update example
- [x] Tests
- [x] update docs

### CODE REVIEW

**Review by dwelle — APPROVED** [review]

**Comment by ad1992** [comment]
@dwelle I have updated the docs, we can merge this if it looks good

**Review by dwelle — APPROVED** [review]

**Comment by zsviczian** [comment]
@ad1992 , @dwelle ,
I might be misunderstanding something here... but it seems that with this change, the custom component a.k.a. custom footer no longer displays in the mobile menu. I don't understand the logic. If a custom component/action is implemented, like, for example, element comments in the example code, then you'd want to make that available in mobile view as well.

**Comment by ad1992** [comment]
> @ad1992 , @dwelle , I might be misunderstanding something here... but it seems that with this change, the custom component a.k.a. custom footer no longer displays in the mobile menu. I don't understand the logic. If a custom component/action is implemented, like, for example, element comments in the example code, then you'd want to make that available in mobile view as well.

@zsviczian the footer will go into Hamburger menu in menu, I will take care of this in https://github.com/excalidraw/excalidraw/pull/6034

**Comment by zsviczian** [comment]
@ad1992 Excellent, then I will wait with using the customer footer. Thanks!

**Pull request merged**
