### PR TITLE
feat: export types for package @excalidraw/excalidraw 🎉 

### PR DESCRIPTION
**Pull request by ad1992**
fixes https://github.com/excalidraw/excalidraw/issues/2514
pushed [here](https://codesandbox.io/s/excalidraw-types-9h2dm)

- [x] `excalidraw-app` types are shared with core hence getting added, fix it so it doesn't get added.
    - [x] Pre requirement https://github.com/excalidraw/excalidraw/pull/3353, reduces ~4 errors
    - [x] Pre requirement https://github.com/excalidraw/excalidraw/issues/3354, reduces ~1 error
- [x] There are ~73 errors still when exporting types which needs to be fixed so all types are exported correctly, the build action is failing for same reason 😉 
- [x] update readme/changelog

### CODE REVIEW

**Comment by dwelle** [comment]
> There are ~73 errors

27 of them can be resolved by including `"src"` in the tsconfig. Not sure what side effect it'll have.

**Comment by ad1992** [comment]
> > There are ~73 errors
> 
> 27 of them can be resolved by including `"src"` in the tsconfig. Not sure what side effect it'll have.

It will start including the other folders also for example `tests`, `excal-app` so I am adding the entry point of package so only those types are included, however `excal-app` is also getting added now as its shared so that we need to fix in core.

**Comment by dwelle** [comment]
> > > There are ~73 errors
> > 
> > 
> > 27 of them can be resolved by including `"src"` in the tsconfig. Not sure what side effect it'll have.
> 
> It will start including the other folders also for example `tests`, `excal-app` so I am adding the entry point of package so only those types are included, however `excal-app` is also getting added now as its shared so that we need to fix in core.

Then let's make the `main.d.ts` into a normal `.ts` file and start exporting/importing the types where needed.

**Comment by dwelle** [comment]
> Add lib in tsconfig-types and Add global.d.ts, and errors down to 39 :)

That also works.

**Review by dwelle — APPROVED** [review]
Looks good, let's ship it! :tada:

**Comment by dwelle** [comment]
The output is kinda sad — this https://github.com/microsoft/TypeScript/issues/4433 should help, but it'll probably take years to get done :). Though someone made a rollup plugin to accomplish it more or less: https://github.com/microsoft/TypeScript/issues/4433#issuecomment-460375001 — for other time, though.

**Comment by ad1992** [comment]
> The output is kinda sad — this [microsoft/TypeScript#4433](https://github.com/microsoft/TypeScript/issues/4433) should help, but it'll probably take years to get done :). Though someone made a rollup plugin to accomplish it more or less: [microsoft/TypeScript#4433 (comment)](https://github.com/microsoft/TypeScript/issues/4433#issuecomment-460375001) — for other time, though.

Yep will try it out in next PR, also we might wanna publish the types under `@types` org so will check on the process for that as well.

**Comment by jeremypress** [comment]
Awesome! Thanks for this @ad1992

**Pull request merged**
