### PR TITLE
fix: Add externals to support Preact

### LINKED ISSUE #5909: Preact Not Supported
Is any plan to support preact?
preact doesn't have a `ReactCurrentOwner`, so it will throw exception.

### PR DESCRIPTION
**Pull request by Aloento**
fix #5909

### CODE REVIEW

**Comment by dwelle** [comment]
@excalibot trigger release

**Comment by ad1992** [comment]
So with this change the integration is broken in browser since there are two new externals which are needed now "react-dom/client", "react/jsx-runtime" for which  looks like there are no direct umd builds

**Comment by Aloento** [comment]
it's working on my case 🎉
image

**Comment by dwelle** [comment]
@Aloento @ad1992 I'd actually love to merge this if we figure out the way to fix the `react-dom/client` & `react/jsx-runtime` thing

**Comment by ad1992** [comment]
> @Aloento @ad1992 I'd actually love to merge this if we figure out the way to fix the `react-dom/client` & `react/jsx-runtime` thing

Yep this was breaking in browser, once that's fixed we are good to merge. So will need to check for proper fix for browser .

**Comment by Aloento** [comment]
> @excalibot trigger release

can you run this again @dwelle thx

**Pull request closed without merging**
