### PR TITLE
fix: failing `build:app:docker` post vite migration during docker build

### LINKED ISSUE #6839: Install fail: Self-hosting docker build fail
```bash
xhzn@R440:~/ideaProjects/excalidraw$ docker build -t excalidraw/excalidraw .
[+] Building 6.8s (12/13)                                                                                                                                                                                                                                    docker:default
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                                   0.0s
 => => transferring dockerfile: 379B                                                                                                                                                                                                                                   0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                                      0.0s
 => => transferring context: 171B                                                                                                                                                                                                                                      0.0s
 => [internal] load metadata for docker.io/library/nginx:1.21-alpine                                                                                                                                                                                                   5.8s
 => [internal] load metadata for docker.io/library/node:18                                                                                                                                                                                                             5.8s
 => CACHED [stage-1 1/2] FROM docker.io/library/nginx:1.21-alpine@sha256:a74534e76ee1121d418fa7394ca930eb67440deda413848bc67c68138535b989                                                                                                                              0.0s
 => [build 1/6] FROM docker.io/library/node:18@sha256:c85dc4392f44f5de1d0d72dd20a088a542734445f99bed7aa8ac895c706d370d                                                                                                                                                 0.0s
 => [internal] load build context                                                                                                                                                                                                                                      0.0s
 => => transferring context: 27.99kB                                                                                                                                                                                                                                   0.0s
 => CACHED [build 2/6] WORKDIR /opt/node_app                                                                                                                                                                                                                           0.0s
 => CACHED [build 3/6] COPY package.json yarn.lock ./                                                                                                                                                                                                                  0.0s
 => CACHED [build 4/6] RUN yarn --ignore-optional --network-timeout 600000                                                                                                                                                                                             0.0s
 => CACHED [build 5/6] COPY . .                                                                                                                                                                                                                                        0.0s
 => ERROR [build 6/6] RUN yarn build:app:docker                                                                                                                                                                                                                        0.9s
------
 > [build 6/6] RUN yarn build:app:docker:
0.428 yarn run v1.22.19
0.457 $ cross-env VITE_APP_DISABLE_SENTRY=true VITE_APP_DISABLE_TRACKING=true vite build
0.738 vite v4.4.2 building for production...
0.750 ✓ 0 modules transformed.
0.750 ✓ built in 10ms
0.751 Could not resolve entry module "index.html".
0.753 error during build:
0.753 RollupError: Could not resolve entry module "index.html".
0.753     at error (file:///opt/node_app/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:2245:30)
0.753     at ModuleLoader.loadEntryModule (file:///opt/node_app/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:24671:20)
0.753     at async Promise.all (index 0)
0.786 error Command failed with exit code 1.
0.786 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
Dockerfile:11
--------------------
   9 |
  10 |     COPY . .
  11 | >>> RUN yarn build:app:docker
  12 |
  13 |     FROM nginx:1.21-alpine
--------------------
ERROR: failed to solve: process "/bin/sh -c yarn build:app:docker" did not complete successfully: exit code: 1
```

### PR DESCRIPTION
**Pull request by griimick**
Fix #6839

Added the following to docker context

- `index.html` required entrypoint for vite build
- `vite.config.ts` vite build config

Verified the following now work,
- docker image builds successfully
- `docker compose up` serves excalidraw on local port 3000

### CODE REVIEW

**Comment by LeiTi34** [comment]
I just tried this fix on the newest commit and get the following error.

Removing .dockerignore fixes the problem.

```
docker compose build --no-cache
[+] Building 22.2s (9/13)                                                                                                                                                                            docker:default
 => [excalidraw internal] load build definition from Dockerfile                                                                                                                                                0.0s
 => => transferring dockerfile: 379B                                                                                                                                                                           0.0s
 => [excalidraw internal] load .dockerignore                                                                                                                                                                   0.0s
 => => transferring context: 199B                                                                                                                                                                              0.0s
 => [excalidraw internal] load metadata for docker.io/library/nginx:1.21-alpine                                                                                                                                0.5s
 => [excalidraw internal] load metadata for docker.io/library/node:18                                                                                                                                          0.5s
 => [excalidraw build 1/6] FROM docker.io/library/node:18@sha256:ee0a21d64211d92d4340b225c556e9ef1a8bce1d5b03b49f5f07bf1dbbaa5626                                                                              0.0s
 => [excalidraw internal] load build context                                                                                                                                                                   0.0s
 => => transferring context: 26.98kB                                                                    [+] Building 46.8s (12/13)                                                               docker:default0 => [excalidraw internal] load build definition from Dockerfile                                    0.0s
 => => transferring dockerfile: 379B                                                               0.0sf => [excalidraw internal] load .dockerignore                                                       0.0s0 => => transferring context: 199B                                                                  0.0s
 => [excalidraw internal] load metadata for docker.io/library/nginx:1.21-alpine                    0.5s  => [excalidraw internal] load metadata for docker.io/library/node:18                              0.5s0 => [excalidraw build 1/6] FROM docker.io/library/node:18@sha256:ee0a21d64211d92d4340b225c556e9ef  0.0s
 => [excalidraw internal] load build context                                                       0.0s  => => transferring context: 26.98kB                                                               0.0s0 => CACHED [excalidraw stage-1 1/2] FROM docker.io/library/nginx:1.21-alpine@sha256:a74534e76ee11  0.0s
 => CACHED [excalidraw build 2/6] WORKDIR /opt/node_app                                            0.0s  => [excalidraw build 3/6] COPY package.json yarn.lock ./                                          0.1s1 => [excalidraw build 4/6] RUN yarn --ignore-optional --network-timeout 600000                    43.3s
 => [excalidraw build 5/6] COPY . .                                                                0.5s
 => ERROR [excalidraw build 6/6] RUN yarn build:app:docker                                         2.3s
------
 > [excalidraw build 6/6] RUN yarn build:app:docker:
0.599 yarn run v1.22.19
0.644 $ cross-env VITE_APP_DISABLE_SENTRY=true VITE_APP_DISABLE_TRACKING=true vite build
1.926 vite v4.4.2 building for production...
2.038 transforming...
2.229 ✓ 8 modules transformed.
2.229 [vite-plugin-pwa:build] Could not resolve "../excalidraw-app" from "src/index.tsx"
2.229 file: /opt/node_app/src/index.tsx
2.234 error during build:
2.234 RollupError: Could not resolve "../excalidraw-app" from "src/index.tsx"
2.234     at error (file:///opt/node_app/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:2245:30)
2.234     at ModuleLoader.handleInvalidResolvedId (file:///opt/node_app/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:24650:24)
2.234     at file:///opt/node_app/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:24612:26
2.282 error Command failed with exit code 1.
2.282 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
failed to solve: process "/bin/sh -c yarn build:app:docker" did not complete successfully: exit code: 1
```

**Comment by PseudoResonance** [comment]
You need to add a new line, `!excalidraw-app/` now, because that has been moved out of src.

**Comment by Jan-M** [comment]
Looking at the same problem, thx for adding this.

**Review by DanielJGeiger — COMMENTED** [review]
@griimick Could you add the line @PseudoResonance mentioned?

For the stalled GH checks, you may need to pull in the latest `master` branch.

**Comment by griimick** [comment]
Looks like I messed up the rebase. Closing this in favour of creating a new branch from latest master. Apologies.

**Pull request closed without merging**
