### PR TITLE
Fix Library Menu Layout

### LINKED ISSUE #2492: Browse libraries link is hidden behind the buttons on mobile
Screenshot 2020-12-08 at 11 31 42 PM

### PR DESCRIPTION
**Pull request by Kartik1397**
Fixes #2492

### Desktop
localhost_3000_
### Mobile
mobile

### CODE REVIEW

**Comment by lipis** [comment]
If we are fine with buttons on the left.. could you also remove the following from the `.browse-libraries` class.

```css
max-width: 140px;
text-overflow: ellipsis;
overflow: hidden;
```

**Comment by Kartik1397** [comment]
Hi @lipis, I have removed unwanted css rule.

**Comment by lipis** [comment]
We need to run it with our _designers_ for the final approval :)

**Review by lipis — APPROVED** [review]

**Review by ad1992 — APPROVED** [review]
LGTM 👍

**Comment by lipis** [comment]
Thank you @Kartik1397!

**Pull request merged**
