### PR TITLE
Make dialogs look better on mobile

### PR DESCRIPTION
**Pull request by j-f1**
Ref #138
- make them fill the screen
- switch the X to a back button
- align title to close button on desktop
- add border to file name field for discoverabilty
- fix layout of export dialog on mobile

### CODE REVIEW

**Comment by dwelle** [comment]
Note that in my RoomDialog PR, I've factored the `__close` out to `Modal.css`, so one of us will need to reconcile this.

**Comment by j-f1** [comment]
You can merge first. I don’t mind.

**Comment by lipis** [comment]
> * add border to file name field for discoverabilty

❤️

**Comment by j-f1** [comment]
This is ready for review.

**Pull request merged**
