### PR TITLE
docs: improve grammar, import + render only once

### PR DESCRIPTION
**Pull request by karlhorky**
Hi there, thanks for Excalidraw! Really amazing editor, enables so many things 🙌 

Just a quick PR to improve the grammar and make the `useEffect` with the import run only once (which I believe should be fine)

### CODE REVIEW

**Review by dwelle — APPROVED** [review]

**Review by ad1992 — APPROVED** [review]

**Review by ad1992 — COMMENTED** [review]
@karlhorky can you make the same change in https://github.com/excalidraw/excalidraw/blob/master/src/packages/excalidraw/README_NEXT.md as well?

**Comment by karlhorky** [comment]
Sure, done!

**Comment by ad1992** [comment]
Thanks @karlhorky 🎉

**Comment by karlhorky** [comment]
Glad to help, thanks for the merge!

**Pull request merged**
