### PR TITLE
15-degree rotation locking

### LINKED ISSUE #1451: Is it possible to change the discrete rotation steps from 22.5 to 15 degrees?
Now the discrete steps when pressing the SHIFT key are 22.5 degrees. But 15 degrees is IMHO more useful/logical because then it will be possible to make also 30, 60 etcetera degree diagonals (which are useful in for example transit map sketches)

This is related to my  #1351 issue

### PR DESCRIPTION
**Pull request by dai-shi**
Close #1451

### CODE REVIEW

**Comment by lipis** [comment]
Not for this PR... but maybe it would be nice to show the degrees when the lock is happening! :)

**Comment by dwelle** [comment]
Fix the test and we're good to go.

> Not for this PR... but maybe it would be nice to show the degrees when the lock is happening! :)

Yep.

**Comment by lipis** [comment]
#1629

**Comment by dai-shi** [comment]
@dwelle I'm not super confident with the `expect` change.

**Comment by dwelle** [comment]
Nothing much we can do except hardcode it and hold our fingers. Merging, thanks!

**Pull request merged**
