### PR TITLE
fix: text align center on container bind

### PR DESCRIPTION
**Pull request by Saidbek**
Should fix https://github.com/excalidraw/excalidraw/issues/6434

### CODE REVIEW

**Comment by dwelle** [comment]
Thanks @Saidbek!

Could you add a test for this in `src/tests/binding.test.tsx` (check the test cases at the bottom for inspiration on how to create elements and execute the bind action `h.app.actionManager.executeAction(actionCreateContainerFromText);`.

Also, you can run the `yarn fix:code` to fix the lint issue. ✌

**Comment by ad1992** [comment]
Oops we already have one more PR for this https://github.com/excalidraw/excalidraw/pull/6451/files, probably you both can collaborate in #6451 as the test was added in the PR is well ?

**Comment by ad1992** [comment]
Actually even better would be if you could instead fix the same alignment issue when "wrapping text into container" via context menu, @Saidbek would be you be interested to fix that ?

**Comment by ad1992** [comment]
> Actually even better would be if you could instead fix the same alignment issue when "wrapping text in a container" via context menu, @Saidbek would be you be interested to fix that ?
> 
> EDIT - Here is a concern I have [#6434 (comment)](https://github.com/excalidraw/excalidraw/issues/6434#issuecomment-1508034121) so lets resolve this first before resuming

@Saidbek its resolved let me know if you would like to fix it

**Comment by ad1992** [comment]
closing as #6451 was merged

**Pull request closed without merging**
