### PR TITLE
Proper RTL support

### PR DESCRIPTION
**Pull request by j-f1**
~Will rebase on `master` once #1151 is merged.~

### CODE REVIEW

**Comment by lipis** [comment]
WOW! That was fast :)

**Comment by lipis** [comment]
#1151 is ready.. merge it whenever you want! Has 100% of Arabic in it..

**Comment by vjeux** [comment]
Can you put a screenshot?

**Comment by j-f1** [comment]
@mohammadameer Can you check out [the preview](https://excalidraw-git-arabic.excalidraw-team.now.sh) and tell me if you see anything that looks wrong?

**Comment by lipis** [comment]
Screenshot 2020-04-01 at 9 06 37 PM

------


Screenshot 2020-04-01 at 9 06 49 PM

**Comment by j-f1** [comment]
Screen Shot 2020-04-01 at 14 05 13

**Comment by vjeux** [comment]
Nice! Looks like the pointer should not be shifted :) Not sure if undo/redo makes sense shifted or not.

**Pull request merged**
