### PR TITLE
fix: cancel erase elements on pointer up if eraser is not active on pointer up

### PR DESCRIPTION
**Pull request by ad1992**
fixes https://github.com/excalidraw/excalidraw/issues/4949

### CODE REVIEW

**Comment by dwelle** [comment]
I think we should instead cancel the erasure as @xixixao suggests in https://github.com/excalidraw/excalidraw/issues/4949 as it makes more intuitive sense?

**Comment by ad1992** [comment]
> I think we should instead cancel the erasure as @xixixao suggests in #4949 as it makes more intuitive sense?

Yeah I agree that would make more sense

**Review by dwelle — APPROVED** [review]

**Comment by dwelle** [comment]
Ideally we should restore on keyDown, but that will require us to pass `pointerDownState` to `actionFinalize`, which means we'd have to cache (and invalidate the cache properly). Something for another PR!

Let's ship 🚀 👍

**Comment by ad1992** [comment]
> Ideally we should restore on keyDown, but that will require us to pass `pointerDownState` to `actionFinalize`, which means we'd have to cache (and invalidate the cache properly). Something for another PR!
> 
> Let's ship 🚀 👍

or may move it out of `pointerDownState` altogether, let's discuss that

**Pull request merged**
