### PR TITLE
[WIP] build(package/excalidraw): use cdn to serve the assets. no more copying files :)

### PR DESCRIPTION
**Pull request by ad1992**
for https://github.com/excalidraw/excalidraw/issues/2605
All the assets will be served from https://unpkg.com/
check it out [here](https://codesandbox.io/s/aakansha-testing-xig4w?file=/src/App.js)
package: `aakansha-excalidraw@0.2.1-cdn`

- [ ] Update the script to read the version from the package so we need no update manually
- [ ] Update readme

### CODE REVIEW

**Comment by dwelle** [comment]
I think this should be optional (no idea how) as people (me included) wouldn't want to depend on 3rd parties to load static content (non-reliability one of the reasons — even though unpkg is basically a Cloudflare, I'm not sure what the mean response times are, and what their SLAs are).

**Comment by ad1992** [comment]
> I think this should be optional (no idea how) as people (me included) wouldn't want to depend on 3rd parties to load static content (non-reliability one of the reasons — even though unpkg is basically a Cloudflare, I'm not sure what the mean response times are, and what their SLAs are).

The only way I can think of making optional is having two separate builds, one which we have now and one which loads assets from cdn then it depends on users which they want to use, and for this build, we can keep only the `excalidraw.min.js, and CSS files` rest all will load from CDN. Wdyt ?
This will also allow users to use this package directly via script tag as well.

**Comment by dwelle** [comment]
Ok, let's do two separate builds then. The default (if talking about a default even makes sense, that is) I believe should still be self-hosting IMO.

**Comment by ad1992** [comment]
closing this in favor of #2835

**Pull request closed without merging**
