### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by lipis**

### CODE REVIEW

**Comment by dwelle** [comment]
Why adding english labels to non-english translations? Isn't then gonna show as translated on the crowdin?

**Comment by lipis** [comment]
That's how Crowding does it..no they are not appearing as translated there.. https://crowdin.com/project/excalidraw

**Comment by dwelle** [comment]
Interesting. I wonder how they keep track of what's already translated, then :thinking:

**Comment by dwelle** [comment]
Merge whenever you think it's ready - I have no clue.

**Comment by lipis** [comment]
Have you seen the website? It's all there..

**Comment by dwelle** [comment]
I have, but am not well acquainted with it. What are you referring to?

**Comment by szympajka** [comment]
Hey @lipis, @vjeux  I think you have to approve transactions in Crowdin to show they are accepted :)

**Comment by dwelle** [comment]
> Hey @lipis, @vjeux I think you have to approve transactions in Crowdin to show they are accepted :)

So now when you want to add a translation, you have to go to Crowdin, enter it there, which then creates a PR that you need to merge, and an admin has to go back to Crowdin to also accept the translation? Mhm...

**Comment by lipis** [comment]
@szympajka for now you can autoapprove your own ones.. but in theory would be nice if we have two people per translation so they can proofread it..

**Pull request merged**
