### PR TITLE
feat: Ability to search for a text

### PR DESCRIPTION
**Pull request by liyu1981**
feat: Ability to search for a text

This is my try of [#3826](https://github.com/excalidraw/excalidraw/issues/3826). Seen this is opened for a while, though an important missing part but not yet get there.

There is also another implementation in https://github.com/excalidraw/excalidraw/pull/5435 by @dragonman225. Comparing to that one, I took a different search library and different UI approach. Mine does get the hightlighting part done, which is the obvious difference as I can now see.

Below is a gif showing what it looks alike
Monosnap screencast 2023-11-16 17-19-12

Hopefully this can be reviewed and either mine or @dragonman225's effort can be merged soon.

### CODE REVIEW

**Comment by adrianbienias** [comment]
I would love to see it merged

**Comment by iamericfletcher** [comment]
Awesome job. I can certainly see the utility this feature provides. If I may, my initial reaction to the UI is that the text input would be perhaps less jarring if it were similar to the `more tools` menu. That is, the search text input field would drop down in a similar manner to `more tools` menu thus preserving the positioning of the toolbar. What do you think?

**Comment by guangxuanliu** [comment]
This is awesome, what I really wanted. Why didn't merge ?

**Comment by johnpanos** [comment]
@liyu1981 bro pls 😭

**Comment by Mrazator** [comment]
Closing in favor of https://github.com/excalidraw/excalidraw/pull/8438

**Pull request closed without merging**
