### PR TITLE
Checks on push and fix formatting

### PR DESCRIPTION
**Pull request by lipis**

### CODE REVIEW

**Comment by j-f1** [comment]
It looks like things are running twice now:
Screenshot_2020-03-22 12 17 00

**Comment by dwelle** [comment]
This will put it to the state before https://github.com/excalidraw/excalidraw/pull/511 which means it'll again not work for PRs from forked repos, AFAIK.

**Comment by lipis** [comment]
The we are going to need both.. or how to isolate push only on master?

**Comment by lipis** [comment]
Updated

**Comment by dwelle** [comment]
> The we are going to need both.. or how to isolate push only on master?

No clue. We'll see if this runs them twice. Doesn't look like it does in this case, but maybe for forked PRs, or new PRs in general it will.

**Comment by lipis** [comment]
Check it now.. that's the way.

**Pull request merged**
