### PR TITLE
feat: support excalidrawAPI and remove refs support

### PR DESCRIPTION
**Pull request by ad1992**
closes https://github.com/excalidraw/excalidraw/issues/6177

### CODE REVIEW

**Comment by ad1992** [comment]
@excalibot trigger release

**Comment by dwelle** [comment]
let's remove the `readyPromise` and `ready` flag from the `ExcalidrawImperativeAPI` as well. The `flag` didn't serve much purpose even back then, and the `readyPromise` doesn't serve any purpose now.

On the other hand, we _may_ add `onReady()` subscription on the API that will be triggered once the editor is initialized, but that's for the future

**Comment by ad1992** [comment]
@excalibot trigger release

**Review by dwelle — APPROVED** [review]

**Comment by bric3** [comment]
For anyone following this, that's what I changed :


I have this already

```typescript
    const excalidrawApiRef = React.useRef<ExcalidrawImperativeAPI | null>(null);
    apiBridge = new ExcalidrawApiBridge(excalidrawApiRef)

    const excalidrawRef = React.useCallback((excalidrawApi: ExcalidrawImperativeAPI) => {
        excalidrawApiRef.current = excalidrawApi;
        apiBridge!.dispatchToPlugin({type: "ready"})
    }, []);
```

And that what I changed

```diff
    return (
        <div className="excalidraw-wrapper">
            <Excalidraw
-               ref={excalidrawRef}
+               excalidrawAPI={excalidrawRef}

```

**Pull request merged**
